// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: registry/skills/v1alpha1/skills.proto

// Package skills defines the registry of agent capabilities.
//
// Hexagonal: inbound port — consumed by ReasoningService and MCP discovery tools.
// CODE phase: Distill — skills are distilled patterns ready for reuse.
// PARA: Resources — capabilities available to the org.
// Second brain: Skills are the "what can I do?" self-awareness layer.

package skillsv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Skill represents a single capability exposed to agents.
// Resource name pattern: "skills/{skill_id}" (AIP-122).
type Skill struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name (e.g. "skills/retrieve-memory").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable display name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// What the skill does — used for agent tool selection.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// JSON schema fragments describing the skill's input parameters.
	// Each element is a JSON string representing one parameter's schema.
	InputSchema   []string `protobuf:"bytes,4,rep,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_registry_skills_v1alpha1_skills_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_registry_skills_v1alpha1_skills_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_registry_skills_v1alpha1_skills_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Skill) GetInputSchema() []string {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

// ListSkillsRequest is the request message for
// [SkillsService.ListSkills][registry.skills.v1alpha1.SkillsService.ListSkills].
type ListSkillsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Maximum number of skills to return. Default 50 (AIP-158).
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Token for the next page of results.
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsRequest) Reset() {
	*x = ListSkillsRequest{}
	mi := &file_registry_skills_v1alpha1_skills_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsRequest) ProtoMessage() {}

func (x *ListSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_skills_v1alpha1_skills_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return file_registry_skills_v1alpha1_skills_proto_rawDescGZIP(), []int{1}
}

func (x *ListSkillsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSkillsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListSkillsResponse is the response message for
// [SkillsService.ListSkills][registry.skills.v1alpha1.SkillsService.ListSkills].
type ListSkillsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of skills for the current page.
	Skills []*Skill `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	// Token for the next page. Empty if no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkillsResponse) Reset() {
	*x = ListSkillsResponse{}
	mi := &file_registry_skills_v1alpha1_skills_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkillsResponse) ProtoMessage() {}

func (x *ListSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_skills_v1alpha1_skills_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return file_registry_skills_v1alpha1_skills_proto_rawDescGZIP(), []int{2}
}

func (x *ListSkillsResponse) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListSkillsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetSkillRequest is the request message for
// [SkillsService.GetSkill][registry.skills.v1alpha1.SkillsService.GetSkill].
type GetSkillRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Resource name of the skill (e.g. "skills/retrieve-memory").
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillRequest) Reset() {
	*x = GetSkillRequest{}
	mi := &file_registry_skills_v1alpha1_skills_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillRequest) ProtoMessage() {}

func (x *GetSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_skills_v1alpha1_skills_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillRequest.ProtoReflect.Descriptor instead.
func (*GetSkillRequest) Descriptor() ([]byte, []int) {
	return file_registry_skills_v1alpha1_skills_proto_rawDescGZIP(), []int{3}
}

func (x *GetSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetSkillResponse is the response message for
// [SkillsService.GetSkill][registry.skills.v1alpha1.SkillsService.GetSkill].
type GetSkillResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested skill.
	Skill         *Skill `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillResponse) Reset() {
	*x = GetSkillResponse{}
	mi := &file_registry_skills_v1alpha1_skills_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillResponse) ProtoMessage() {}

func (x *GetSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_skills_v1alpha1_skills_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillResponse.ProtoReflect.Descriptor instead.
func (*GetSkillResponse) Descriptor() ([]byte, []int) {
	return file_registry_skills_v1alpha1_skills_proto_rawDescGZIP(), []int{4}
}

func (x *GetSkillResponse) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

var File_registry_skills_v1alpha1_skills_proto protoreflect.FileDescriptor

const file_registry_skills_v1alpha1_skills_proto_rawDesc = "" +
	"\n" +
	"%registry/skills/v1alpha1/skills.proto\x12\x18registry.skills.v1alpha1\"\x83\x01\n" +
	"\x05Skill\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x04 \x03(\tR\vinputSchema\"O\n" +
	"\x11ListSkillsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"u\n" +
	"\x12ListSkillsResponse\x127\n" +
	"\x06skills\x18\x01 \x03(\v2\x1f.registry.skills.v1alpha1.SkillR\x06skills\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"%\n" +
	"\x0fGetSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"I\n" +
	"\x10GetSkillResponse\x125\n" +
	"\x05skill\x18\x01 \x01(\v2\x1f.registry.skills.v1alpha1.SkillR\x05skill2\xdb\x01\n" +
	"\rSkillsService\x12g\n" +
	"\n" +
	"ListSkills\x12+.registry.skills.v1alpha1.ListSkillsRequest\x1a,.registry.skills.v1alpha1.ListSkillsResponse\x12a\n" +
	"\bGetSkill\x12).registry.skills.v1alpha1.GetSkillRequest\x1a*.registry.skills.v1alpha1.GetSkillResponseBXZVgithub.com/duizendstra/alexandria/go/contracts/registry/skills/v1alpha1;skillsv1alpha1b\x06proto3"

var (
	file_registry_skills_v1alpha1_skills_proto_rawDescOnce sync.Once
	file_registry_skills_v1alpha1_skills_proto_rawDescData []byte
)

func file_registry_skills_v1alpha1_skills_proto_rawDescGZIP() []byte {
	file_registry_skills_v1alpha1_skills_proto_rawDescOnce.Do(func() {
		file_registry_skills_v1alpha1_skills_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_skills_v1alpha1_skills_proto_rawDesc), len(file_registry_skills_v1alpha1_skills_proto_rawDesc)))
	})
	return file_registry_skills_v1alpha1_skills_proto_rawDescData
}

var file_registry_skills_v1alpha1_skills_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_registry_skills_v1alpha1_skills_proto_goTypes = []any{
	(*Skill)(nil),              // 0: registry.skills.v1alpha1.Skill
	(*ListSkillsRequest)(nil),  // 1: registry.skills.v1alpha1.ListSkillsRequest
	(*ListSkillsResponse)(nil), // 2: registry.skills.v1alpha1.ListSkillsResponse
	(*GetSkillRequest)(nil),    // 3: registry.skills.v1alpha1.GetSkillRequest
	(*GetSkillResponse)(nil),   // 4: registry.skills.v1alpha1.GetSkillResponse
}
var file_registry_skills_v1alpha1_skills_proto_depIdxs = []int32{
	0, // 0: registry.skills.v1alpha1.ListSkillsResponse.skills:type_name -> registry.skills.v1alpha1.Skill
	0, // 1: registry.skills.v1alpha1.GetSkillResponse.skill:type_name -> registry.skills.v1alpha1.Skill
	1, // 2: registry.skills.v1alpha1.SkillsService.ListSkills:input_type -> registry.skills.v1alpha1.ListSkillsRequest
	3, // 3: registry.skills.v1alpha1.SkillsService.GetSkill:input_type -> registry.skills.v1alpha1.GetSkillRequest
	2, // 4: registry.skills.v1alpha1.SkillsService.ListSkills:output_type -> registry.skills.v1alpha1.ListSkillsResponse
	4, // 5: registry.skills.v1alpha1.SkillsService.GetSkill:output_type -> registry.skills.v1alpha1.GetSkillResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_registry_skills_v1alpha1_skills_proto_init() }
func file_registry_skills_v1alpha1_skills_proto_init() {
	if File_registry_skills_v1alpha1_skills_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_skills_v1alpha1_skills_proto_rawDesc), len(file_registry_skills_v1alpha1_skills_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_skills_v1alpha1_skills_proto_goTypes,
		DependencyIndexes: file_registry_skills_v1alpha1_skills_proto_depIdxs,
		MessageInfos:      file_registry_skills_v1alpha1_skills_proto_msgTypes,
	}.Build()
	File_registry_skills_v1alpha1_skills_proto = out.File
	file_registry_skills_v1alpha1_skills_proto_goTypes = nil
	file_registry_skills_v1alpha1_skills_proto_depIdxs = nil
}
