version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/go/contracts/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/dataquality/datadiff/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/discovery/privacyfilter/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/discovery/search/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/discovery/search/searchtest/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/google/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/governance/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/iac/governance/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/iac/delivery/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/iac/finops/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/iac/identity/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/iac/observability/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/iac/pulumi/gcpinfra/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/iac/pulumi/stackref/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/iac/workloads/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/observability/audit/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/platform/apierr/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/platform/async/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/platform/cache/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/platform/gcpenv/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/platform/passstore/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/platform/web/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/retry/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/retry/gcp/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/slog-gcp/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/slog-gcp/otelgcp/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
