version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/go/slog-gcp/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/slog-gcp/otelgcp/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/retry/gcp/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/google/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/go/contracts/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
