// Friction captures process pain points for retrospective analysis.
//
// Scrumban: Retro phase — captures what slowed us down.
// CODE: Capture (instant logging) → Organize (sprint summary).
// PARA: Projects — friction is per-sprint, time-bound.
// Hexagonal: core domain — FrictionService defines the port contract.
//
// Models: Scrumban (retro), Theory of Constraints (find bottleneck),
// OODA (friction slows the Observe→Act loop).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: collaboration/friction/v1alpha1/friction.proto

package frictionv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FrictionStatus represents the lifecycle of a friction point.
type FrictionStatus int32

const (
	// Default value.
	FrictionStatus_FRICTION_STATUS_UNSPECIFIED FrictionStatus = 0
	// Newly logged, unreviewed.
	FrictionStatus_FRICTION_STATUS_NEW FrictionStatus = 1
	// Acknowledged and being addressed.
	FrictionStatus_FRICTION_STATUS_ACKNOWLEDGED FrictionStatus = 2
	// Resolved — the pain point is gone.
	FrictionStatus_FRICTION_STATUS_RESOLVED FrictionStatus = 3
)

// Enum value maps for FrictionStatus.
var (
	FrictionStatus_name = map[int32]string{
		0: "FRICTION_STATUS_UNSPECIFIED",
		1: "FRICTION_STATUS_NEW",
		2: "FRICTION_STATUS_ACKNOWLEDGED",
		3: "FRICTION_STATUS_RESOLVED",
	}
	FrictionStatus_value = map[string]int32{
		"FRICTION_STATUS_UNSPECIFIED":  0,
		"FRICTION_STATUS_NEW":          1,
		"FRICTION_STATUS_ACKNOWLEDGED": 2,
		"FRICTION_STATUS_RESOLVED":     3,
	}
)

func (x FrictionStatus) Enum() *FrictionStatus {
	p := new(FrictionStatus)
	*p = x
	return p
}

func (x FrictionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrictionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_collaboration_friction_v1alpha1_friction_proto_enumTypes[0].Descriptor()
}

func (FrictionStatus) Type() protoreflect.EnumType {
	return &file_collaboration_friction_v1alpha1_friction_proto_enumTypes[0]
}

func (x FrictionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrictionStatus.Descriptor instead.
func (FrictionStatus) EnumDescriptor() ([]byte, []int) {
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP(), []int{0}
}

// FrictionCategory classifies friction by type.
type FrictionCategory int32

const (
	// Default value.
	FrictionCategory_FRICTION_CATEGORY_UNSPECIFIED FrictionCategory = 0
	// Tooling issues — broken terminals, slow builds, flaky tests.
	FrictionCategory_FRICTION_CATEGORY_TOOLING FrictionCategory = 1
	// Process issues — too much ceremony, unclear workflow.
	FrictionCategory_FRICTION_CATEGORY_PROCESS FrictionCategory = 2
	// Communication issues — unclear requirements, misalignment.
	FrictionCategory_FRICTION_CATEGORY_COMMUNICATION FrictionCategory = 3
	// Technical debt — missing tests, unrefactored code.
	FrictionCategory_FRICTION_CATEGORY_DEBT FrictionCategory = 4
)

// Enum value maps for FrictionCategory.
var (
	FrictionCategory_name = map[int32]string{
		0: "FRICTION_CATEGORY_UNSPECIFIED",
		1: "FRICTION_CATEGORY_TOOLING",
		2: "FRICTION_CATEGORY_PROCESS",
		3: "FRICTION_CATEGORY_COMMUNICATION",
		4: "FRICTION_CATEGORY_DEBT",
	}
	FrictionCategory_value = map[string]int32{
		"FRICTION_CATEGORY_UNSPECIFIED":   0,
		"FRICTION_CATEGORY_TOOLING":       1,
		"FRICTION_CATEGORY_PROCESS":       2,
		"FRICTION_CATEGORY_COMMUNICATION": 3,
		"FRICTION_CATEGORY_DEBT":          4,
	}
)

func (x FrictionCategory) Enum() *FrictionCategory {
	p := new(FrictionCategory)
	*p = x
	return p
}

func (x FrictionCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrictionCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_collaboration_friction_v1alpha1_friction_proto_enumTypes[1].Descriptor()
}

func (FrictionCategory) Type() protoreflect.EnumType {
	return &file_collaboration_friction_v1alpha1_friction_proto_enumTypes[1]
}

func (x FrictionCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrictionCategory.Descriptor instead.
func (FrictionCategory) EnumDescriptor() ([]byte, []int) {
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP(), []int{1}
}

// Friction represents a logged pain point.
// Resource name pattern: "friction/{friction_id}" (AIP-122).
type Friction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name (e.g. "friction/a1b2c3d4").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the friction point.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Category of friction.
	Category FrictionCategory `protobuf:"varint,3,opt,name=category,proto3,enum=collaboration.friction.v1alpha1.FrictionCategory" json:"category,omitempty"`
	// Lifecycle state.
	Status FrictionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=collaboration.friction.v1alpha1.FrictionStatus" json:"status,omitempty"`
	// Optional. Sprint this friction was logged during.
	Sprint string `protobuf:"bytes,5,opt,name=sprint,proto3" json:"sprint,omitempty"`
	// Output only. Creation time.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Friction) Reset() {
	*x = Friction{}
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Friction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Friction) ProtoMessage() {}

func (x *Friction) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Friction.ProtoReflect.Descriptor instead.
func (*Friction) Descriptor() ([]byte, []int) {
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP(), []int{0}
}

func (x *Friction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Friction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Friction) GetCategory() FrictionCategory {
	if x != nil {
		return x.Category
	}
	return FrictionCategory_FRICTION_CATEGORY_UNSPECIFIED
}

func (x *Friction) GetStatus() FrictionStatus {
	if x != nil {
		return x.Status
	}
	return FrictionStatus_FRICTION_STATUS_UNSPECIFIED
}

func (x *Friction) GetSprint() string {
	if x != nil {
		return x.Sprint
	}
	return ""
}

func (x *Friction) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// LogFrictionRequest is the request for
// [FrictionService.LogFriction].
type LogFrictionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Description of the friction.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Optional. Category. Defaults to UNSPECIFIED.
	Category FrictionCategory `protobuf:"varint,2,opt,name=category,proto3,enum=collaboration.friction.v1alpha1.FrictionCategory" json:"category,omitempty"`
	// Optional. Sprint name (e.g. "sprints/3").
	Sprint        string `protobuf:"bytes,3,opt,name=sprint,proto3" json:"sprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFrictionRequest) Reset() {
	*x = LogFrictionRequest{}
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFrictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFrictionRequest) ProtoMessage() {}

func (x *LogFrictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFrictionRequest.ProtoReflect.Descriptor instead.
func (*LogFrictionRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP(), []int{1}
}

func (x *LogFrictionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LogFrictionRequest) GetCategory() FrictionCategory {
	if x != nil {
		return x.Category
	}
	return FrictionCategory_FRICTION_CATEGORY_UNSPECIFIED
}

func (x *LogFrictionRequest) GetSprint() string {
	if x != nil {
		return x.Sprint
	}
	return ""
}

// LogFrictionResponse is the response for
// [FrictionService.LogFriction].
type LogFrictionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The logged friction point.
	Friction      *Friction `protobuf:"bytes,1,opt,name=friction,proto3" json:"friction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFrictionResponse) Reset() {
	*x = LogFrictionResponse{}
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFrictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFrictionResponse) ProtoMessage() {}

func (x *LogFrictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFrictionResponse.ProtoReflect.Descriptor instead.
func (*LogFrictionResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP(), []int{2}
}

func (x *LogFrictionResponse) GetFriction() *Friction {
	if x != nil {
		return x.Friction
	}
	return nil
}

// ListFrictionRequest is the request for
// [FrictionService.ListFriction].
type ListFrictionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Filter by status.
	Status FrictionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=collaboration.friction.v1alpha1.FrictionStatus" json:"status,omitempty"`
	// Optional. Filter by sprint.
	Sprint string `protobuf:"bytes,2,opt,name=sprint,proto3" json:"sprint,omitempty"`
	// Optional. Page size. Default 50, max 100.
	PageSize int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Page token.
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFrictionRequest) Reset() {
	*x = ListFrictionRequest{}
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFrictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFrictionRequest) ProtoMessage() {}

func (x *ListFrictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFrictionRequest.ProtoReflect.Descriptor instead.
func (*ListFrictionRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP(), []int{3}
}

func (x *ListFrictionRequest) GetStatus() FrictionStatus {
	if x != nil {
		return x.Status
	}
	return FrictionStatus_FRICTION_STATUS_UNSPECIFIED
}

func (x *ListFrictionRequest) GetSprint() string {
	if x != nil {
		return x.Sprint
	}
	return ""
}

func (x *ListFrictionRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFrictionRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListFrictionResponse is the response for
// [FrictionService.ListFriction].
type ListFrictionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Friction points.
	Items []*Friction `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Next page token.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// Total count.
	TotalSize     int32 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFrictionResponse) Reset() {
	*x = ListFrictionResponse{}
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFrictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFrictionResponse) ProtoMessage() {}

func (x *ListFrictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFrictionResponse.ProtoReflect.Descriptor instead.
func (*ListFrictionResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP(), []int{4}
}

func (x *ListFrictionResponse) GetItems() []*Friction {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFrictionResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListFrictionResponse) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

// UpdateFrictionRequest is the request for
// [FrictionService.UpdateFriction].
type UpdateFrictionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Resource name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional. Updated description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Optional. Updated status.
	Status        FrictionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=collaboration.friction.v1alpha1.FrictionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFrictionRequest) Reset() {
	*x = UpdateFrictionRequest{}
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFrictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFrictionRequest) ProtoMessage() {}

func (x *UpdateFrictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFrictionRequest.ProtoReflect.Descriptor instead.
func (*UpdateFrictionRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFrictionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFrictionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateFrictionRequest) GetStatus() FrictionStatus {
	if x != nil {
		return x.Status
	}
	return FrictionStatus_FRICTION_STATUS_UNSPECIFIED
}

// UpdateFrictionResponse is the response for
// [FrictionService.UpdateFriction].
type UpdateFrictionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated friction point.
	Friction      *Friction `protobuf:"bytes,1,opt,name=friction,proto3" json:"friction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFrictionResponse) Reset() {
	*x = UpdateFrictionResponse{}
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFrictionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFrictionResponse) ProtoMessage() {}

func (x *UpdateFrictionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFrictionResponse.ProtoReflect.Descriptor instead.
func (*UpdateFrictionResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateFrictionResponse) GetFriction() *Friction {
	if x != nil {
		return x.Friction
	}
	return nil
}

// SprintSummaryRequest is the request for
// [FrictionService.SprintSummary].
type SprintSummaryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Sprint name (e.g. "sprints/3").
	Sprint        string `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SprintSummaryRequest) Reset() {
	*x = SprintSummaryRequest{}
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SprintSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SprintSummaryRequest) ProtoMessage() {}

func (x *SprintSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SprintSummaryRequest.ProtoReflect.Descriptor instead.
func (*SprintSummaryRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP(), []int{7}
}

func (x *SprintSummaryRequest) GetSprint() string {
	if x != nil {
		return x.Sprint
	}
	return ""
}

// SprintSummaryResponse is the response for
// [FrictionService.SprintSummary].
type SprintSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sprint name.
	Sprint string `protobuf:"bytes,1,opt,name=sprint,proto3" json:"sprint,omitempty"`
	// Total friction points logged.
	TotalCount int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Resolved during sprint.
	ResolvedCount int32 `protobuf:"varint,3,opt,name=resolved_count,json=resolvedCount,proto3" json:"resolved_count,omitempty"`
	// Breakdown by category.
	ByCategory map[string]int32 `protobuf:"bytes,4,rep,name=by_category,json=byCategory,proto3" json:"by_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Top unresolved friction points.
	TopUnresolved []*Friction `protobuf:"bytes,5,rep,name=top_unresolved,json=topUnresolved,proto3" json:"top_unresolved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SprintSummaryResponse) Reset() {
	*x = SprintSummaryResponse{}
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SprintSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SprintSummaryResponse) ProtoMessage() {}

func (x *SprintSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_friction_v1alpha1_friction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SprintSummaryResponse.ProtoReflect.Descriptor instead.
func (*SprintSummaryResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP(), []int{8}
}

func (x *SprintSummaryResponse) GetSprint() string {
	if x != nil {
		return x.Sprint
	}
	return ""
}

func (x *SprintSummaryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *SprintSummaryResponse) GetResolvedCount() int32 {
	if x != nil {
		return x.ResolvedCount
	}
	return 0
}

func (x *SprintSummaryResponse) GetByCategory() map[string]int32 {
	if x != nil {
		return x.ByCategory
	}
	return nil
}

func (x *SprintSummaryResponse) GetTopUnresolved() []*Friction {
	if x != nil {
		return x.TopUnresolved
	}
	return nil
}

var File_collaboration_friction_v1alpha1_friction_proto protoreflect.FileDescriptor

const file_collaboration_friction_v1alpha1_friction_proto_rawDesc = "" +
	"\n" +
	".collaboration/friction/v1alpha1/friction.proto\x12\x1fcollaboration.friction.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x02\n" +
	"\bFriction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12M\n" +
	"\bcategory\x18\x03 \x01(\x0e21.collaboration.friction.v1alpha1.FrictionCategoryR\bcategory\x12G\n" +
	"\x06status\x18\x04 \x01(\x0e2/.collaboration.friction.v1alpha1.FrictionStatusR\x06status\x12\x16\n" +
	"\x06sprint\x18\x05 \x01(\tR\x06sprint\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\x9d\x01\n" +
	"\x12LogFrictionRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12M\n" +
	"\bcategory\x18\x02 \x01(\x0e21.collaboration.friction.v1alpha1.FrictionCategoryR\bcategory\x12\x16\n" +
	"\x06sprint\x18\x03 \x01(\tR\x06sprint\"\\\n" +
	"\x13LogFrictionResponse\x12E\n" +
	"\bfriction\x18\x01 \x01(\v2).collaboration.friction.v1alpha1.FrictionR\bfriction\"\xb2\x01\n" +
	"\x13ListFrictionRequest\x12G\n" +
	"\x06status\x18\x01 \x01(\x0e2/.collaboration.friction.v1alpha1.FrictionStatusR\x06status\x12\x16\n" +
	"\x06sprint\x18\x02 \x01(\tR\x06sprint\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x9e\x01\n" +
	"\x14ListFrictionResponse\x12?\n" +
	"\x05items\x18\x01 \x03(\v2).collaboration.friction.v1alpha1.FrictionR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x05R\ttotalSize\"\x96\x01\n" +
	"\x15UpdateFrictionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12G\n" +
	"\x06status\x18\x03 \x01(\x0e2/.collaboration.friction.v1alpha1.FrictionStatusR\x06status\"_\n" +
	"\x16UpdateFrictionResponse\x12E\n" +
	"\bfriction\x18\x01 \x01(\v2).collaboration.friction.v1alpha1.FrictionR\bfriction\".\n" +
	"\x14SprintSummaryRequest\x12\x16\n" +
	"\x06sprint\x18\x01 \x01(\tR\x06sprint\"\xf1\x02\n" +
	"\x15SprintSummaryResponse\x12\x16\n" +
	"\x06sprint\x18\x01 \x01(\tR\x06sprint\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12%\n" +
	"\x0eresolved_count\x18\x03 \x01(\x05R\rresolvedCount\x12g\n" +
	"\vby_category\x18\x04 \x03(\v2F.collaboration.friction.v1alpha1.SprintSummaryResponse.ByCategoryEntryR\n" +
	"byCategory\x12P\n" +
	"\x0etop_unresolved\x18\x05 \x03(\v2).collaboration.friction.v1alpha1.FrictionR\rtopUnresolved\x1a=\n" +
	"\x0fByCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*\x8a\x01\n" +
	"\x0eFrictionStatus\x12\x1f\n" +
	"\x1bFRICTION_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FRICTION_STATUS_NEW\x10\x01\x12 \n" +
	"\x1cFRICTION_STATUS_ACKNOWLEDGED\x10\x02\x12\x1c\n" +
	"\x18FRICTION_STATUS_RESOLVED\x10\x03*\xb4\x01\n" +
	"\x10FrictionCategory\x12!\n" +
	"\x1dFRICTION_CATEGORY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FRICTION_CATEGORY_TOOLING\x10\x01\x12\x1d\n" +
	"\x19FRICTION_CATEGORY_PROCESS\x10\x02\x12#\n" +
	"\x1fFRICTION_CATEGORY_COMMUNICATION\x10\x03\x12\x1a\n" +
	"\x16FRICTION_CATEGORY_DEBT\x10\x042\x8c\x04\n" +
	"\x0fFrictionService\x12x\n" +
	"\vLogFriction\x123.collaboration.friction.v1alpha1.LogFrictionRequest\x1a4.collaboration.friction.v1alpha1.LogFrictionResponse\x12{\n" +
	"\fListFriction\x124.collaboration.friction.v1alpha1.ListFrictionRequest\x1a5.collaboration.friction.v1alpha1.ListFrictionResponse\x12\x81\x01\n" +
	"\x0eUpdateFriction\x126.collaboration.friction.v1alpha1.UpdateFrictionRequest\x1a7.collaboration.friction.v1alpha1.UpdateFrictionResponse\x12~\n" +
	"\rSprintSummary\x125.collaboration.friction.v1alpha1.SprintSummaryRequest\x1a6.collaboration.friction.v1alpha1.SprintSummaryResponseBaZ_github.com/duizendstra/alexandria/go/contracts/collaboration/friction/v1alpha1;frictionv1alpha1b\x06proto3"

var (
	file_collaboration_friction_v1alpha1_friction_proto_rawDescOnce sync.Once
	file_collaboration_friction_v1alpha1_friction_proto_rawDescData []byte
)

func file_collaboration_friction_v1alpha1_friction_proto_rawDescGZIP() []byte {
	file_collaboration_friction_v1alpha1_friction_proto_rawDescOnce.Do(func() {
		file_collaboration_friction_v1alpha1_friction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collaboration_friction_v1alpha1_friction_proto_rawDesc), len(file_collaboration_friction_v1alpha1_friction_proto_rawDesc)))
	})
	return file_collaboration_friction_v1alpha1_friction_proto_rawDescData
}

var file_collaboration_friction_v1alpha1_friction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_collaboration_friction_v1alpha1_friction_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_collaboration_friction_v1alpha1_friction_proto_goTypes = []any{
	(FrictionStatus)(0),            // 0: collaboration.friction.v1alpha1.FrictionStatus
	(FrictionCategory)(0),          // 1: collaboration.friction.v1alpha1.FrictionCategory
	(*Friction)(nil),               // 2: collaboration.friction.v1alpha1.Friction
	(*LogFrictionRequest)(nil),     // 3: collaboration.friction.v1alpha1.LogFrictionRequest
	(*LogFrictionResponse)(nil),    // 4: collaboration.friction.v1alpha1.LogFrictionResponse
	(*ListFrictionRequest)(nil),    // 5: collaboration.friction.v1alpha1.ListFrictionRequest
	(*ListFrictionResponse)(nil),   // 6: collaboration.friction.v1alpha1.ListFrictionResponse
	(*UpdateFrictionRequest)(nil),  // 7: collaboration.friction.v1alpha1.UpdateFrictionRequest
	(*UpdateFrictionResponse)(nil), // 8: collaboration.friction.v1alpha1.UpdateFrictionResponse
	(*SprintSummaryRequest)(nil),   // 9: collaboration.friction.v1alpha1.SprintSummaryRequest
	(*SprintSummaryResponse)(nil),  // 10: collaboration.friction.v1alpha1.SprintSummaryResponse
	nil,                            // 11: collaboration.friction.v1alpha1.SprintSummaryResponse.ByCategoryEntry
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_collaboration_friction_v1alpha1_friction_proto_depIdxs = []int32{
	1,  // 0: collaboration.friction.v1alpha1.Friction.category:type_name -> collaboration.friction.v1alpha1.FrictionCategory
	0,  // 1: collaboration.friction.v1alpha1.Friction.status:type_name -> collaboration.friction.v1alpha1.FrictionStatus
	12, // 2: collaboration.friction.v1alpha1.Friction.create_time:type_name -> google.protobuf.Timestamp
	1,  // 3: collaboration.friction.v1alpha1.LogFrictionRequest.category:type_name -> collaboration.friction.v1alpha1.FrictionCategory
	2,  // 4: collaboration.friction.v1alpha1.LogFrictionResponse.friction:type_name -> collaboration.friction.v1alpha1.Friction
	0,  // 5: collaboration.friction.v1alpha1.ListFrictionRequest.status:type_name -> collaboration.friction.v1alpha1.FrictionStatus
	2,  // 6: collaboration.friction.v1alpha1.ListFrictionResponse.items:type_name -> collaboration.friction.v1alpha1.Friction
	0,  // 7: collaboration.friction.v1alpha1.UpdateFrictionRequest.status:type_name -> collaboration.friction.v1alpha1.FrictionStatus
	2,  // 8: collaboration.friction.v1alpha1.UpdateFrictionResponse.friction:type_name -> collaboration.friction.v1alpha1.Friction
	11, // 9: collaboration.friction.v1alpha1.SprintSummaryResponse.by_category:type_name -> collaboration.friction.v1alpha1.SprintSummaryResponse.ByCategoryEntry
	2,  // 10: collaboration.friction.v1alpha1.SprintSummaryResponse.top_unresolved:type_name -> collaboration.friction.v1alpha1.Friction
	3,  // 11: collaboration.friction.v1alpha1.FrictionService.LogFriction:input_type -> collaboration.friction.v1alpha1.LogFrictionRequest
	5,  // 12: collaboration.friction.v1alpha1.FrictionService.ListFriction:input_type -> collaboration.friction.v1alpha1.ListFrictionRequest
	7,  // 13: collaboration.friction.v1alpha1.FrictionService.UpdateFriction:input_type -> collaboration.friction.v1alpha1.UpdateFrictionRequest
	9,  // 14: collaboration.friction.v1alpha1.FrictionService.SprintSummary:input_type -> collaboration.friction.v1alpha1.SprintSummaryRequest
	4,  // 15: collaboration.friction.v1alpha1.FrictionService.LogFriction:output_type -> collaboration.friction.v1alpha1.LogFrictionResponse
	6,  // 16: collaboration.friction.v1alpha1.FrictionService.ListFriction:output_type -> collaboration.friction.v1alpha1.ListFrictionResponse
	8,  // 17: collaboration.friction.v1alpha1.FrictionService.UpdateFriction:output_type -> collaboration.friction.v1alpha1.UpdateFrictionResponse
	10, // 18: collaboration.friction.v1alpha1.FrictionService.SprintSummary:output_type -> collaboration.friction.v1alpha1.SprintSummaryResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_collaboration_friction_v1alpha1_friction_proto_init() }
func file_collaboration_friction_v1alpha1_friction_proto_init() {
	if File_collaboration_friction_v1alpha1_friction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collaboration_friction_v1alpha1_friction_proto_rawDesc), len(file_collaboration_friction_v1alpha1_friction_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collaboration_friction_v1alpha1_friction_proto_goTypes,
		DependencyIndexes: file_collaboration_friction_v1alpha1_friction_proto_depIdxs,
		EnumInfos:         file_collaboration_friction_v1alpha1_friction_proto_enumTypes,
		MessageInfos:      file_collaboration_friction_v1alpha1_friction_proto_msgTypes,
	}.Build()
	File_collaboration_friction_v1alpha1_friction_proto = out.File
	file_collaboration_friction_v1alpha1_friction_proto_goTypes = nil
	file_collaboration_friction_v1alpha1_friction_proto_depIdxs = nil
}
