// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: registry/repos/v1/repos.proto

package reposv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/duizendstra/alexandria/go/contracts/registry/repos/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RepoServiceName is the fully-qualified name of the RepoService service.
	RepoServiceName = "registry.repos.v1.RepoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RepoServiceListRepositoriesProcedure is the fully-qualified name of the RepoService's
	// ListRepositories RPC.
	RepoServiceListRepositoriesProcedure = "/registry.repos.v1.RepoService/ListRepositories"
)

// RepoServiceClient is a client for the registry.repos.v1.RepoService service.
type RepoServiceClient interface {
	// ListRepositories returns all configured repositories (AIP-132).
	ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error)
}

// NewRepoServiceClient constructs a client for the registry.repos.v1.RepoService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRepoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RepoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	repoServiceMethods := v1.File_registry_repos_v1_repos_proto.Services().ByName("RepoService").Methods()
	return &repoServiceClient{
		listRepositories: connect.NewClient[v1.ListRepositoriesRequest, v1.ListRepositoriesResponse](
			httpClient,
			baseURL+RepoServiceListRepositoriesProcedure,
			connect.WithSchema(repoServiceMethods.ByName("ListRepositories")),
			connect.WithClientOptions(opts...),
		),
	}
}

// repoServiceClient implements RepoServiceClient.
type repoServiceClient struct {
	listRepositories *connect.Client[v1.ListRepositoriesRequest, v1.ListRepositoriesResponse]
}

// ListRepositories calls registry.repos.v1.RepoService.ListRepositories.
func (c *repoServiceClient) ListRepositories(ctx context.Context, req *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error) {
	return c.listRepositories.CallUnary(ctx, req)
}

// RepoServiceHandler is an implementation of the registry.repos.v1.RepoService service.
type RepoServiceHandler interface {
	// ListRepositories returns all configured repositories (AIP-132).
	ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error)
}

// NewRepoServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRepoServiceHandler(svc RepoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	repoServiceMethods := v1.File_registry_repos_v1_repos_proto.Services().ByName("RepoService").Methods()
	repoServiceListRepositoriesHandler := connect.NewUnaryHandler(
		RepoServiceListRepositoriesProcedure,
		svc.ListRepositories,
		connect.WithSchema(repoServiceMethods.ByName("ListRepositories")),
		connect.WithHandlerOptions(opts...),
	)
	return "/registry.repos.v1.RepoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RepoServiceListRepositoriesProcedure:
			repoServiceListRepositoriesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRepoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRepoServiceHandler struct{}

func (UnimplementedRepoServiceHandler) ListRepositories(context.Context, *connect.Request[v1.ListRepositoriesRequest]) (*connect.Response[v1.ListRepositoriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("registry.repos.v1.RepoService.ListRepositories is not implemented"))
}
