// Copyright 2026 Duizendstra. All rights reserved.
//
// Workspace governance — validates workspace structure, conventions,
// and dependency hygiene.
//
// Domain:  Workspace
// Concern: Is the workspace well-formed?

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workspace/governance/v1alpha1/governance.proto

package governancev1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadmeStatus reports DDD compliance for a single README.
type ReadmeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Pass          bool                   `protobuf:"varint,2,opt,name=pass,proto3" json:"pass,omitempty"`
	Issues        []string               `protobuf:"bytes,3,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadmeStatus) Reset() {
	*x = ReadmeStatus{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadmeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadmeStatus) ProtoMessage() {}

func (x *ReadmeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadmeStatus.ProtoReflect.Descriptor instead.
func (*ReadmeStatus) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{0}
}

func (x *ReadmeStatus) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadmeStatus) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

func (x *ReadmeStatus) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

type ScanReadmesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory to scan. Defaults to workspace alexandria/.
	Directory     string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanReadmesRequest) Reset() {
	*x = ScanReadmesRequest{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanReadmesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanReadmesRequest) ProtoMessage() {}

func (x *ScanReadmesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanReadmesRequest.ProtoReflect.Descriptor instead.
func (*ScanReadmesRequest) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{1}
}

func (x *ScanReadmesRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type ScanReadmesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ReadmeStatus        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	PassCount     int32                  `protobuf:"varint,2,opt,name=pass_count,json=passCount,proto3" json:"pass_count,omitempty"`
	FailCount     int32                  `protobuf:"varint,3,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanReadmesResponse) Reset() {
	*x = ScanReadmesResponse{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanReadmesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanReadmesResponse) ProtoMessage() {}

func (x *ScanReadmesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanReadmesResponse.ProtoReflect.Descriptor instead.
func (*ScanReadmesResponse) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{2}
}

func (x *ScanReadmesResponse) GetResults() []*ReadmeStatus {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ScanReadmesResponse) GetPassCount() int32 {
	if x != nil {
		return x.PassCount
	}
	return 0
}

func (x *ScanReadmesResponse) GetFailCount() int32 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

// ScratchStatus reports the state of one scratch folder.
type ScratchStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	Gitignored    bool                   `protobuf:"varint,3,opt,name=gitignored,proto3" json:"gitignored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScratchStatus) Reset() {
	*x = ScratchStatus{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScratchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScratchStatus) ProtoMessage() {}

func (x *ScratchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScratchStatus.ProtoReflect.Descriptor instead.
func (*ScratchStatus) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{3}
}

func (x *ScratchStatus) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ScratchStatus) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ScratchStatus) GetGitignored() bool {
	if x != nil {
		return x.Gitignored
	}
	return false
}

type ScanScratchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanScratchRequest) Reset() {
	*x = ScanScratchRequest{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanScratchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanScratchRequest) ProtoMessage() {}

func (x *ScanScratchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanScratchRequest.ProtoReflect.Descriptor instead.
func (*ScanScratchRequest) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{4}
}

type ScanScratchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScratchStatus       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanScratchResponse) Reset() {
	*x = ScanScratchResponse{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanScratchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanScratchResponse) ProtoMessage() {}

func (x *ScanScratchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanScratchResponse.ProtoReflect.Descriptor instead.
func (*ScanScratchResponse) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{5}
}

func (x *ScanScratchResponse) GetResults() []*ScratchStatus {
	if x != nil {
		return x.Results
	}
	return nil
}

type EnsureScratchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureScratchRequest) Reset() {
	*x = EnsureScratchRequest{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureScratchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureScratchRequest) ProtoMessage() {}

func (x *EnsureScratchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureScratchRequest.ProtoReflect.Descriptor instead.
func (*EnsureScratchRequest) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{6}
}

type EnsureScratchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fixed         int32                  `protobuf:"varint,1,opt,name=fixed,proto3" json:"fixed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureScratchResponse) Reset() {
	*x = EnsureScratchResponse{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureScratchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureScratchResponse) ProtoMessage() {}

func (x *EnsureScratchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureScratchResponse.ProtoReflect.Descriptor instead.
func (*EnsureScratchResponse) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{7}
}

func (x *EnsureScratchResponse) GetFixed() int32 {
	if x != nil {
		return x.Fixed
	}
	return 0
}

// PurityStatus reports cloud dependency analysis for one package.
type PurityStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Pure          bool                   `protobuf:"varint,2,opt,name=pure,proto3" json:"pure,omitempty"`
	CloudDeps     []string               `protobuf:"bytes,3,rep,name=cloud_deps,json=cloudDeps,proto3" json:"cloud_deps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurityStatus) Reset() {
	*x = PurityStatus{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurityStatus) ProtoMessage() {}

func (x *PurityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurityStatus.ProtoReflect.Descriptor instead.
func (*PurityStatus) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{8}
}

func (x *PurityStatus) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *PurityStatus) GetPure() bool {
	if x != nil {
		return x.Pure
	}
	return false
}

func (x *PurityStatus) GetCloudDeps() []string {
	if x != nil {
		return x.CloudDeps
	}
	return nil
}

type ScanPurityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Directory to scan. Defaults to workspace alexandria/go/.
	Directory     string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanPurityRequest) Reset() {
	*x = ScanPurityRequest{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanPurityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanPurityRequest) ProtoMessage() {}

func (x *ScanPurityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanPurityRequest.ProtoReflect.Descriptor instead.
func (*ScanPurityRequest) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{9}
}

func (x *ScanPurityRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

type ScanPurityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PurityStatus        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanPurityResponse) Reset() {
	*x = ScanPurityResponse{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanPurityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanPurityResponse) ProtoMessage() {}

func (x *ScanPurityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanPurityResponse.ProtoReflect.Descriptor instead.
func (*ScanPurityResponse) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{10}
}

func (x *ScanPurityResponse) GetResults() []*PurityStatus {
	if x != nil {
		return x.Results
	}
	return nil
}

type FixGoVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetVersion string                 `protobuf:"bytes,1,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixGoVersionsRequest) Reset() {
	*x = FixGoVersionsRequest{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixGoVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixGoVersionsRequest) ProtoMessage() {}

func (x *FixGoVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixGoVersionsRequest.ProtoReflect.Descriptor instead.
func (*FixGoVersionsRequest) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{11}
}

func (x *FixGoVersionsRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

type GoVersionFix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	OldVersion    string                 `protobuf:"bytes,2,opt,name=old_version,json=oldVersion,proto3" json:"old_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoVersionFix) Reset() {
	*x = GoVersionFix{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoVersionFix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoVersionFix) ProtoMessage() {}

func (x *GoVersionFix) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoVersionFix.ProtoReflect.Descriptor instead.
func (*GoVersionFix) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{12}
}

func (x *GoVersionFix) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GoVersionFix) GetOldVersion() string {
	if x != nil {
		return x.OldVersion
	}
	return ""
}

type FixGoVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*GoVersionFix        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixGoVersionsResponse) Reset() {
	*x = FixGoVersionsResponse{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixGoVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixGoVersionsResponse) ProtoMessage() {}

func (x *FixGoVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixGoVersionsResponse.ProtoReflect.Descriptor instead.
func (*FixGoVersionsResponse) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{13}
}

func (x *FixGoVersionsResponse) GetResults() []*GoVersionFix {
	if x != nil {
		return x.Results
	}
	return nil
}

type CleanGoSumsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module prefix to clean. Defaults to alexandria module prefix.
	ModulePrefix  string `protobuf:"bytes,1,opt,name=module_prefix,json=modulePrefix,proto3" json:"module_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanGoSumsRequest) Reset() {
	*x = CleanGoSumsRequest{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanGoSumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanGoSumsRequest) ProtoMessage() {}

func (x *CleanGoSumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanGoSumsRequest.ProtoReflect.Descriptor instead.
func (*CleanGoSumsRequest) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{14}
}

func (x *CleanGoSumsRequest) GetModulePrefix() string {
	if x != nil {
		return x.ModulePrefix
	}
	return ""
}

type GoSumClean struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Removed       int32                  `protobuf:"varint,2,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoSumClean) Reset() {
	*x = GoSumClean{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoSumClean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoSumClean) ProtoMessage() {}

func (x *GoSumClean) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoSumClean.ProtoReflect.Descriptor instead.
func (*GoSumClean) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{15}
}

func (x *GoSumClean) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GoSumClean) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

type CleanGoSumsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*GoSumClean          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanGoSumsResponse) Reset() {
	*x = CleanGoSumsResponse{}
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanGoSumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanGoSumsResponse) ProtoMessage() {}

func (x *CleanGoSumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_governance_v1alpha1_governance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanGoSumsResponse.ProtoReflect.Descriptor instead.
func (*CleanGoSumsResponse) Descriptor() ([]byte, []int) {
	return file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP(), []int{16}
}

func (x *CleanGoSumsResponse) GetResults() []*GoSumClean {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_workspace_governance_v1alpha1_governance_proto protoreflect.FileDescriptor

const file_workspace_governance_v1alpha1_governance_proto_rawDesc = "" +
	"\n" +
	".workspace/governance/v1alpha1/governance.proto\x12\x1dworkspace.governance.v1alpha1\"N\n" +
	"\fReadmeStatus\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04pass\x18\x02 \x01(\bR\x04pass\x12\x16\n" +
	"\x06issues\x18\x03 \x03(\tR\x06issues\"2\n" +
	"\x12ScanReadmesRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\"\x9a\x01\n" +
	"\x13ScanReadmesResponse\x12E\n" +
	"\aresults\x18\x01 \x03(\v2+.workspace.governance.v1alpha1.ReadmeStatusR\aresults\x12\x1d\n" +
	"\n" +
	"pass_count\x18\x02 \x01(\x05R\tpassCount\x12\x1d\n" +
	"\n" +
	"fail_count\x18\x03 \x01(\x05R\tfailCount\"]\n" +
	"\rScratchStatus\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12\x1e\n" +
	"\n" +
	"gitignored\x18\x03 \x01(\bR\n" +
	"gitignored\"\x14\n" +
	"\x12ScanScratchRequest\"]\n" +
	"\x13ScanScratchResponse\x12F\n" +
	"\aresults\x18\x01 \x03(\v2,.workspace.governance.v1alpha1.ScratchStatusR\aresults\"\x16\n" +
	"\x14EnsureScratchRequest\"-\n" +
	"\x15EnsureScratchResponse\x12\x14\n" +
	"\x05fixed\x18\x01 \x01(\x05R\x05fixed\"[\n" +
	"\fPurityStatus\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x12\n" +
	"\x04pure\x18\x02 \x01(\bR\x04pure\x12\x1d\n" +
	"\n" +
	"cloud_deps\x18\x03 \x03(\tR\tcloudDeps\"1\n" +
	"\x11ScanPurityRequest\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\"[\n" +
	"\x12ScanPurityResponse\x12E\n" +
	"\aresults\x18\x01 \x03(\v2+.workspace.governance.v1alpha1.PurityStatusR\aresults\"=\n" +
	"\x14FixGoVersionsRequest\x12%\n" +
	"\x0etarget_version\x18\x01 \x01(\tR\rtargetVersion\"C\n" +
	"\fGoVersionFix\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vold_version\x18\x02 \x01(\tR\n" +
	"oldVersion\"^\n" +
	"\x15FixGoVersionsResponse\x12E\n" +
	"\aresults\x18\x01 \x03(\v2+.workspace.governance.v1alpha1.GoVersionFixR\aresults\"9\n" +
	"\x12CleanGoSumsRequest\x12#\n" +
	"\rmodule_prefix\x18\x01 \x01(\tR\fmodulePrefix\":\n" +
	"\n" +
	"GoSumClean\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\aremoved\x18\x02 \x01(\x05R\aremoved\"Z\n" +
	"\x13CleanGoSumsResponse\x12C\n" +
	"\aresults\x18\x01 \x03(\v2).workspace.governance.v1alpha1.GoSumCleanR\aresults2\xe0\x05\n" +
	"\x11GovernanceService\x12t\n" +
	"\vScanReadmes\x121.workspace.governance.v1alpha1.ScanReadmesRequest\x1a2.workspace.governance.v1alpha1.ScanReadmesResponse\x12t\n" +
	"\vScanScratch\x121.workspace.governance.v1alpha1.ScanScratchRequest\x1a2.workspace.governance.v1alpha1.ScanScratchResponse\x12z\n" +
	"\rEnsureScratch\x123.workspace.governance.v1alpha1.EnsureScratchRequest\x1a4.workspace.governance.v1alpha1.EnsureScratchResponse\x12q\n" +
	"\n" +
	"ScanPurity\x120.workspace.governance.v1alpha1.ScanPurityRequest\x1a1.workspace.governance.v1alpha1.ScanPurityResponse\x12z\n" +
	"\rFixGoVersions\x123.workspace.governance.v1alpha1.FixGoVersionsRequest\x1a4.workspace.governance.v1alpha1.FixGoVersionsResponse\x12t\n" +
	"\vCleanGoSums\x121.workspace.governance.v1alpha1.CleanGoSumsRequest\x1a2.workspace.governance.v1alpha1.CleanGoSumsResponseBaZ_github.com/duizendstra/alexandria/go/contracts/workspace/governance/v1alpha1;governancev1alpha1b\x06proto3"

var (
	file_workspace_governance_v1alpha1_governance_proto_rawDescOnce sync.Once
	file_workspace_governance_v1alpha1_governance_proto_rawDescData []byte
)

func file_workspace_governance_v1alpha1_governance_proto_rawDescGZIP() []byte {
	file_workspace_governance_v1alpha1_governance_proto_rawDescOnce.Do(func() {
		file_workspace_governance_v1alpha1_governance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_governance_v1alpha1_governance_proto_rawDesc), len(file_workspace_governance_v1alpha1_governance_proto_rawDesc)))
	})
	return file_workspace_governance_v1alpha1_governance_proto_rawDescData
}

var file_workspace_governance_v1alpha1_governance_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_workspace_governance_v1alpha1_governance_proto_goTypes = []any{
	(*ReadmeStatus)(nil),          // 0: workspace.governance.v1alpha1.ReadmeStatus
	(*ScanReadmesRequest)(nil),    // 1: workspace.governance.v1alpha1.ScanReadmesRequest
	(*ScanReadmesResponse)(nil),   // 2: workspace.governance.v1alpha1.ScanReadmesResponse
	(*ScratchStatus)(nil),         // 3: workspace.governance.v1alpha1.ScratchStatus
	(*ScanScratchRequest)(nil),    // 4: workspace.governance.v1alpha1.ScanScratchRequest
	(*ScanScratchResponse)(nil),   // 5: workspace.governance.v1alpha1.ScanScratchResponse
	(*EnsureScratchRequest)(nil),  // 6: workspace.governance.v1alpha1.EnsureScratchRequest
	(*EnsureScratchResponse)(nil), // 7: workspace.governance.v1alpha1.EnsureScratchResponse
	(*PurityStatus)(nil),          // 8: workspace.governance.v1alpha1.PurityStatus
	(*ScanPurityRequest)(nil),     // 9: workspace.governance.v1alpha1.ScanPurityRequest
	(*ScanPurityResponse)(nil),    // 10: workspace.governance.v1alpha1.ScanPurityResponse
	(*FixGoVersionsRequest)(nil),  // 11: workspace.governance.v1alpha1.FixGoVersionsRequest
	(*GoVersionFix)(nil),          // 12: workspace.governance.v1alpha1.GoVersionFix
	(*FixGoVersionsResponse)(nil), // 13: workspace.governance.v1alpha1.FixGoVersionsResponse
	(*CleanGoSumsRequest)(nil),    // 14: workspace.governance.v1alpha1.CleanGoSumsRequest
	(*GoSumClean)(nil),            // 15: workspace.governance.v1alpha1.GoSumClean
	(*CleanGoSumsResponse)(nil),   // 16: workspace.governance.v1alpha1.CleanGoSumsResponse
}
var file_workspace_governance_v1alpha1_governance_proto_depIdxs = []int32{
	0,  // 0: workspace.governance.v1alpha1.ScanReadmesResponse.results:type_name -> workspace.governance.v1alpha1.ReadmeStatus
	3,  // 1: workspace.governance.v1alpha1.ScanScratchResponse.results:type_name -> workspace.governance.v1alpha1.ScratchStatus
	8,  // 2: workspace.governance.v1alpha1.ScanPurityResponse.results:type_name -> workspace.governance.v1alpha1.PurityStatus
	12, // 3: workspace.governance.v1alpha1.FixGoVersionsResponse.results:type_name -> workspace.governance.v1alpha1.GoVersionFix
	15, // 4: workspace.governance.v1alpha1.CleanGoSumsResponse.results:type_name -> workspace.governance.v1alpha1.GoSumClean
	1,  // 5: workspace.governance.v1alpha1.GovernanceService.ScanReadmes:input_type -> workspace.governance.v1alpha1.ScanReadmesRequest
	4,  // 6: workspace.governance.v1alpha1.GovernanceService.ScanScratch:input_type -> workspace.governance.v1alpha1.ScanScratchRequest
	6,  // 7: workspace.governance.v1alpha1.GovernanceService.EnsureScratch:input_type -> workspace.governance.v1alpha1.EnsureScratchRequest
	9,  // 8: workspace.governance.v1alpha1.GovernanceService.ScanPurity:input_type -> workspace.governance.v1alpha1.ScanPurityRequest
	11, // 9: workspace.governance.v1alpha1.GovernanceService.FixGoVersions:input_type -> workspace.governance.v1alpha1.FixGoVersionsRequest
	14, // 10: workspace.governance.v1alpha1.GovernanceService.CleanGoSums:input_type -> workspace.governance.v1alpha1.CleanGoSumsRequest
	2,  // 11: workspace.governance.v1alpha1.GovernanceService.ScanReadmes:output_type -> workspace.governance.v1alpha1.ScanReadmesResponse
	5,  // 12: workspace.governance.v1alpha1.GovernanceService.ScanScratch:output_type -> workspace.governance.v1alpha1.ScanScratchResponse
	7,  // 13: workspace.governance.v1alpha1.GovernanceService.EnsureScratch:output_type -> workspace.governance.v1alpha1.EnsureScratchResponse
	10, // 14: workspace.governance.v1alpha1.GovernanceService.ScanPurity:output_type -> workspace.governance.v1alpha1.ScanPurityResponse
	13, // 15: workspace.governance.v1alpha1.GovernanceService.FixGoVersions:output_type -> workspace.governance.v1alpha1.FixGoVersionsResponse
	16, // 16: workspace.governance.v1alpha1.GovernanceService.CleanGoSums:output_type -> workspace.governance.v1alpha1.CleanGoSumsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_workspace_governance_v1alpha1_governance_proto_init() }
func file_workspace_governance_v1alpha1_governance_proto_init() {
	if File_workspace_governance_v1alpha1_governance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_governance_v1alpha1_governance_proto_rawDesc), len(file_workspace_governance_v1alpha1_governance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_governance_v1alpha1_governance_proto_goTypes,
		DependencyIndexes: file_workspace_governance_v1alpha1_governance_proto_depIdxs,
		MessageInfos:      file_workspace_governance_v1alpha1_governance_proto_msgTypes,
	}.Build()
	File_workspace_governance_v1alpha1_governance_proto = out.File
	file_workspace_governance_v1alpha1_governance_proto_goTypes = nil
	file_workspace_governance_v1alpha1_governance_proto_depIdxs = nil
}
