// Copyright 2026 Duizendstra. All rights reserved.
//
// Git hook verification — API endpoints for pre-commit,
// commit-msg, and pre-push checks. Client hooks call these
// endpoints on the local Kratos API for fast feedback.
//
// Domain:  Development
// Concern: How do we verify code quality at commit time?

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: development/hooks/v1/hooks.proto

package hooksv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PreCommitRequest provides context for the pre-commit hook.
type PreCommitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path to the repository root.
	RepoPath string `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	// Staged files (relative to repo root).
	StagedFiles   []string `protobuf:"bytes,2,rep,name=staged_files,json=stagedFiles,proto3" json:"staged_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCommitRequest) Reset() {
	*x = PreCommitRequest{}
	mi := &file_development_hooks_v1_hooks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCommitRequest) ProtoMessage() {}

func (x *PreCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_development_hooks_v1_hooks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCommitRequest.ProtoReflect.Descriptor instead.
func (*PreCommitRequest) Descriptor() ([]byte, []int) {
	return file_development_hooks_v1_hooks_proto_rawDescGZIP(), []int{0}
}

func (x *PreCommitRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *PreCommitRequest) GetStagedFiles() []string {
	if x != nil {
		return x.StagedFiles
	}
	return nil
}

// CommitMsgRequest provides the commit message for validation.
type CommitMsgRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path to the repository root.
	RepoPath string `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	// The commit message to validate.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMsgRequest) Reset() {
	*x = CommitMsgRequest{}
	mi := &file_development_hooks_v1_hooks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMsgRequest) ProtoMessage() {}

func (x *CommitMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_development_hooks_v1_hooks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMsgRequest.ProtoReflect.Descriptor instead.
func (*CommitMsgRequest) Descriptor() ([]byte, []int) {
	return file_development_hooks_v1_hooks_proto_rawDescGZIP(), []int{1}
}

func (x *CommitMsgRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *CommitMsgRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PrePushRequest provides context for the pre-push hook.
type PrePushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path to the repository root.
	RepoPath string `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	// Remote name (e.g. "origin").
	Remote string `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"`
	// Ref being pushed (e.g. "refs/heads/main").
	Ref           string `protobuf:"bytes,3,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrePushRequest) Reset() {
	*x = PrePushRequest{}
	mi := &file_development_hooks_v1_hooks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrePushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrePushRequest) ProtoMessage() {}

func (x *PrePushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_development_hooks_v1_hooks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrePushRequest.ProtoReflect.Descriptor instead.
func (*PrePushRequest) Descriptor() ([]byte, []int) {
	return file_development_hooks_v1_hooks_proto_rawDescGZIP(), []int{2}
}

func (x *PrePushRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *PrePushRequest) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *PrePushRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// HookResponse is the result of any hook check.
type HookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether all checks passed.
	Pass bool `protobuf:"varint,1,opt,name=pass,proto3" json:"pass,omitempty"`
	// Individual check results.
	Checks        []*CheckResult `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponse) Reset() {
	*x = HookResponse{}
	mi := &file_development_hooks_v1_hooks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponse) ProtoMessage() {}

func (x *HookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_development_hooks_v1_hooks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponse.ProtoReflect.Descriptor instead.
func (*HookResponse) Descriptor() ([]byte, []int) {
	return file_development_hooks_v1_hooks_proto_rawDescGZIP(), []int{3}
}

func (x *HookResponse) GetPass() bool {
	if x != nil {
		return x.Pass
	}
	return false
}

func (x *HookResponse) GetChecks() []*CheckResult {
	if x != nil {
		return x.Checks
	}
	return nil
}

// CheckResult is the outcome of a single check within a hook.
type CheckResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Check name (e.g. "lint", "test", "submodule", "format").
	Check string `protobuf:"bytes,1,opt,name=check,proto3" json:"check,omitempty"`
	// true if this check passed.
	Passed bool `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	// Human-readable message (error details if failed).
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// File reference if applicable (e.g. "handler.go:42").
	File          string `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_development_hooks_v1_hooks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_development_hooks_v1_hooks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_development_hooks_v1_hooks_proto_rawDescGZIP(), []int{4}
}

func (x *CheckResult) GetCheck() string {
	if x != nil {
		return x.Check
	}
	return ""
}

func (x *CheckResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *CheckResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckResult) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

var File_development_hooks_v1_hooks_proto protoreflect.FileDescriptor

const file_development_hooks_v1_hooks_proto_rawDesc = "" +
	"\n" +
	" development/hooks/v1/hooks.proto\x12\x14development.hooks.v1\"R\n" +
	"\x10PreCommitRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12!\n" +
	"\fstaged_files\x18\x02 \x03(\tR\vstagedFiles\"I\n" +
	"\x10CommitMsgRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\x0ePrePushRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x16\n" +
	"\x06remote\x18\x02 \x01(\tR\x06remote\x12\x10\n" +
	"\x03ref\x18\x03 \x01(\tR\x03ref\"]\n" +
	"\fHookResponse\x12\x12\n" +
	"\x04pass\x18\x01 \x01(\bR\x04pass\x129\n" +
	"\x06checks\x18\x02 \x03(\v2!.development.hooks.v1.CheckResultR\x06checks\"i\n" +
	"\vCheckResult\x12\x14\n" +
	"\x05check\x18\x01 \x01(\tR\x05check\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04file\x18\x04 \x01(\tR\x04file2\x95\x02\n" +
	"\fHooksService\x12W\n" +
	"\tPreCommit\x12&.development.hooks.v1.PreCommitRequest\x1a\".development.hooks.v1.HookResponse\x12W\n" +
	"\tCommitMsg\x12&.development.hooks.v1.CommitMsgRequest\x1a\".development.hooks.v1.HookResponse\x12S\n" +
	"\aPrePush\x12$.development.hooks.v1.PrePushRequest\x1a\".development.hooks.v1.HookResponseBMZKgithub.com/duizendstra/alexandria/go/contracts/development/hooks/v1;hooksv1b\x06proto3"

var (
	file_development_hooks_v1_hooks_proto_rawDescOnce sync.Once
	file_development_hooks_v1_hooks_proto_rawDescData []byte
)

func file_development_hooks_v1_hooks_proto_rawDescGZIP() []byte {
	file_development_hooks_v1_hooks_proto_rawDescOnce.Do(func() {
		file_development_hooks_v1_hooks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_development_hooks_v1_hooks_proto_rawDesc), len(file_development_hooks_v1_hooks_proto_rawDesc)))
	})
	return file_development_hooks_v1_hooks_proto_rawDescData
}

var file_development_hooks_v1_hooks_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_development_hooks_v1_hooks_proto_goTypes = []any{
	(*PreCommitRequest)(nil), // 0: development.hooks.v1.PreCommitRequest
	(*CommitMsgRequest)(nil), // 1: development.hooks.v1.CommitMsgRequest
	(*PrePushRequest)(nil),   // 2: development.hooks.v1.PrePushRequest
	(*HookResponse)(nil),     // 3: development.hooks.v1.HookResponse
	(*CheckResult)(nil),      // 4: development.hooks.v1.CheckResult
}
var file_development_hooks_v1_hooks_proto_depIdxs = []int32{
	4, // 0: development.hooks.v1.HookResponse.checks:type_name -> development.hooks.v1.CheckResult
	0, // 1: development.hooks.v1.HooksService.PreCommit:input_type -> development.hooks.v1.PreCommitRequest
	1, // 2: development.hooks.v1.HooksService.CommitMsg:input_type -> development.hooks.v1.CommitMsgRequest
	2, // 3: development.hooks.v1.HooksService.PrePush:input_type -> development.hooks.v1.PrePushRequest
	3, // 4: development.hooks.v1.HooksService.PreCommit:output_type -> development.hooks.v1.HookResponse
	3, // 5: development.hooks.v1.HooksService.CommitMsg:output_type -> development.hooks.v1.HookResponse
	3, // 6: development.hooks.v1.HooksService.PrePush:output_type -> development.hooks.v1.HookResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_development_hooks_v1_hooks_proto_init() }
func file_development_hooks_v1_hooks_proto_init() {
	if File_development_hooks_v1_hooks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_development_hooks_v1_hooks_proto_rawDesc), len(file_development_hooks_v1_hooks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_development_hooks_v1_hooks_proto_goTypes,
		DependencyIndexes: file_development_hooks_v1_hooks_proto_depIdxs,
		MessageInfos:      file_development_hooks_v1_hooks_proto_msgTypes,
	}.Build()
	File_development_hooks_v1_hooks_proto = out.File
	file_development_hooks_v1_hooks_proto_goTypes = nil
	file_development_hooks_v1_hooks_proto_depIdxs = nil
}
