// Copyright 2026 Duizendstra. All rights reserved.
//
// Service registry types — describes services in the ecosystem.
// Go package registry/services implements the catalog and health checks.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: registry/services/v1/services.proto

package servicesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transport describes the protocol a service uses.
type Transport int32

const (
	Transport_TRANSPORT_UNSPECIFIED Transport = 0
	// Connect RPC protocol (HTTP/2 + protobuf).
	Transport_TRANSPORT_CONNECT_RPC Transport = 1
	// Model Context Protocol (stdio or SSE).
	Transport_TRANSPORT_MCP Transport = 2
)

// Enum value maps for Transport.
var (
	Transport_name = map[int32]string{
		0: "TRANSPORT_UNSPECIFIED",
		1: "TRANSPORT_CONNECT_RPC",
		2: "TRANSPORT_MCP",
	}
	Transport_value = map[string]int32{
		"TRANSPORT_UNSPECIFIED": 0,
		"TRANSPORT_CONNECT_RPC": 1,
		"TRANSPORT_MCP":         2,
	}
)

func (x Transport) Enum() *Transport {
	p := new(Transport)
	*p = x
	return p
}

func (x Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_registry_services_v1_services_proto_enumTypes[0].Descriptor()
}

func (Transport) Type() protoreflect.EnumType {
	return &file_registry_services_v1_services_proto_enumTypes[0]
}

func (x Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transport.Descriptor instead.
func (Transport) EnumDescriptor() ([]byte, []int) {
	return file_registry_services_v1_services_proto_rawDescGZIP(), []int{0}
}

// Service describes a registered service in the ecosystem.
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique service identifier (e.g. "kratos-api", "nous-api").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Default port the service listens on.
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Default bind address (e.g. "127.0.0.1").
	Bind string `protobuf:"bytes,3,opt,name=bind,proto3" json:"bind,omitempty"`
	// Protocol used by the service.
	Transport Transport `protobuf:"varint,4,opt,name=transport,proto3,enum=registry.services.v1.Transport" json:"transport,omitempty"`
	// Human-readable summary.
	Description   string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_registry_services_v1_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_registry_services_v1_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_registry_services_v1_services_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Service) GetBind() string {
	if x != nil {
		return x.Bind
	}
	return ""
}

func (x *Service) GetTransport() Transport {
	if x != nil {
		return x.Transport
	}
	return Transport_TRANSPORT_UNSPECIFIED
}

func (x *Service) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_registry_services_v1_services_proto protoreflect.FileDescriptor

const file_registry_services_v1_services_proto_rawDesc = "" +
	"\n" +
	"#registry/services/v1/services.proto\x12\x14registry.services.v1\"\xa6\x01\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04bind\x18\x03 \x01(\tR\x04bind\x12=\n" +
	"\ttransport\x18\x04 \x01(\x0e2\x1f.registry.services.v1.TransportR\ttransport\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription*T\n" +
	"\tTransport\x12\x19\n" +
	"\x15TRANSPORT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TRANSPORT_CONNECT_RPC\x10\x01\x12\x11\n" +
	"\rTRANSPORT_MCP\x10\x02BPZNgithub.com/duizendstra/alexandria/go/contracts/registry/services/v1;servicesv1b\x06proto3"

var (
	file_registry_services_v1_services_proto_rawDescOnce sync.Once
	file_registry_services_v1_services_proto_rawDescData []byte
)

func file_registry_services_v1_services_proto_rawDescGZIP() []byte {
	file_registry_services_v1_services_proto_rawDescOnce.Do(func() {
		file_registry_services_v1_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_services_v1_services_proto_rawDesc), len(file_registry_services_v1_services_proto_rawDesc)))
	})
	return file_registry_services_v1_services_proto_rawDescData
}

var file_registry_services_v1_services_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_registry_services_v1_services_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_registry_services_v1_services_proto_goTypes = []any{
	(Transport)(0),  // 0: registry.services.v1.Transport
	(*Service)(nil), // 1: registry.services.v1.Service
}
var file_registry_services_v1_services_proto_depIdxs = []int32{
	0, // 0: registry.services.v1.Service.transport:type_name -> registry.services.v1.Transport
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_registry_services_v1_services_proto_init() }
func file_registry_services_v1_services_proto_init() {
	if File_registry_services_v1_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_services_v1_services_proto_rawDesc), len(file_registry_services_v1_services_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registry_services_v1_services_proto_goTypes,
		DependencyIndexes: file_registry_services_v1_services_proto_depIdxs,
		EnumInfos:         file_registry_services_v1_services_proto_enumTypes,
		MessageInfos:      file_registry_services_v1_services_proto_msgTypes,
	}.Build()
	File_registry_services_v1_services_proto = out.File
	file_registry_services_v1_services_proto_goTypes = nil
	file_registry_services_v1_services_proto_depIdxs = nil
}
