// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: collaboration/board/v1/board.proto

package boardv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BoardItem represents an item on a GitHub Projects V2 board.
type BoardItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GitHub Projects V2 item ID (node ID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Item title (typically the issue title).
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Current status column (e.g. "Sprint", "In Progress", "Done").
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// URL to the issue or PR this item represents.
	ContentUrl string `protobuf:"bytes,4,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	// Repository in "owner/repo" format.
	Repository    string `protobuf:"bytes,5,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardItem) Reset() {
	*x = BoardItem{}
	mi := &file_collaboration_board_v1_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardItem) ProtoMessage() {}

func (x *BoardItem) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_board_v1_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardItem.ProtoReflect.Descriptor instead.
func (*BoardItem) Descriptor() ([]byte, []int) {
	return file_collaboration_board_v1_board_proto_rawDescGZIP(), []int{0}
}

func (x *BoardItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BoardItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BoardItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BoardItem) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *BoardItem) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

// BoardField represents a field (column) on a Projects V2 board.
type BoardField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GitHub field ID (node ID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Field name (e.g. "Status", "Priority", "Pillar").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Available options for single-select fields.
	Options       []*BoardFieldOption `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardField) Reset() {
	*x = BoardField{}
	mi := &file_collaboration_board_v1_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardField) ProtoMessage() {}

func (x *BoardField) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_board_v1_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardField.ProtoReflect.Descriptor instead.
func (*BoardField) Descriptor() ([]byte, []int) {
	return file_collaboration_board_v1_board_proto_rawDescGZIP(), []int{1}
}

func (x *BoardField) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BoardField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BoardField) GetOptions() []*BoardFieldOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// BoardFieldOption represents one option for a single-select field.
type BoardFieldOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GitHub option ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name (e.g. "Done", "In Progress").
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardFieldOption) Reset() {
	*x = BoardFieldOption{}
	mi := &file_collaboration_board_v1_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardFieldOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardFieldOption) ProtoMessage() {}

func (x *BoardFieldOption) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_board_v1_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardFieldOption.ProtoReflect.Descriptor instead.
func (*BoardFieldOption) Descriptor() ([]byte, []int) {
	return file_collaboration_board_v1_board_proto_rawDescGZIP(), []int{2}
}

func (x *BoardFieldOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BoardFieldOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ListBoardItemsRequest is the request message for
// [BoardService.ListBoardItems][collaboration.board.v1.BoardService.ListBoardItems].
type ListBoardItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. GitHub organization or user login.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// Required. Project board number.
	ProjectNumber int32 `protobuf:"varint,2,opt,name=project_number,json=projectNumber,proto3" json:"project_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoardItemsRequest) Reset() {
	*x = ListBoardItemsRequest{}
	mi := &file_collaboration_board_v1_board_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoardItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoardItemsRequest) ProtoMessage() {}

func (x *ListBoardItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_board_v1_board_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoardItemsRequest.ProtoReflect.Descriptor instead.
func (*ListBoardItemsRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_board_v1_board_proto_rawDescGZIP(), []int{3}
}

func (x *ListBoardItemsRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ListBoardItemsRequest) GetProjectNumber() int32 {
	if x != nil {
		return x.ProjectNumber
	}
	return 0
}

// ListBoardItemsResponse is the response message for
// [BoardService.ListBoardItems][collaboration.board.v1.BoardService.ListBoardItems].
type ListBoardItemsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Board items with current status.
	Items         []*BoardItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoardItemsResponse) Reset() {
	*x = ListBoardItemsResponse{}
	mi := &file_collaboration_board_v1_board_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoardItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoardItemsResponse) ProtoMessage() {}

func (x *ListBoardItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_board_v1_board_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoardItemsResponse.ProtoReflect.Descriptor instead.
func (*ListBoardItemsResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_board_v1_board_proto_rawDescGZIP(), []int{4}
}

func (x *ListBoardItemsResponse) GetItems() []*BoardItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// GetBoardFieldsRequest is the request message for
// [BoardService.GetBoardFields][collaboration.board.v1.BoardService.GetBoardFields].
type GetBoardFieldsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. GitHub organization or user login.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// Required. Project board number.
	ProjectNumber int32 `protobuf:"varint,2,opt,name=project_number,json=projectNumber,proto3" json:"project_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardFieldsRequest) Reset() {
	*x = GetBoardFieldsRequest{}
	mi := &file_collaboration_board_v1_board_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardFieldsRequest) ProtoMessage() {}

func (x *GetBoardFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_board_v1_board_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardFieldsRequest.ProtoReflect.Descriptor instead.
func (*GetBoardFieldsRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_board_v1_board_proto_rawDescGZIP(), []int{5}
}

func (x *GetBoardFieldsRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetBoardFieldsRequest) GetProjectNumber() int32 {
	if x != nil {
		return x.ProjectNumber
	}
	return 0
}

// GetBoardFieldsResponse is the response message for
// [BoardService.GetBoardFields][collaboration.board.v1.BoardService.GetBoardFields].
type GetBoardFieldsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Board fields with options.
	Fields        []*BoardField `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardFieldsResponse) Reset() {
	*x = GetBoardFieldsResponse{}
	mi := &file_collaboration_board_v1_board_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardFieldsResponse) ProtoMessage() {}

func (x *GetBoardFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_board_v1_board_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardFieldsResponse.ProtoReflect.Descriptor instead.
func (*GetBoardFieldsResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_board_v1_board_proto_rawDescGZIP(), []int{6}
}

func (x *GetBoardFieldsResponse) GetFields() []*BoardField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// UpdateBoardItemStatusRequest is the request message for
// [BoardService.UpdateBoardItemStatus][collaboration.board.v1.BoardService.UpdateBoardItemStatus].
type UpdateBoardItemStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. GitHub organization or user login.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// Required. Project board number.
	ProjectNumber int32 `protobuf:"varint,2,opt,name=project_number,json=projectNumber,proto3" json:"project_number,omitempty"`
	// Required. URL of the issue to update (e.g. "https://github.com/owner/repo/issues/42").
	IssueUrl string `protobuf:"bytes,3,opt,name=issue_url,json=issueUrl,proto3" json:"issue_url,omitempty"`
	// Required. Target status name (e.g. "Done", "Sprint", "In Progress").
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardItemStatusRequest) Reset() {
	*x = UpdateBoardItemStatusRequest{}
	mi := &file_collaboration_board_v1_board_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardItemStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardItemStatusRequest) ProtoMessage() {}

func (x *UpdateBoardItemStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_board_v1_board_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardItemStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateBoardItemStatusRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_board_v1_board_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBoardItemStatusRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *UpdateBoardItemStatusRequest) GetProjectNumber() int32 {
	if x != nil {
		return x.ProjectNumber
	}
	return 0
}

func (x *UpdateBoardItemStatusRequest) GetIssueUrl() string {
	if x != nil {
		return x.IssueUrl
	}
	return ""
}

func (x *UpdateBoardItemStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpdateBoardItemStatusResponse is the response message for
// [BoardService.UpdateBoardItemStatus][collaboration.board.v1.BoardService.UpdateBoardItemStatus].
type UpdateBoardItemStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated board item.
	Item          *BoardItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardItemStatusResponse) Reset() {
	*x = UpdateBoardItemStatusResponse{}
	mi := &file_collaboration_board_v1_board_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardItemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardItemStatusResponse) ProtoMessage() {}

func (x *UpdateBoardItemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_board_v1_board_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardItemStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateBoardItemStatusResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_board_v1_board_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBoardItemStatusResponse) GetItem() *BoardItem {
	if x != nil {
		return x.Item
	}
	return nil
}

// AddItemToBoardRequest is the request message for
// [BoardService.AddItemToBoard][collaboration.board.v1.BoardService.AddItemToBoard].
type AddItemToBoardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. GitHub organization or user login.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// Required. Project board number.
	ProjectNumber int32 `protobuf:"varint,2,opt,name=project_number,json=projectNumber,proto3" json:"project_number,omitempty"`
	// Required. URL of the issue to add (e.g. "https://github.com/owner/repo/issues/42").
	IssueUrl      string `protobuf:"bytes,3,opt,name=issue_url,json=issueUrl,proto3" json:"issue_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemToBoardRequest) Reset() {
	*x = AddItemToBoardRequest{}
	mi := &file_collaboration_board_v1_board_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemToBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemToBoardRequest) ProtoMessage() {}

func (x *AddItemToBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_board_v1_board_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemToBoardRequest.ProtoReflect.Descriptor instead.
func (*AddItemToBoardRequest) Descriptor() ([]byte, []int) {
	return file_collaboration_board_v1_board_proto_rawDescGZIP(), []int{9}
}

func (x *AddItemToBoardRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *AddItemToBoardRequest) GetProjectNumber() int32 {
	if x != nil {
		return x.ProjectNumber
	}
	return 0
}

func (x *AddItemToBoardRequest) GetIssueUrl() string {
	if x != nil {
		return x.IssueUrl
	}
	return ""
}

// AddItemToBoardResponse is the response message for
// [BoardService.AddItemToBoard][collaboration.board.v1.BoardService.AddItemToBoard].
type AddItemToBoardResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly added board item.
	Item          *BoardItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemToBoardResponse) Reset() {
	*x = AddItemToBoardResponse{}
	mi := &file_collaboration_board_v1_board_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemToBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemToBoardResponse) ProtoMessage() {}

func (x *AddItemToBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_collaboration_board_v1_board_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemToBoardResponse.ProtoReflect.Descriptor instead.
func (*AddItemToBoardResponse) Descriptor() ([]byte, []int) {
	return file_collaboration_board_v1_board_proto_rawDescGZIP(), []int{10}
}

func (x *AddItemToBoardResponse) GetItem() *BoardItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_collaboration_board_v1_board_proto protoreflect.FileDescriptor

const file_collaboration_board_v1_board_proto_rawDesc = "" +
	"\n" +
	"\"collaboration/board/v1/board.proto\x12\x16collaboration.board.v1\"\x8a\x01\n" +
	"\tBoardItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vcontent_url\x18\x04 \x01(\tR\n" +
	"contentUrl\x12\x1e\n" +
	"\n" +
	"repository\x18\x05 \x01(\tR\n" +
	"repository\"t\n" +
	"\n" +
	"BoardField\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12B\n" +
	"\aoptions\x18\x03 \x03(\v2(.collaboration.board.v1.BoardFieldOptionR\aoptions\"6\n" +
	"\x10BoardFieldOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"T\n" +
	"\x15ListBoardItemsRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12%\n" +
	"\x0eproject_number\x18\x02 \x01(\x05R\rprojectNumber\"Q\n" +
	"\x16ListBoardItemsResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.collaboration.board.v1.BoardItemR\x05items\"T\n" +
	"\x15GetBoardFieldsRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12%\n" +
	"\x0eproject_number\x18\x02 \x01(\x05R\rprojectNumber\"T\n" +
	"\x16GetBoardFieldsResponse\x12:\n" +
	"\x06fields\x18\x01 \x03(\v2\".collaboration.board.v1.BoardFieldR\x06fields\"\x90\x01\n" +
	"\x1cUpdateBoardItemStatusRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12%\n" +
	"\x0eproject_number\x18\x02 \x01(\x05R\rprojectNumber\x12\x1b\n" +
	"\tissue_url\x18\x03 \x01(\tR\bissueUrl\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"V\n" +
	"\x1dUpdateBoardItemStatusResponse\x125\n" +
	"\x04item\x18\x01 \x01(\v2!.collaboration.board.v1.BoardItemR\x04item\"q\n" +
	"\x15AddItemToBoardRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12%\n" +
	"\x0eproject_number\x18\x02 \x01(\x05R\rprojectNumber\x12\x1b\n" +
	"\tissue_url\x18\x03 \x01(\tR\bissueUrl\"O\n" +
	"\x16AddItemToBoardResponse\x125\n" +
	"\x04item\x18\x01 \x01(\v2!.collaboration.board.v1.BoardItemR\x04item2\xe8\x03\n" +
	"\fBoardService\x12o\n" +
	"\x0eListBoardItems\x12-.collaboration.board.v1.ListBoardItemsRequest\x1a..collaboration.board.v1.ListBoardItemsResponse\x12o\n" +
	"\x0eGetBoardFields\x12-.collaboration.board.v1.GetBoardFieldsRequest\x1a..collaboration.board.v1.GetBoardFieldsResponse\x12\x84\x01\n" +
	"\x15UpdateBoardItemStatus\x124.collaboration.board.v1.UpdateBoardItemStatusRequest\x1a5.collaboration.board.v1.UpdateBoardItemStatusResponse\x12o\n" +
	"\x0eAddItemToBoard\x12-.collaboration.board.v1.AddItemToBoardRequest\x1a..collaboration.board.v1.AddItemToBoardResponseBOZMgithub.com/duizendstra/alexandria/go/contracts/collaboration/board/v1;boardv1b\x06proto3"

var (
	file_collaboration_board_v1_board_proto_rawDescOnce sync.Once
	file_collaboration_board_v1_board_proto_rawDescData []byte
)

func file_collaboration_board_v1_board_proto_rawDescGZIP() []byte {
	file_collaboration_board_v1_board_proto_rawDescOnce.Do(func() {
		file_collaboration_board_v1_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_collaboration_board_v1_board_proto_rawDesc), len(file_collaboration_board_v1_board_proto_rawDesc)))
	})
	return file_collaboration_board_v1_board_proto_rawDescData
}

var file_collaboration_board_v1_board_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_collaboration_board_v1_board_proto_goTypes = []any{
	(*BoardItem)(nil),                     // 0: collaboration.board.v1.BoardItem
	(*BoardField)(nil),                    // 1: collaboration.board.v1.BoardField
	(*BoardFieldOption)(nil),              // 2: collaboration.board.v1.BoardFieldOption
	(*ListBoardItemsRequest)(nil),         // 3: collaboration.board.v1.ListBoardItemsRequest
	(*ListBoardItemsResponse)(nil),        // 4: collaboration.board.v1.ListBoardItemsResponse
	(*GetBoardFieldsRequest)(nil),         // 5: collaboration.board.v1.GetBoardFieldsRequest
	(*GetBoardFieldsResponse)(nil),        // 6: collaboration.board.v1.GetBoardFieldsResponse
	(*UpdateBoardItemStatusRequest)(nil),  // 7: collaboration.board.v1.UpdateBoardItemStatusRequest
	(*UpdateBoardItemStatusResponse)(nil), // 8: collaboration.board.v1.UpdateBoardItemStatusResponse
	(*AddItemToBoardRequest)(nil),         // 9: collaboration.board.v1.AddItemToBoardRequest
	(*AddItemToBoardResponse)(nil),        // 10: collaboration.board.v1.AddItemToBoardResponse
}
var file_collaboration_board_v1_board_proto_depIdxs = []int32{
	2,  // 0: collaboration.board.v1.BoardField.options:type_name -> collaboration.board.v1.BoardFieldOption
	0,  // 1: collaboration.board.v1.ListBoardItemsResponse.items:type_name -> collaboration.board.v1.BoardItem
	1,  // 2: collaboration.board.v1.GetBoardFieldsResponse.fields:type_name -> collaboration.board.v1.BoardField
	0,  // 3: collaboration.board.v1.UpdateBoardItemStatusResponse.item:type_name -> collaboration.board.v1.BoardItem
	0,  // 4: collaboration.board.v1.AddItemToBoardResponse.item:type_name -> collaboration.board.v1.BoardItem
	3,  // 5: collaboration.board.v1.BoardService.ListBoardItems:input_type -> collaboration.board.v1.ListBoardItemsRequest
	5,  // 6: collaboration.board.v1.BoardService.GetBoardFields:input_type -> collaboration.board.v1.GetBoardFieldsRequest
	7,  // 7: collaboration.board.v1.BoardService.UpdateBoardItemStatus:input_type -> collaboration.board.v1.UpdateBoardItemStatusRequest
	9,  // 8: collaboration.board.v1.BoardService.AddItemToBoard:input_type -> collaboration.board.v1.AddItemToBoardRequest
	4,  // 9: collaboration.board.v1.BoardService.ListBoardItems:output_type -> collaboration.board.v1.ListBoardItemsResponse
	6,  // 10: collaboration.board.v1.BoardService.GetBoardFields:output_type -> collaboration.board.v1.GetBoardFieldsResponse
	8,  // 11: collaboration.board.v1.BoardService.UpdateBoardItemStatus:output_type -> collaboration.board.v1.UpdateBoardItemStatusResponse
	10, // 12: collaboration.board.v1.BoardService.AddItemToBoard:output_type -> collaboration.board.v1.AddItemToBoardResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_collaboration_board_v1_board_proto_init() }
func file_collaboration_board_v1_board_proto_init() {
	if File_collaboration_board_v1_board_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collaboration_board_v1_board_proto_rawDesc), len(file_collaboration_board_v1_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collaboration_board_v1_board_proto_goTypes,
		DependencyIndexes: file_collaboration_board_v1_board_proto_depIdxs,
		MessageInfos:      file_collaboration_board_v1_board_proto_msgTypes,
	}.Build()
	File_collaboration_board_v1_board_proto = out.File
	file_collaboration_board_v1_board_proto_goTypes = nil
	file_collaboration_board_v1_board_proto_depIdxs = nil
}
