// Copyright 2026 Duizendstra. All rights reserved.
//
// Development tooling — mechanical code evolution operations
// that change the codebase structure.
//
// Domain:  Development
// Concern: How do we evolve the codebase?

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: development/tools/v1alpha1/tools.proto

package toolsv1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/duizendstra/alexandria/go/contracts/development/tools/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ToolsServiceName is the fully-qualified name of the ToolsService service.
	ToolsServiceName = "development.tools.v1alpha1.ToolsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ToolsServiceTagUntaggedProcedure is the fully-qualified name of the ToolsService's TagUntagged
	// RPC.
	ToolsServiceTagUntaggedProcedure = "/development.tools.v1alpha1.ToolsService/TagUntagged"
	// ToolsServiceMovePackagesProcedure is the fully-qualified name of the ToolsService's MovePackages
	// RPC.
	ToolsServiceMovePackagesProcedure = "/development.tools.v1alpha1.ToolsService/MovePackages"
	// ToolsServiceExtractDomainProcedure is the fully-qualified name of the ToolsService's
	// ExtractDomain RPC.
	ToolsServiceExtractDomainProcedure = "/development.tools.v1alpha1.ToolsService/ExtractDomain"
	// ToolsServiceRunQualityProcedure is the fully-qualified name of the ToolsService's RunQuality RPC.
	ToolsServiceRunQualityProcedure = "/development.tools.v1alpha1.ToolsService/RunQuality"
	// ToolsServiceSubmitQualityProcedure is the fully-qualified name of the ToolsService's
	// SubmitQuality RPC.
	ToolsServiceSubmitQualityProcedure = "/development.tools.v1alpha1.ToolsService/SubmitQuality"
	// ToolsServiceGetJobProcedure is the fully-qualified name of the ToolsService's GetJob RPC.
	ToolsServiceGetJobProcedure = "/development.tools.v1alpha1.ToolsService/GetJob"
)

// ToolsServiceClient is a client for the development.tools.v1alpha1.ToolsService service.
type ToolsServiceClient interface {
	// TagUntagged creates version tags for all untagged modules.
	TagUntagged(context.Context, *connect.Request[v1alpha1.TagUntaggedRequest]) (*connect.Response[v1alpha1.TagUntaggedResponse], error)
	// MovePackages relocates Go packages and rewires all import paths.
	MovePackages(context.Context, *connect.Request[v1alpha1.MovePackagesRequest]) (*connect.Response[v1alpha1.MovePackagesResponse], error)
	// ExtractDomain extracts domain types from a handler package into a new pure domain package.
	ExtractDomain(context.Context, *connect.Request[v1alpha1.ExtractDomainRequest]) (*connect.Response[v1alpha1.ExtractDomainResponse], error)
	// RunQuality runs the full quality gate synchronously (blocks until done).
	RunQuality(context.Context, *connect.Request[v1alpha1.RunQualityRequest]) (*connect.Response[v1alpha1.RunQualityResponse], error)
	// SubmitQuality starts a quality gate run asynchronously and returns a job ID.
	SubmitQuality(context.Context, *connect.Request[v1alpha1.RunQualityRequest]) (*connect.Response[v1alpha1.SubmitJobResponse], error)
	// GetJob polls the status of an async job by ID.
	GetJob(context.Context, *connect.Request[v1alpha1.GetJobRequest]) (*connect.Response[v1alpha1.GetJobResponse], error)
}

// NewToolsServiceClient constructs a client for the development.tools.v1alpha1.ToolsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewToolsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ToolsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	toolsServiceMethods := v1alpha1.File_development_tools_v1alpha1_tools_proto.Services().ByName("ToolsService").Methods()
	return &toolsServiceClient{
		tagUntagged: connect.NewClient[v1alpha1.TagUntaggedRequest, v1alpha1.TagUntaggedResponse](
			httpClient,
			baseURL+ToolsServiceTagUntaggedProcedure,
			connect.WithSchema(toolsServiceMethods.ByName("TagUntagged")),
			connect.WithClientOptions(opts...),
		),
		movePackages: connect.NewClient[v1alpha1.MovePackagesRequest, v1alpha1.MovePackagesResponse](
			httpClient,
			baseURL+ToolsServiceMovePackagesProcedure,
			connect.WithSchema(toolsServiceMethods.ByName("MovePackages")),
			connect.WithClientOptions(opts...),
		),
		extractDomain: connect.NewClient[v1alpha1.ExtractDomainRequest, v1alpha1.ExtractDomainResponse](
			httpClient,
			baseURL+ToolsServiceExtractDomainProcedure,
			connect.WithSchema(toolsServiceMethods.ByName("ExtractDomain")),
			connect.WithClientOptions(opts...),
		),
		runQuality: connect.NewClient[v1alpha1.RunQualityRequest, v1alpha1.RunQualityResponse](
			httpClient,
			baseURL+ToolsServiceRunQualityProcedure,
			connect.WithSchema(toolsServiceMethods.ByName("RunQuality")),
			connect.WithClientOptions(opts...),
		),
		submitQuality: connect.NewClient[v1alpha1.RunQualityRequest, v1alpha1.SubmitJobResponse](
			httpClient,
			baseURL+ToolsServiceSubmitQualityProcedure,
			connect.WithSchema(toolsServiceMethods.ByName("SubmitQuality")),
			connect.WithClientOptions(opts...),
		),
		getJob: connect.NewClient[v1alpha1.GetJobRequest, v1alpha1.GetJobResponse](
			httpClient,
			baseURL+ToolsServiceGetJobProcedure,
			connect.WithSchema(toolsServiceMethods.ByName("GetJob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// toolsServiceClient implements ToolsServiceClient.
type toolsServiceClient struct {
	tagUntagged   *connect.Client[v1alpha1.TagUntaggedRequest, v1alpha1.TagUntaggedResponse]
	movePackages  *connect.Client[v1alpha1.MovePackagesRequest, v1alpha1.MovePackagesResponse]
	extractDomain *connect.Client[v1alpha1.ExtractDomainRequest, v1alpha1.ExtractDomainResponse]
	runQuality    *connect.Client[v1alpha1.RunQualityRequest, v1alpha1.RunQualityResponse]
	submitQuality *connect.Client[v1alpha1.RunQualityRequest, v1alpha1.SubmitJobResponse]
	getJob        *connect.Client[v1alpha1.GetJobRequest, v1alpha1.GetJobResponse]
}

// TagUntagged calls development.tools.v1alpha1.ToolsService.TagUntagged.
func (c *toolsServiceClient) TagUntagged(ctx context.Context, req *connect.Request[v1alpha1.TagUntaggedRequest]) (*connect.Response[v1alpha1.TagUntaggedResponse], error) {
	return c.tagUntagged.CallUnary(ctx, req)
}

// MovePackages calls development.tools.v1alpha1.ToolsService.MovePackages.
func (c *toolsServiceClient) MovePackages(ctx context.Context, req *connect.Request[v1alpha1.MovePackagesRequest]) (*connect.Response[v1alpha1.MovePackagesResponse], error) {
	return c.movePackages.CallUnary(ctx, req)
}

// ExtractDomain calls development.tools.v1alpha1.ToolsService.ExtractDomain.
func (c *toolsServiceClient) ExtractDomain(ctx context.Context, req *connect.Request[v1alpha1.ExtractDomainRequest]) (*connect.Response[v1alpha1.ExtractDomainResponse], error) {
	return c.extractDomain.CallUnary(ctx, req)
}

// RunQuality calls development.tools.v1alpha1.ToolsService.RunQuality.
func (c *toolsServiceClient) RunQuality(ctx context.Context, req *connect.Request[v1alpha1.RunQualityRequest]) (*connect.Response[v1alpha1.RunQualityResponse], error) {
	return c.runQuality.CallUnary(ctx, req)
}

// SubmitQuality calls development.tools.v1alpha1.ToolsService.SubmitQuality.
func (c *toolsServiceClient) SubmitQuality(ctx context.Context, req *connect.Request[v1alpha1.RunQualityRequest]) (*connect.Response[v1alpha1.SubmitJobResponse], error) {
	return c.submitQuality.CallUnary(ctx, req)
}

// GetJob calls development.tools.v1alpha1.ToolsService.GetJob.
func (c *toolsServiceClient) GetJob(ctx context.Context, req *connect.Request[v1alpha1.GetJobRequest]) (*connect.Response[v1alpha1.GetJobResponse], error) {
	return c.getJob.CallUnary(ctx, req)
}

// ToolsServiceHandler is an implementation of the development.tools.v1alpha1.ToolsService service.
type ToolsServiceHandler interface {
	// TagUntagged creates version tags for all untagged modules.
	TagUntagged(context.Context, *connect.Request[v1alpha1.TagUntaggedRequest]) (*connect.Response[v1alpha1.TagUntaggedResponse], error)
	// MovePackages relocates Go packages and rewires all import paths.
	MovePackages(context.Context, *connect.Request[v1alpha1.MovePackagesRequest]) (*connect.Response[v1alpha1.MovePackagesResponse], error)
	// ExtractDomain extracts domain types from a handler package into a new pure domain package.
	ExtractDomain(context.Context, *connect.Request[v1alpha1.ExtractDomainRequest]) (*connect.Response[v1alpha1.ExtractDomainResponse], error)
	// RunQuality runs the full quality gate synchronously (blocks until done).
	RunQuality(context.Context, *connect.Request[v1alpha1.RunQualityRequest]) (*connect.Response[v1alpha1.RunQualityResponse], error)
	// SubmitQuality starts a quality gate run asynchronously and returns a job ID.
	SubmitQuality(context.Context, *connect.Request[v1alpha1.RunQualityRequest]) (*connect.Response[v1alpha1.SubmitJobResponse], error)
	// GetJob polls the status of an async job by ID.
	GetJob(context.Context, *connect.Request[v1alpha1.GetJobRequest]) (*connect.Response[v1alpha1.GetJobResponse], error)
}

// NewToolsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewToolsServiceHandler(svc ToolsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	toolsServiceMethods := v1alpha1.File_development_tools_v1alpha1_tools_proto.Services().ByName("ToolsService").Methods()
	toolsServiceTagUntaggedHandler := connect.NewUnaryHandler(
		ToolsServiceTagUntaggedProcedure,
		svc.TagUntagged,
		connect.WithSchema(toolsServiceMethods.ByName("TagUntagged")),
		connect.WithHandlerOptions(opts...),
	)
	toolsServiceMovePackagesHandler := connect.NewUnaryHandler(
		ToolsServiceMovePackagesProcedure,
		svc.MovePackages,
		connect.WithSchema(toolsServiceMethods.ByName("MovePackages")),
		connect.WithHandlerOptions(opts...),
	)
	toolsServiceExtractDomainHandler := connect.NewUnaryHandler(
		ToolsServiceExtractDomainProcedure,
		svc.ExtractDomain,
		connect.WithSchema(toolsServiceMethods.ByName("ExtractDomain")),
		connect.WithHandlerOptions(opts...),
	)
	toolsServiceRunQualityHandler := connect.NewUnaryHandler(
		ToolsServiceRunQualityProcedure,
		svc.RunQuality,
		connect.WithSchema(toolsServiceMethods.ByName("RunQuality")),
		connect.WithHandlerOptions(opts...),
	)
	toolsServiceSubmitQualityHandler := connect.NewUnaryHandler(
		ToolsServiceSubmitQualityProcedure,
		svc.SubmitQuality,
		connect.WithSchema(toolsServiceMethods.ByName("SubmitQuality")),
		connect.WithHandlerOptions(opts...),
	)
	toolsServiceGetJobHandler := connect.NewUnaryHandler(
		ToolsServiceGetJobProcedure,
		svc.GetJob,
		connect.WithSchema(toolsServiceMethods.ByName("GetJob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/development.tools.v1alpha1.ToolsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ToolsServiceTagUntaggedProcedure:
			toolsServiceTagUntaggedHandler.ServeHTTP(w, r)
		case ToolsServiceMovePackagesProcedure:
			toolsServiceMovePackagesHandler.ServeHTTP(w, r)
		case ToolsServiceExtractDomainProcedure:
			toolsServiceExtractDomainHandler.ServeHTTP(w, r)
		case ToolsServiceRunQualityProcedure:
			toolsServiceRunQualityHandler.ServeHTTP(w, r)
		case ToolsServiceSubmitQualityProcedure:
			toolsServiceSubmitQualityHandler.ServeHTTP(w, r)
		case ToolsServiceGetJobProcedure:
			toolsServiceGetJobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedToolsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedToolsServiceHandler struct{}

func (UnimplementedToolsServiceHandler) TagUntagged(context.Context, *connect.Request[v1alpha1.TagUntaggedRequest]) (*connect.Response[v1alpha1.TagUntaggedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("development.tools.v1alpha1.ToolsService.TagUntagged is not implemented"))
}

func (UnimplementedToolsServiceHandler) MovePackages(context.Context, *connect.Request[v1alpha1.MovePackagesRequest]) (*connect.Response[v1alpha1.MovePackagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("development.tools.v1alpha1.ToolsService.MovePackages is not implemented"))
}

func (UnimplementedToolsServiceHandler) ExtractDomain(context.Context, *connect.Request[v1alpha1.ExtractDomainRequest]) (*connect.Response[v1alpha1.ExtractDomainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("development.tools.v1alpha1.ToolsService.ExtractDomain is not implemented"))
}

func (UnimplementedToolsServiceHandler) RunQuality(context.Context, *connect.Request[v1alpha1.RunQualityRequest]) (*connect.Response[v1alpha1.RunQualityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("development.tools.v1alpha1.ToolsService.RunQuality is not implemented"))
}

func (UnimplementedToolsServiceHandler) SubmitQuality(context.Context, *connect.Request[v1alpha1.RunQualityRequest]) (*connect.Response[v1alpha1.SubmitJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("development.tools.v1alpha1.ToolsService.SubmitQuality is not implemented"))
}

func (UnimplementedToolsServiceHandler) GetJob(context.Context, *connect.Request[v1alpha1.GetJobRequest]) (*connect.Response[v1alpha1.GetJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("development.tools.v1alpha1.ToolsService.GetJob is not implemented"))
}
