// Copyright 2026 Duizendstra. All rights reserved.
//
// Workspace governance — validates workspace structure, conventions,
// and dependency hygiene.
//
// Domain:  Workspace
// Concern: Is the workspace well-formed?

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: workspace/governance/v1alpha1/governance.proto

package governancev1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/duizendstra/alexandria/go/contracts/workspace/governance/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GovernanceServiceName is the fully-qualified name of the GovernanceService service.
	GovernanceServiceName = "workspace.governance.v1alpha1.GovernanceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GovernanceServiceScanReadmesProcedure is the fully-qualified name of the GovernanceService's
	// ScanReadmes RPC.
	GovernanceServiceScanReadmesProcedure = "/workspace.governance.v1alpha1.GovernanceService/ScanReadmes"
	// GovernanceServiceScanScratchProcedure is the fully-qualified name of the GovernanceService's
	// ScanScratch RPC.
	GovernanceServiceScanScratchProcedure = "/workspace.governance.v1alpha1.GovernanceService/ScanScratch"
	// GovernanceServiceEnsureScratchProcedure is the fully-qualified name of the GovernanceService's
	// EnsureScratch RPC.
	GovernanceServiceEnsureScratchProcedure = "/workspace.governance.v1alpha1.GovernanceService/EnsureScratch"
	// GovernanceServiceScanPurityProcedure is the fully-qualified name of the GovernanceService's
	// ScanPurity RPC.
	GovernanceServiceScanPurityProcedure = "/workspace.governance.v1alpha1.GovernanceService/ScanPurity"
	// GovernanceServiceFixGoVersionsProcedure is the fully-qualified name of the GovernanceService's
	// FixGoVersions RPC.
	GovernanceServiceFixGoVersionsProcedure = "/workspace.governance.v1alpha1.GovernanceService/FixGoVersions"
	// GovernanceServiceCleanGoSumsProcedure is the fully-qualified name of the GovernanceService's
	// CleanGoSums RPC.
	GovernanceServiceCleanGoSumsProcedure = "/workspace.governance.v1alpha1.GovernanceService/CleanGoSums"
)

// GovernanceServiceClient is a client for the workspace.governance.v1alpha1.GovernanceService
// service.
type GovernanceServiceClient interface {
	// ScanReadmes checks all READMEs for DDD compliance (Domain + Concern).
	ScanReadmes(context.Context, *connect.Request[v1alpha1.ScanReadmesRequest]) (*connect.Response[v1alpha1.ScanReadmesResponse], error)
	// ScanScratch reports scratch folder status across all boundaries.
	ScanScratch(context.Context, *connect.Request[v1alpha1.ScanScratchRequest]) (*connect.Response[v1alpha1.ScanScratchResponse], error)
	// EnsureScratch creates missing scratch folders and gitignore entries.
	EnsureScratch(context.Context, *connect.Request[v1alpha1.EnsureScratchRequest]) (*connect.Response[v1alpha1.EnsureScratchResponse], error)
	// ScanPurity checks packages for cloud dependencies.
	ScanPurity(context.Context, *connect.Request[v1alpha1.ScanPurityRequest]) (*connect.Response[v1alpha1.ScanPurityResponse], error)
	// FixGoVersions updates all go.mod files to the target Go version.
	FixGoVersions(context.Context, *connect.Request[v1alpha1.FixGoVersionsRequest]) (*connect.Response[v1alpha1.FixGoVersionsResponse], error)
	// CleanGoSums removes stale checksums from all go.sum files.
	CleanGoSums(context.Context, *connect.Request[v1alpha1.CleanGoSumsRequest]) (*connect.Response[v1alpha1.CleanGoSumsResponse], error)
}

// NewGovernanceServiceClient constructs a client for the
// workspace.governance.v1alpha1.GovernanceService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGovernanceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GovernanceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	governanceServiceMethods := v1alpha1.File_workspace_governance_v1alpha1_governance_proto.Services().ByName("GovernanceService").Methods()
	return &governanceServiceClient{
		scanReadmes: connect.NewClient[v1alpha1.ScanReadmesRequest, v1alpha1.ScanReadmesResponse](
			httpClient,
			baseURL+GovernanceServiceScanReadmesProcedure,
			connect.WithSchema(governanceServiceMethods.ByName("ScanReadmes")),
			connect.WithClientOptions(opts...),
		),
		scanScratch: connect.NewClient[v1alpha1.ScanScratchRequest, v1alpha1.ScanScratchResponse](
			httpClient,
			baseURL+GovernanceServiceScanScratchProcedure,
			connect.WithSchema(governanceServiceMethods.ByName("ScanScratch")),
			connect.WithClientOptions(opts...),
		),
		ensureScratch: connect.NewClient[v1alpha1.EnsureScratchRequest, v1alpha1.EnsureScratchResponse](
			httpClient,
			baseURL+GovernanceServiceEnsureScratchProcedure,
			connect.WithSchema(governanceServiceMethods.ByName("EnsureScratch")),
			connect.WithClientOptions(opts...),
		),
		scanPurity: connect.NewClient[v1alpha1.ScanPurityRequest, v1alpha1.ScanPurityResponse](
			httpClient,
			baseURL+GovernanceServiceScanPurityProcedure,
			connect.WithSchema(governanceServiceMethods.ByName("ScanPurity")),
			connect.WithClientOptions(opts...),
		),
		fixGoVersions: connect.NewClient[v1alpha1.FixGoVersionsRequest, v1alpha1.FixGoVersionsResponse](
			httpClient,
			baseURL+GovernanceServiceFixGoVersionsProcedure,
			connect.WithSchema(governanceServiceMethods.ByName("FixGoVersions")),
			connect.WithClientOptions(opts...),
		),
		cleanGoSums: connect.NewClient[v1alpha1.CleanGoSumsRequest, v1alpha1.CleanGoSumsResponse](
			httpClient,
			baseURL+GovernanceServiceCleanGoSumsProcedure,
			connect.WithSchema(governanceServiceMethods.ByName("CleanGoSums")),
			connect.WithClientOptions(opts...),
		),
	}
}

// governanceServiceClient implements GovernanceServiceClient.
type governanceServiceClient struct {
	scanReadmes   *connect.Client[v1alpha1.ScanReadmesRequest, v1alpha1.ScanReadmesResponse]
	scanScratch   *connect.Client[v1alpha1.ScanScratchRequest, v1alpha1.ScanScratchResponse]
	ensureScratch *connect.Client[v1alpha1.EnsureScratchRequest, v1alpha1.EnsureScratchResponse]
	scanPurity    *connect.Client[v1alpha1.ScanPurityRequest, v1alpha1.ScanPurityResponse]
	fixGoVersions *connect.Client[v1alpha1.FixGoVersionsRequest, v1alpha1.FixGoVersionsResponse]
	cleanGoSums   *connect.Client[v1alpha1.CleanGoSumsRequest, v1alpha1.CleanGoSumsResponse]
}

// ScanReadmes calls workspace.governance.v1alpha1.GovernanceService.ScanReadmes.
func (c *governanceServiceClient) ScanReadmes(ctx context.Context, req *connect.Request[v1alpha1.ScanReadmesRequest]) (*connect.Response[v1alpha1.ScanReadmesResponse], error) {
	return c.scanReadmes.CallUnary(ctx, req)
}

// ScanScratch calls workspace.governance.v1alpha1.GovernanceService.ScanScratch.
func (c *governanceServiceClient) ScanScratch(ctx context.Context, req *connect.Request[v1alpha1.ScanScratchRequest]) (*connect.Response[v1alpha1.ScanScratchResponse], error) {
	return c.scanScratch.CallUnary(ctx, req)
}

// EnsureScratch calls workspace.governance.v1alpha1.GovernanceService.EnsureScratch.
func (c *governanceServiceClient) EnsureScratch(ctx context.Context, req *connect.Request[v1alpha1.EnsureScratchRequest]) (*connect.Response[v1alpha1.EnsureScratchResponse], error) {
	return c.ensureScratch.CallUnary(ctx, req)
}

// ScanPurity calls workspace.governance.v1alpha1.GovernanceService.ScanPurity.
func (c *governanceServiceClient) ScanPurity(ctx context.Context, req *connect.Request[v1alpha1.ScanPurityRequest]) (*connect.Response[v1alpha1.ScanPurityResponse], error) {
	return c.scanPurity.CallUnary(ctx, req)
}

// FixGoVersions calls workspace.governance.v1alpha1.GovernanceService.FixGoVersions.
func (c *governanceServiceClient) FixGoVersions(ctx context.Context, req *connect.Request[v1alpha1.FixGoVersionsRequest]) (*connect.Response[v1alpha1.FixGoVersionsResponse], error) {
	return c.fixGoVersions.CallUnary(ctx, req)
}

// CleanGoSums calls workspace.governance.v1alpha1.GovernanceService.CleanGoSums.
func (c *governanceServiceClient) CleanGoSums(ctx context.Context, req *connect.Request[v1alpha1.CleanGoSumsRequest]) (*connect.Response[v1alpha1.CleanGoSumsResponse], error) {
	return c.cleanGoSums.CallUnary(ctx, req)
}

// GovernanceServiceHandler is an implementation of the
// workspace.governance.v1alpha1.GovernanceService service.
type GovernanceServiceHandler interface {
	// ScanReadmes checks all READMEs for DDD compliance (Domain + Concern).
	ScanReadmes(context.Context, *connect.Request[v1alpha1.ScanReadmesRequest]) (*connect.Response[v1alpha1.ScanReadmesResponse], error)
	// ScanScratch reports scratch folder status across all boundaries.
	ScanScratch(context.Context, *connect.Request[v1alpha1.ScanScratchRequest]) (*connect.Response[v1alpha1.ScanScratchResponse], error)
	// EnsureScratch creates missing scratch folders and gitignore entries.
	EnsureScratch(context.Context, *connect.Request[v1alpha1.EnsureScratchRequest]) (*connect.Response[v1alpha1.EnsureScratchResponse], error)
	// ScanPurity checks packages for cloud dependencies.
	ScanPurity(context.Context, *connect.Request[v1alpha1.ScanPurityRequest]) (*connect.Response[v1alpha1.ScanPurityResponse], error)
	// FixGoVersions updates all go.mod files to the target Go version.
	FixGoVersions(context.Context, *connect.Request[v1alpha1.FixGoVersionsRequest]) (*connect.Response[v1alpha1.FixGoVersionsResponse], error)
	// CleanGoSums removes stale checksums from all go.sum files.
	CleanGoSums(context.Context, *connect.Request[v1alpha1.CleanGoSumsRequest]) (*connect.Response[v1alpha1.CleanGoSumsResponse], error)
}

// NewGovernanceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGovernanceServiceHandler(svc GovernanceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	governanceServiceMethods := v1alpha1.File_workspace_governance_v1alpha1_governance_proto.Services().ByName("GovernanceService").Methods()
	governanceServiceScanReadmesHandler := connect.NewUnaryHandler(
		GovernanceServiceScanReadmesProcedure,
		svc.ScanReadmes,
		connect.WithSchema(governanceServiceMethods.ByName("ScanReadmes")),
		connect.WithHandlerOptions(opts...),
	)
	governanceServiceScanScratchHandler := connect.NewUnaryHandler(
		GovernanceServiceScanScratchProcedure,
		svc.ScanScratch,
		connect.WithSchema(governanceServiceMethods.ByName("ScanScratch")),
		connect.WithHandlerOptions(opts...),
	)
	governanceServiceEnsureScratchHandler := connect.NewUnaryHandler(
		GovernanceServiceEnsureScratchProcedure,
		svc.EnsureScratch,
		connect.WithSchema(governanceServiceMethods.ByName("EnsureScratch")),
		connect.WithHandlerOptions(opts...),
	)
	governanceServiceScanPurityHandler := connect.NewUnaryHandler(
		GovernanceServiceScanPurityProcedure,
		svc.ScanPurity,
		connect.WithSchema(governanceServiceMethods.ByName("ScanPurity")),
		connect.WithHandlerOptions(opts...),
	)
	governanceServiceFixGoVersionsHandler := connect.NewUnaryHandler(
		GovernanceServiceFixGoVersionsProcedure,
		svc.FixGoVersions,
		connect.WithSchema(governanceServiceMethods.ByName("FixGoVersions")),
		connect.WithHandlerOptions(opts...),
	)
	governanceServiceCleanGoSumsHandler := connect.NewUnaryHandler(
		GovernanceServiceCleanGoSumsProcedure,
		svc.CleanGoSums,
		connect.WithSchema(governanceServiceMethods.ByName("CleanGoSums")),
		connect.WithHandlerOptions(opts...),
	)
	return "/workspace.governance.v1alpha1.GovernanceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GovernanceServiceScanReadmesProcedure:
			governanceServiceScanReadmesHandler.ServeHTTP(w, r)
		case GovernanceServiceScanScratchProcedure:
			governanceServiceScanScratchHandler.ServeHTTP(w, r)
		case GovernanceServiceEnsureScratchProcedure:
			governanceServiceEnsureScratchHandler.ServeHTTP(w, r)
		case GovernanceServiceScanPurityProcedure:
			governanceServiceScanPurityHandler.ServeHTTP(w, r)
		case GovernanceServiceFixGoVersionsProcedure:
			governanceServiceFixGoVersionsHandler.ServeHTTP(w, r)
		case GovernanceServiceCleanGoSumsProcedure:
			governanceServiceCleanGoSumsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGovernanceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGovernanceServiceHandler struct{}

func (UnimplementedGovernanceServiceHandler) ScanReadmes(context.Context, *connect.Request[v1alpha1.ScanReadmesRequest]) (*connect.Response[v1alpha1.ScanReadmesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.governance.v1alpha1.GovernanceService.ScanReadmes is not implemented"))
}

func (UnimplementedGovernanceServiceHandler) ScanScratch(context.Context, *connect.Request[v1alpha1.ScanScratchRequest]) (*connect.Response[v1alpha1.ScanScratchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.governance.v1alpha1.GovernanceService.ScanScratch is not implemented"))
}

func (UnimplementedGovernanceServiceHandler) EnsureScratch(context.Context, *connect.Request[v1alpha1.EnsureScratchRequest]) (*connect.Response[v1alpha1.EnsureScratchResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.governance.v1alpha1.GovernanceService.EnsureScratch is not implemented"))
}

func (UnimplementedGovernanceServiceHandler) ScanPurity(context.Context, *connect.Request[v1alpha1.ScanPurityRequest]) (*connect.Response[v1alpha1.ScanPurityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.governance.v1alpha1.GovernanceService.ScanPurity is not implemented"))
}

func (UnimplementedGovernanceServiceHandler) FixGoVersions(context.Context, *connect.Request[v1alpha1.FixGoVersionsRequest]) (*connect.Response[v1alpha1.FixGoVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.governance.v1alpha1.GovernanceService.FixGoVersions is not implemented"))
}

func (UnimplementedGovernanceServiceHandler) CleanGoSums(context.Context, *connect.Request[v1alpha1.CleanGoSumsRequest]) (*connect.Response[v1alpha1.CleanGoSumsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workspace.governance.v1alpha1.GovernanceService.CleanGoSums is not implemented"))
}
