// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: alx/postmark/v1/email.proto

package postmarkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendResponse represents Postmark's response after accepting an email.
// Source: https://postmarkapp.com/developer/api/email-api#send-a-single-email
type SendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Recipient email address.
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// Timestamp when Postmark accepted the message.
	SubmittedAt string `protobuf:"bytes,2,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	// Unique message ID assigned by Postmark.
	MessageId string `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Error code (0 = success).
	ErrorCode int32 `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Status message.
	Message       string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_alx_postmark_v1_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alx_postmark_v1_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_alx_postmark_v1_email_proto_rawDescGZIP(), []int{0}
}

func (x *SendResponse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendResponse) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

func (x *SendResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *SendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_alx_postmark_v1_email_proto protoreflect.FileDescriptor

const file_alx_postmark_v1_email_proto_rawDesc = "" +
	"\n" +
	"\x1balx/postmark/v1/email.proto\x12\x0falx.postmark.v1\"\x99\x01\n" +
	"\fSendResponse\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12!\n" +
	"\fsubmitted_at\x18\x02 \x01(\tR\vsubmittedAt\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x05R\terrorCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessageBKZIgithub.com/duizendstra/alexandria/go/contracts/alx/postmark/v1;postmarkv1b\x06proto3"

var (
	file_alx_postmark_v1_email_proto_rawDescOnce sync.Once
	file_alx_postmark_v1_email_proto_rawDescData []byte
)

func file_alx_postmark_v1_email_proto_rawDescGZIP() []byte {
	file_alx_postmark_v1_email_proto_rawDescOnce.Do(func() {
		file_alx_postmark_v1_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alx_postmark_v1_email_proto_rawDesc), len(file_alx_postmark_v1_email_proto_rawDesc)))
	})
	return file_alx_postmark_v1_email_proto_rawDescData
}

var file_alx_postmark_v1_email_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alx_postmark_v1_email_proto_goTypes = []any{
	(*SendResponse)(nil), // 0: alx.postmark.v1.SendResponse
}
var file_alx_postmark_v1_email_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alx_postmark_v1_email_proto_init() }
func file_alx_postmark_v1_email_proto_init() {
	if File_alx_postmark_v1_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alx_postmark_v1_email_proto_rawDesc), len(file_alx_postmark_v1_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alx_postmark_v1_email_proto_goTypes,
		DependencyIndexes: file_alx_postmark_v1_email_proto_depIdxs,
		MessageInfos:      file_alx_postmark_v1_email_proto_msgTypes,
	}.Build()
	File_alx_postmark_v1_email_proto = out.File
	file_alx_postmark_v1_email_proto_goTypes = nil
	file_alx_postmark_v1_email_proto_depIdxs = nil
}
