// Etchings captures raw, unclassified data for later triage.
//
// Scrumban: Capture phase — everything starts as an etch.
// CODE: Capture — instant, zero ceremony.
// PARA: Inbox — not yet classified into Projects/Areas/Resources.
// Hexagonal: core domain — EtchingsService defines the port contract.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: capture/etchings/v1alpha1/etchings.proto

package etchingsv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Etching represents a raw capture in the inbox.
type Etching struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name (e.g. "etchings/a1b2c3d4").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Raw content of the etch.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Output only. Creation time in RFC 3339 format.
	CreateTime    string `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Etching) Reset() {
	*x = Etching{}
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Etching) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Etching) ProtoMessage() {}

func (x *Etching) ProtoReflect() protoreflect.Message {
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Etching.ProtoReflect.Descriptor instead.
func (*Etching) Descriptor() ([]byte, []int) {
	return file_capture_etchings_v1alpha1_etchings_proto_rawDescGZIP(), []int{0}
}

func (x *Etching) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Etching) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Etching) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

// CreateEtchingRequest is the request for CreateEtching.
type CreateEtchingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The content to capture.
	Content       string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEtchingRequest) Reset() {
	*x = CreateEtchingRequest{}
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEtchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEtchingRequest) ProtoMessage() {}

func (x *CreateEtchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEtchingRequest.ProtoReflect.Descriptor instead.
func (*CreateEtchingRequest) Descriptor() ([]byte, []int) {
	return file_capture_etchings_v1alpha1_etchings_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEtchingRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// CreateEtchingResponse is the response for CreateEtching.
type CreateEtchingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created etching.
	Etching       *Etching `protobuf:"bytes,1,opt,name=etching,proto3" json:"etching,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEtchingResponse) Reset() {
	*x = CreateEtchingResponse{}
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEtchingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEtchingResponse) ProtoMessage() {}

func (x *CreateEtchingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEtchingResponse.ProtoReflect.Descriptor instead.
func (*CreateEtchingResponse) Descriptor() ([]byte, []int) {
	return file_capture_etchings_v1alpha1_etchings_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEtchingResponse) GetEtching() *Etching {
	if x != nil {
		return x.Etching
	}
	return nil
}

// ListEtchingsRequest is the request for ListEtchings.
type ListEtchingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEtchingsRequest) Reset() {
	*x = ListEtchingsRequest{}
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEtchingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEtchingsRequest) ProtoMessage() {}

func (x *ListEtchingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEtchingsRequest.ProtoReflect.Descriptor instead.
func (*ListEtchingsRequest) Descriptor() ([]byte, []int) {
	return file_capture_etchings_v1alpha1_etchings_proto_rawDescGZIP(), []int{3}
}

// ListEtchingsResponse is the response for ListEtchings.
type ListEtchingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All etchings in the inbox.
	Etchings []*Etching `protobuf:"bytes,1,rep,name=etchings,proto3" json:"etchings,omitempty"`
	// Total count.
	TotalCount    int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEtchingsResponse) Reset() {
	*x = ListEtchingsResponse{}
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEtchingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEtchingsResponse) ProtoMessage() {}

func (x *ListEtchingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEtchingsResponse.ProtoReflect.Descriptor instead.
func (*ListEtchingsResponse) Descriptor() ([]byte, []int) {
	return file_capture_etchings_v1alpha1_etchings_proto_rawDescGZIP(), []int{4}
}

func (x *ListEtchingsResponse) GetEtchings() []*Etching {
	if x != nil {
		return x.Etchings
	}
	return nil
}

func (x *ListEtchingsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetEtchingRequest is the request for GetEtching.
type GetEtchingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Etching ID.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEtchingRequest) Reset() {
	*x = GetEtchingRequest{}
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEtchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEtchingRequest) ProtoMessage() {}

func (x *GetEtchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEtchingRequest.ProtoReflect.Descriptor instead.
func (*GetEtchingRequest) Descriptor() ([]byte, []int) {
	return file_capture_etchings_v1alpha1_etchings_proto_rawDescGZIP(), []int{5}
}

func (x *GetEtchingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetEtchingResponse is the response for GetEtching.
type GetEtchingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested etching.
	Etching       *Etching `protobuf:"bytes,1,opt,name=etching,proto3" json:"etching,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEtchingResponse) Reset() {
	*x = GetEtchingResponse{}
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEtchingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEtchingResponse) ProtoMessage() {}

func (x *GetEtchingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEtchingResponse.ProtoReflect.Descriptor instead.
func (*GetEtchingResponse) Descriptor() ([]byte, []int) {
	return file_capture_etchings_v1alpha1_etchings_proto_rawDescGZIP(), []int{6}
}

func (x *GetEtchingResponse) GetEtching() *Etching {
	if x != nil {
		return x.Etching
	}
	return nil
}

// DeleteEtchingRequest is the request for DeleteEtching.
type DeleteEtchingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Etching ID.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEtchingRequest) Reset() {
	*x = DeleteEtchingRequest{}
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEtchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEtchingRequest) ProtoMessage() {}

func (x *DeleteEtchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEtchingRequest.ProtoReflect.Descriptor instead.
func (*DeleteEtchingRequest) Descriptor() ([]byte, []int) {
	return file_capture_etchings_v1alpha1_etchings_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEtchingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteEtchingResponse is the response for DeleteEtching.
type DeleteEtchingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEtchingResponse) Reset() {
	*x = DeleteEtchingResponse{}
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEtchingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEtchingResponse) ProtoMessage() {}

func (x *DeleteEtchingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capture_etchings_v1alpha1_etchings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEtchingResponse.ProtoReflect.Descriptor instead.
func (*DeleteEtchingResponse) Descriptor() ([]byte, []int) {
	return file_capture_etchings_v1alpha1_etchings_proto_rawDescGZIP(), []int{8}
}

var File_capture_etchings_v1alpha1_etchings_proto protoreflect.FileDescriptor

const file_capture_etchings_v1alpha1_etchings_proto_rawDesc = "" +
	"\n" +
	"(capture/etchings/v1alpha1/etchings.proto\x12\x19capture.etchings.v1alpha1\"X\n" +
	"\aEtching\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\tR\n" +
	"createTime\"0\n" +
	"\x14CreateEtchingRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"U\n" +
	"\x15CreateEtchingResponse\x12<\n" +
	"\aetching\x18\x01 \x01(\v2\".capture.etchings.v1alpha1.EtchingR\aetching\"\x15\n" +
	"\x13ListEtchingsRequest\"w\n" +
	"\x14ListEtchingsResponse\x12>\n" +
	"\betchings\x18\x01 \x03(\v2\".capture.etchings.v1alpha1.EtchingR\betchings\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"#\n" +
	"\x11GetEtchingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x12GetEtchingResponse\x12<\n" +
	"\aetching\x18\x01 \x01(\v2\".capture.etchings.v1alpha1.EtchingR\aetching\"&\n" +
	"\x14DeleteEtchingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteEtchingResponse2\xd5\x03\n" +
	"\x0fEtchingsService\x12r\n" +
	"\rCreateEtching\x12/.capture.etchings.v1alpha1.CreateEtchingRequest\x1a0.capture.etchings.v1alpha1.CreateEtchingResponse\x12o\n" +
	"\fListEtchings\x12..capture.etchings.v1alpha1.ListEtchingsRequest\x1a/.capture.etchings.v1alpha1.ListEtchingsResponse\x12i\n" +
	"\n" +
	"GetEtching\x12,.capture.etchings.v1alpha1.GetEtchingRequest\x1a-.capture.etchings.v1alpha1.GetEtchingResponse\x12r\n" +
	"\rDeleteEtching\x12/.capture.etchings.v1alpha1.DeleteEtchingRequest\x1a0.capture.etchings.v1alpha1.DeleteEtchingResponseB[ZYgithub.com/duizendstra/alexandria/go/contracts/capture/etchings/v1alpha1;etchingsv1alpha1b\x06proto3"

var (
	file_capture_etchings_v1alpha1_etchings_proto_rawDescOnce sync.Once
	file_capture_etchings_v1alpha1_etchings_proto_rawDescData []byte
)

func file_capture_etchings_v1alpha1_etchings_proto_rawDescGZIP() []byte {
	file_capture_etchings_v1alpha1_etchings_proto_rawDescOnce.Do(func() {
		file_capture_etchings_v1alpha1_etchings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capture_etchings_v1alpha1_etchings_proto_rawDesc), len(file_capture_etchings_v1alpha1_etchings_proto_rawDesc)))
	})
	return file_capture_etchings_v1alpha1_etchings_proto_rawDescData
}

var file_capture_etchings_v1alpha1_etchings_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_capture_etchings_v1alpha1_etchings_proto_goTypes = []any{
	(*Etching)(nil),               // 0: capture.etchings.v1alpha1.Etching
	(*CreateEtchingRequest)(nil),  // 1: capture.etchings.v1alpha1.CreateEtchingRequest
	(*CreateEtchingResponse)(nil), // 2: capture.etchings.v1alpha1.CreateEtchingResponse
	(*ListEtchingsRequest)(nil),   // 3: capture.etchings.v1alpha1.ListEtchingsRequest
	(*ListEtchingsResponse)(nil),  // 4: capture.etchings.v1alpha1.ListEtchingsResponse
	(*GetEtchingRequest)(nil),     // 5: capture.etchings.v1alpha1.GetEtchingRequest
	(*GetEtchingResponse)(nil),    // 6: capture.etchings.v1alpha1.GetEtchingResponse
	(*DeleteEtchingRequest)(nil),  // 7: capture.etchings.v1alpha1.DeleteEtchingRequest
	(*DeleteEtchingResponse)(nil), // 8: capture.etchings.v1alpha1.DeleteEtchingResponse
}
var file_capture_etchings_v1alpha1_etchings_proto_depIdxs = []int32{
	0, // 0: capture.etchings.v1alpha1.CreateEtchingResponse.etching:type_name -> capture.etchings.v1alpha1.Etching
	0, // 1: capture.etchings.v1alpha1.ListEtchingsResponse.etchings:type_name -> capture.etchings.v1alpha1.Etching
	0, // 2: capture.etchings.v1alpha1.GetEtchingResponse.etching:type_name -> capture.etchings.v1alpha1.Etching
	1, // 3: capture.etchings.v1alpha1.EtchingsService.CreateEtching:input_type -> capture.etchings.v1alpha1.CreateEtchingRequest
	3, // 4: capture.etchings.v1alpha1.EtchingsService.ListEtchings:input_type -> capture.etchings.v1alpha1.ListEtchingsRequest
	5, // 5: capture.etchings.v1alpha1.EtchingsService.GetEtching:input_type -> capture.etchings.v1alpha1.GetEtchingRequest
	7, // 6: capture.etchings.v1alpha1.EtchingsService.DeleteEtching:input_type -> capture.etchings.v1alpha1.DeleteEtchingRequest
	2, // 7: capture.etchings.v1alpha1.EtchingsService.CreateEtching:output_type -> capture.etchings.v1alpha1.CreateEtchingResponse
	4, // 8: capture.etchings.v1alpha1.EtchingsService.ListEtchings:output_type -> capture.etchings.v1alpha1.ListEtchingsResponse
	6, // 9: capture.etchings.v1alpha1.EtchingsService.GetEtching:output_type -> capture.etchings.v1alpha1.GetEtchingResponse
	8, // 10: capture.etchings.v1alpha1.EtchingsService.DeleteEtching:output_type -> capture.etchings.v1alpha1.DeleteEtchingResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_capture_etchings_v1alpha1_etchings_proto_init() }
func file_capture_etchings_v1alpha1_etchings_proto_init() {
	if File_capture_etchings_v1alpha1_etchings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capture_etchings_v1alpha1_etchings_proto_rawDesc), len(file_capture_etchings_v1alpha1_etchings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capture_etchings_v1alpha1_etchings_proto_goTypes,
		DependencyIndexes: file_capture_etchings_v1alpha1_etchings_proto_depIdxs,
		MessageInfos:      file_capture_etchings_v1alpha1_etchings_proto_msgTypes,
	}.Build()
	File_capture_etchings_v1alpha1_etchings_proto = out.File
	file_capture_etchings_v1alpha1_etchings_proto_goTypes = nil
	file_capture_etchings_v1alpha1_etchings_proto_depIdxs = nil
}
