// Copyright 2026 Duizendstra. All rights reserved.
//
// Artifact registry types for the Alexandria catalog.
// Go package registry/artifacts implements the file-based catalog.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: registry/artifacts/v1alpha1/artifacts.proto

package artifactsv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ArtifactType classifies what kind of asset an artifact is.
type ArtifactType int32

const (
	// Default value.
	ArtifactType_ARTIFACT_TYPE_UNSPECIFIED ArtifactType = 0
	// A reusable code or design pattern.
	ArtifactType_ARTIFACT_TYPE_PATTERN ArtifactType = 1
	// Documentation.
	ArtifactType_ARTIFACT_TYPE_DOCS ArtifactType = 2
	// A protobuf contract.
	ArtifactType_ARTIFACT_TYPE_PROTO ArtifactType = 3
	// A deployment asset.
	ArtifactType_ARTIFACT_TYPE_DEPLOY ArtifactType = 4
	// A workflow definition.
	ArtifactType_ARTIFACT_TYPE_WORKFLOW ArtifactType = 5
)

// Enum value maps for ArtifactType.
var (
	ArtifactType_name = map[int32]string{
		0: "ARTIFACT_TYPE_UNSPECIFIED",
		1: "ARTIFACT_TYPE_PATTERN",
		2: "ARTIFACT_TYPE_DOCS",
		3: "ARTIFACT_TYPE_PROTO",
		4: "ARTIFACT_TYPE_DEPLOY",
		5: "ARTIFACT_TYPE_WORKFLOW",
	}
	ArtifactType_value = map[string]int32{
		"ARTIFACT_TYPE_UNSPECIFIED": 0,
		"ARTIFACT_TYPE_PATTERN":     1,
		"ARTIFACT_TYPE_DOCS":        2,
		"ARTIFACT_TYPE_PROTO":       3,
		"ARTIFACT_TYPE_DEPLOY":      4,
		"ARTIFACT_TYPE_WORKFLOW":    5,
	}
)

func (x ArtifactType) Enum() *ArtifactType {
	p := new(ArtifactType)
	*p = x
	return p
}

func (x ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_registry_artifacts_v1alpha1_artifacts_proto_enumTypes[0].Descriptor()
}

func (ArtifactType) Type() protoreflect.EnumType {
	return &file_registry_artifacts_v1alpha1_artifacts_proto_enumTypes[0]
}

func (x ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactType.Descriptor instead.
func (ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_registry_artifacts_v1alpha1_artifacts_proto_rawDescGZIP(), []int{0}
}

// Maturity is the lifecycle stage of an artifact.
type Maturity int32

const (
	// Default value.
	Maturity_MATURITY_UNSPECIFIED Maturity = 0
	// Work in progress — not yet ready for consumers.
	Maturity_MATURITY_DRAFT Maturity = 1
	// Proven and safe to consume.
	Maturity_MATURITY_STABLE Maturity = 2
	// Scheduled for removal — do not adopt.
	Maturity_MATURITY_DEPRECATED Maturity = 3
)

// Enum value maps for Maturity.
var (
	Maturity_name = map[int32]string{
		0: "MATURITY_UNSPECIFIED",
		1: "MATURITY_DRAFT",
		2: "MATURITY_STABLE",
		3: "MATURITY_DEPRECATED",
	}
	Maturity_value = map[string]int32{
		"MATURITY_UNSPECIFIED": 0,
		"MATURITY_DRAFT":       1,
		"MATURITY_STABLE":      2,
		"MATURITY_DEPRECATED":  3,
	}
)

func (x Maturity) Enum() *Maturity {
	p := new(Maturity)
	*p = x
	return p
}

func (x Maturity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Maturity) Descriptor() protoreflect.EnumDescriptor {
	return file_registry_artifacts_v1alpha1_artifacts_proto_enumTypes[1].Descriptor()
}

func (Maturity) Type() protoreflect.EnumType {
	return &file_registry_artifacts_v1alpha1_artifacts_proto_enumTypes[1]
}

func (x Maturity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Maturity.Descriptor instead.
func (Maturity) EnumDescriptor() ([]byte, []int) {
	return file_registry_artifacts_v1alpha1_artifacts_proto_rawDescGZIP(), []int{1}
}

// Artifact represents a single entry in the Alexandria catalog.
type Artifact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique name of the artifact.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Type classification.
	Type ArtifactType `protobuf:"varint,2,opt,name=type,proto3,enum=registry.artifacts.v1alpha1.ArtifactType" json:"type,omitempty"`
	// Path relative to the Alexandria root.
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Maturity level.
	Maturity Maturity `protobuf:"varint,4,opt,name=maturity,proto3,enum=registry.artifacts.v1alpha1.Maturity" json:"maturity,omitempty"`
	// Provenance — where this artifact was ascended from (e.g. "example/sync.go").
	AscendedFrom []string `protobuf:"bytes,5,rep,name=ascended_from,json=ascendedFrom,proto3" json:"ascended_from,omitempty"`
	// Projects that consume this artifact.
	Consumers []string `protobuf:"bytes,6,rep,name=consumers,proto3" json:"consumers,omitempty"`
	// Human-readable description.
	Description   string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_registry_artifacts_v1alpha1_artifacts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_registry_artifacts_v1alpha1_artifacts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_registry_artifacts_v1alpha1_artifacts_proto_rawDescGZIP(), []int{0}
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetType() ArtifactType {
	if x != nil {
		return x.Type
	}
	return ArtifactType_ARTIFACT_TYPE_UNSPECIFIED
}

func (x *Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Artifact) GetMaturity() Maturity {
	if x != nil {
		return x.Maturity
	}
	return Maturity_MATURITY_UNSPECIFIED
}

func (x *Artifact) GetAscendedFrom() []string {
	if x != nil {
		return x.AscendedFrom
	}
	return nil
}

func (x *Artifact) GetConsumers() []string {
	if x != nil {
		return x.Consumers
	}
	return nil
}

func (x *Artifact) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Catalog is the root structure of catalog.yml.
type Catalog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All registered artifacts.
	Artifacts     []*Artifact `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_registry_artifacts_v1alpha1_artifacts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_registry_artifacts_v1alpha1_artifacts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_registry_artifacts_v1alpha1_artifacts_proto_rawDescGZIP(), []int{1}
}

func (x *Catalog) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

// AscendOptions configures an ascend operation (promoting a file to Alexandria).
type AscendOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path to the source file in the customer project.
	SourcePath string `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	// Path to the Alexandria root directory.
	AlexandriaRoot string `protobuf:"bytes,2,opt,name=alexandria_root,json=alexandriaRoot,proto3" json:"alexandria_root,omitempty"`
	// Destination path relative to Alexandria root.
	DestPath string `protobuf:"bytes,3,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"`
	// Artifact name for the catalog entry.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Artifact type for the catalog entry.
	Type ArtifactType `protobuf:"varint,5,opt,name=type,proto3,enum=registry.artifacts.v1alpha1.ArtifactType" json:"type,omitempty"`
	// Human-readable description.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Name of the originating project.
	ProjectName   string `protobuf:"bytes,7,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AscendOptions) Reset() {
	*x = AscendOptions{}
	mi := &file_registry_artifacts_v1alpha1_artifacts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AscendOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AscendOptions) ProtoMessage() {}

func (x *AscendOptions) ProtoReflect() protoreflect.Message {
	mi := &file_registry_artifacts_v1alpha1_artifacts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AscendOptions.ProtoReflect.Descriptor instead.
func (*AscendOptions) Descriptor() ([]byte, []int) {
	return file_registry_artifacts_v1alpha1_artifacts_proto_rawDescGZIP(), []int{2}
}

func (x *AscendOptions) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *AscendOptions) GetAlexandriaRoot() string {
	if x != nil {
		return x.AlexandriaRoot
	}
	return ""
}

func (x *AscendOptions) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

func (x *AscendOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AscendOptions) GetType() ArtifactType {
	if x != nil {
		return x.Type
	}
	return ArtifactType_ARTIFACT_TYPE_UNSPECIFIED
}

func (x *AscendOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AscendOptions) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

// AscendResult describes the outcome of an ascend operation.
type AscendResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path of the source file.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Absolute path of the destination file.
	Dest string `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	// The catalog entry that was created.
	Artifact      *Artifact `protobuf:"bytes,3,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AscendResult) Reset() {
	*x = AscendResult{}
	mi := &file_registry_artifacts_v1alpha1_artifacts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AscendResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AscendResult) ProtoMessage() {}

func (x *AscendResult) ProtoReflect() protoreflect.Message {
	mi := &file_registry_artifacts_v1alpha1_artifacts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AscendResult.ProtoReflect.Descriptor instead.
func (*AscendResult) Descriptor() ([]byte, []int) {
	return file_registry_artifacts_v1alpha1_artifacts_proto_rawDescGZIP(), []int{3}
}

func (x *AscendResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AscendResult) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *AscendResult) GetArtifact() *Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

var File_registry_artifacts_v1alpha1_artifacts_proto protoreflect.FileDescriptor

const file_registry_artifacts_v1alpha1_artifacts_proto_rawDesc = "" +
	"\n" +
	"+registry/artifacts/v1alpha1/artifacts.proto\x12\x1bregistry.artifacts.v1alpha1\"\x99\x02\n" +
	"\bArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12=\n" +
	"\x04type\x18\x02 \x01(\x0e2).registry.artifacts.v1alpha1.ArtifactTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12A\n" +
	"\bmaturity\x18\x04 \x01(\x0e2%.registry.artifacts.v1alpha1.MaturityR\bmaturity\x12#\n" +
	"\rascended_from\x18\x05 \x03(\tR\fascendedFrom\x12\x1c\n" +
	"\tconsumers\x18\x06 \x03(\tR\tconsumers\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"N\n" +
	"\aCatalog\x12C\n" +
	"\tartifacts\x18\x01 \x03(\v2%.registry.artifacts.v1alpha1.ArtifactR\tartifacts\"\x8e\x02\n" +
	"\rAscendOptions\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12'\n" +
	"\x0falexandria_root\x18\x02 \x01(\tR\x0ealexandriaRoot\x12\x1b\n" +
	"\tdest_path\x18\x03 \x01(\tR\bdestPath\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12=\n" +
	"\x04type\x18\x05 \x01(\x0e2).registry.artifacts.v1alpha1.ArtifactTypeR\x04type\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12!\n" +
	"\fproject_name\x18\a \x01(\tR\vprojectName\"}\n" +
	"\fAscendResult\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest\x12A\n" +
	"\bartifact\x18\x03 \x01(\v2%.registry.artifacts.v1alpha1.ArtifactR\bartifact*\xaf\x01\n" +
	"\fArtifactType\x12\x1d\n" +
	"\x19ARTIFACT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ARTIFACT_TYPE_PATTERN\x10\x01\x12\x16\n" +
	"\x12ARTIFACT_TYPE_DOCS\x10\x02\x12\x17\n" +
	"\x13ARTIFACT_TYPE_PROTO\x10\x03\x12\x18\n" +
	"\x14ARTIFACT_TYPE_DEPLOY\x10\x04\x12\x1a\n" +
	"\x16ARTIFACT_TYPE_WORKFLOW\x10\x05*f\n" +
	"\bMaturity\x12\x18\n" +
	"\x14MATURITY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eMATURITY_DRAFT\x10\x01\x12\x13\n" +
	"\x0fMATURITY_STABLE\x10\x02\x12\x17\n" +
	"\x13MATURITY_DEPRECATED\x10\x03B^Z\\github.com/duizendstra/alexandria/go/contracts/registry/artifacts/v1alpha1;artifactsv1alpha1b\x06proto3"

var (
	file_registry_artifacts_v1alpha1_artifacts_proto_rawDescOnce sync.Once
	file_registry_artifacts_v1alpha1_artifacts_proto_rawDescData []byte
)

func file_registry_artifacts_v1alpha1_artifacts_proto_rawDescGZIP() []byte {
	file_registry_artifacts_v1alpha1_artifacts_proto_rawDescOnce.Do(func() {
		file_registry_artifacts_v1alpha1_artifacts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_artifacts_v1alpha1_artifacts_proto_rawDesc), len(file_registry_artifacts_v1alpha1_artifacts_proto_rawDesc)))
	})
	return file_registry_artifacts_v1alpha1_artifacts_proto_rawDescData
}

var file_registry_artifacts_v1alpha1_artifacts_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_registry_artifacts_v1alpha1_artifacts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_registry_artifacts_v1alpha1_artifacts_proto_goTypes = []any{
	(ArtifactType)(0),     // 0: registry.artifacts.v1alpha1.ArtifactType
	(Maturity)(0),         // 1: registry.artifacts.v1alpha1.Maturity
	(*Artifact)(nil),      // 2: registry.artifacts.v1alpha1.Artifact
	(*Catalog)(nil),       // 3: registry.artifacts.v1alpha1.Catalog
	(*AscendOptions)(nil), // 4: registry.artifacts.v1alpha1.AscendOptions
	(*AscendResult)(nil),  // 5: registry.artifacts.v1alpha1.AscendResult
}
var file_registry_artifacts_v1alpha1_artifacts_proto_depIdxs = []int32{
	0, // 0: registry.artifacts.v1alpha1.Artifact.type:type_name -> registry.artifacts.v1alpha1.ArtifactType
	1, // 1: registry.artifacts.v1alpha1.Artifact.maturity:type_name -> registry.artifacts.v1alpha1.Maturity
	2, // 2: registry.artifacts.v1alpha1.Catalog.artifacts:type_name -> registry.artifacts.v1alpha1.Artifact
	0, // 3: registry.artifacts.v1alpha1.AscendOptions.type:type_name -> registry.artifacts.v1alpha1.ArtifactType
	2, // 4: registry.artifacts.v1alpha1.AscendResult.artifact:type_name -> registry.artifacts.v1alpha1.Artifact
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_registry_artifacts_v1alpha1_artifacts_proto_init() }
func file_registry_artifacts_v1alpha1_artifacts_proto_init() {
	if File_registry_artifacts_v1alpha1_artifacts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_artifacts_v1alpha1_artifacts_proto_rawDesc), len(file_registry_artifacts_v1alpha1_artifacts_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registry_artifacts_v1alpha1_artifacts_proto_goTypes,
		DependencyIndexes: file_registry_artifacts_v1alpha1_artifacts_proto_depIdxs,
		EnumInfos:         file_registry_artifacts_v1alpha1_artifacts_proto_enumTypes,
		MessageInfos:      file_registry_artifacts_v1alpha1_artifacts_proto_msgTypes,
	}.Build()
	File_registry_artifacts_v1alpha1_artifacts_proto = out.File
	file_registry_artifacts_v1alpha1_artifacts_proto_goTypes = nil
	file_registry_artifacts_v1alpha1_artifacts_proto_depIdxs = nil
}
