// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: intelligence/memory/v1alpha1/memory.proto

package memoryv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Interaction represents a single communication event stored in memory.
// Resource name pattern: "interactions/{interaction_id}" (AIP-122).
type Interaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name (e.g. "interactions/a1b2c3d4").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Origin channel (e.g. "whatsapp", "slack").
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Identifier of the message sender.
	SenderId string `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// The message content.
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// Unix timestamp of the original message.
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interaction) Reset() {
	*x = Interaction{}
	mi := &file_intelligence_memory_v1alpha1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interaction) ProtoMessage() {}

func (x *Interaction) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_memory_v1alpha1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interaction.ProtoReflect.Descriptor instead.
func (*Interaction) Descriptor() ([]byte, []int) {
	return file_intelligence_memory_v1alpha1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *Interaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Interaction) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Interaction) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Interaction) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Interaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// StoreInteractionRequest is the request message for
// [MemoryService.StoreInteraction][intelligence.memory.v1alpha1.MemoryService.StoreInteraction].
type StoreInteractionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Origin channel (e.g. "whatsapp", "slack").
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Required. Identifier of the message sender.
	SenderId string `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Required. The message content.
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Required. Unix timestamp of the original message.
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreInteractionRequest) Reset() {
	*x = StoreInteractionRequest{}
	mi := &file_intelligence_memory_v1alpha1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreInteractionRequest) ProtoMessage() {}

func (x *StoreInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_memory_v1alpha1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreInteractionRequest.ProtoReflect.Descriptor instead.
func (*StoreInteractionRequest) Descriptor() ([]byte, []int) {
	return file_intelligence_memory_v1alpha1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *StoreInteractionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StoreInteractionRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *StoreInteractionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreInteractionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// StoreInteractionResponse is the response message for
// [MemoryService.StoreInteraction][intelligence.memory.v1alpha1.MemoryService.StoreInteraction].
// Returns the full resource per AIP-133.
type StoreInteractionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stored interaction with server-assigned ID.
	Interaction   *Interaction `protobuf:"bytes,1,opt,name=interaction,proto3" json:"interaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreInteractionResponse) Reset() {
	*x = StoreInteractionResponse{}
	mi := &file_intelligence_memory_v1alpha1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreInteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreInteractionResponse) ProtoMessage() {}

func (x *StoreInteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_memory_v1alpha1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreInteractionResponse.ProtoReflect.Descriptor instead.
func (*StoreInteractionResponse) Descriptor() ([]byte, []int) {
	return file_intelligence_memory_v1alpha1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *StoreInteractionResponse) GetInteraction() *Interaction {
	if x != nil {
		return x.Interaction
	}
	return nil
}

// RetrieveContextRequest is the request message for
// [MemoryService.RetrieveContext][intelligence.memory.v1alpha1.MemoryService.RetrieveContext].
type RetrieveContextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The user's current question or intent.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Optional. Maximum number of context snippets to return. Default 10.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveContextRequest) Reset() {
	*x = RetrieveContextRequest{}
	mi := &file_intelligence_memory_v1alpha1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveContextRequest) ProtoMessage() {}

func (x *RetrieveContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_memory_v1alpha1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveContextRequest.ProtoReflect.Descriptor instead.
func (*RetrieveContextRequest) Descriptor() ([]byte, []int) {
	return file_intelligence_memory_v1alpha1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveContextRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrieveContextRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// RetrieveContextResponse is the response message for
// [MemoryService.RetrieveContext][intelligence.memory.v1alpha1.MemoryService.RetrieveContext].
type RetrieveContextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relevant historical context snippets.
	ContextSnippets []string `protobuf:"bytes,1,rep,name=context_snippets,json=contextSnippets,proto3" json:"context_snippets,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetrieveContextResponse) Reset() {
	*x = RetrieveContextResponse{}
	mi := &file_intelligence_memory_v1alpha1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveContextResponse) ProtoMessage() {}

func (x *RetrieveContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_memory_v1alpha1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveContextResponse.ProtoReflect.Descriptor instead.
func (*RetrieveContextResponse) Descriptor() ([]byte, []int) {
	return file_intelligence_memory_v1alpha1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *RetrieveContextResponse) GetContextSnippets() []string {
	if x != nil {
		return x.ContextSnippets
	}
	return nil
}

var File_intelligence_memory_v1alpha1_memory_proto protoreflect.FileDescriptor

const file_intelligence_memory_v1alpha1_memory_proto_rawDesc = "" +
	"\n" +
	")intelligence/memory/v1alpha1/memory.proto\x12\x1cintelligence.memory.v1alpha1\"\x8a\x01\n" +
	"\vInteraction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x86\x01\n" +
	"\x17StoreInteractionRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"g\n" +
	"\x18StoreInteractionResponse\x12K\n" +
	"\vinteraction\x18\x01 \x01(\v2).intelligence.memory.v1alpha1.InteractionR\vinteraction\"D\n" +
	"\x16RetrieveContextRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"D\n" +
	"\x17RetrieveContextResponse\x12)\n" +
	"\x10context_snippets\x18\x01 \x03(\tR\x0fcontextSnippets2\x93\x02\n" +
	"\rMemoryService\x12\x81\x01\n" +
	"\x10StoreInteraction\x125.intelligence.memory.v1alpha1.StoreInteractionRequest\x1a6.intelligence.memory.v1alpha1.StoreInteractionResponse\x12~\n" +
	"\x0fRetrieveContext\x124.intelligence.memory.v1alpha1.RetrieveContextRequest\x1a5.intelligence.memory.v1alpha1.RetrieveContextResponseB\\ZZgithub.com/duizendstra/alexandria/go/contracts/intelligence/memory/v1alpha1;memoryv1alpha1b\x06proto3"

var (
	file_intelligence_memory_v1alpha1_memory_proto_rawDescOnce sync.Once
	file_intelligence_memory_v1alpha1_memory_proto_rawDescData []byte
)

func file_intelligence_memory_v1alpha1_memory_proto_rawDescGZIP() []byte {
	file_intelligence_memory_v1alpha1_memory_proto_rawDescOnce.Do(func() {
		file_intelligence_memory_v1alpha1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_intelligence_memory_v1alpha1_memory_proto_rawDesc), len(file_intelligence_memory_v1alpha1_memory_proto_rawDesc)))
	})
	return file_intelligence_memory_v1alpha1_memory_proto_rawDescData
}

var file_intelligence_memory_v1alpha1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_intelligence_memory_v1alpha1_memory_proto_goTypes = []any{
	(*Interaction)(nil),              // 0: intelligence.memory.v1alpha1.Interaction
	(*StoreInteractionRequest)(nil),  // 1: intelligence.memory.v1alpha1.StoreInteractionRequest
	(*StoreInteractionResponse)(nil), // 2: intelligence.memory.v1alpha1.StoreInteractionResponse
	(*RetrieveContextRequest)(nil),   // 3: intelligence.memory.v1alpha1.RetrieveContextRequest
	(*RetrieveContextResponse)(nil),  // 4: intelligence.memory.v1alpha1.RetrieveContextResponse
}
var file_intelligence_memory_v1alpha1_memory_proto_depIdxs = []int32{
	0, // 0: intelligence.memory.v1alpha1.StoreInteractionResponse.interaction:type_name -> intelligence.memory.v1alpha1.Interaction
	1, // 1: intelligence.memory.v1alpha1.MemoryService.StoreInteraction:input_type -> intelligence.memory.v1alpha1.StoreInteractionRequest
	3, // 2: intelligence.memory.v1alpha1.MemoryService.RetrieveContext:input_type -> intelligence.memory.v1alpha1.RetrieveContextRequest
	2, // 3: intelligence.memory.v1alpha1.MemoryService.StoreInteraction:output_type -> intelligence.memory.v1alpha1.StoreInteractionResponse
	4, // 4: intelligence.memory.v1alpha1.MemoryService.RetrieveContext:output_type -> intelligence.memory.v1alpha1.RetrieveContextResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_intelligence_memory_v1alpha1_memory_proto_init() }
func file_intelligence_memory_v1alpha1_memory_proto_init() {
	if File_intelligence_memory_v1alpha1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_intelligence_memory_v1alpha1_memory_proto_rawDesc), len(file_intelligence_memory_v1alpha1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intelligence_memory_v1alpha1_memory_proto_goTypes,
		DependencyIndexes: file_intelligence_memory_v1alpha1_memory_proto_depIdxs,
		MessageInfos:      file_intelligence_memory_v1alpha1_memory_proto_msgTypes,
	}.Build()
	File_intelligence_memory_v1alpha1_memory_proto = out.File
	file_intelligence_memory_v1alpha1_memory_proto_goTypes = nil
	file_intelligence_memory_v1alpha1_memory_proto_depIdxs = nil
}
