// Copyright 2026 Duizendstra. All rights reserved.
//
// Privacy types for generic data anonymization.
// Reusable across domains — billing, contacts, employees, etc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/privacy/v1/privacy.proto

package privacyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnonymizeAction defines how a field should be anonymized.
type AnonymizeAction int32

const (
	AnonymizeAction_ANONYMIZE_ACTION_UNSPECIFIED AnonymizeAction = 0
	AnonymizeAction_ANONYMIZE_ACTION_HASH        AnonymizeAction = 1 // SHA-256 hash (deterministic, reversible with salt)
	AnonymizeAction_ANONYMIZE_ACTION_REDACT      AnonymizeAction = 2 // Replace with "[REDACTED]"
	AnonymizeAction_ANONYMIZE_ACTION_TRUNCATE    AnonymizeAction = 3 // Keep category, strip detail
	AnonymizeAction_ANONYMIZE_ACTION_KEEP        AnonymizeAction = 4 // No anonymization — field is safe
)

// Enum value maps for AnonymizeAction.
var (
	AnonymizeAction_name = map[int32]string{
		0: "ANONYMIZE_ACTION_UNSPECIFIED",
		1: "ANONYMIZE_ACTION_HASH",
		2: "ANONYMIZE_ACTION_REDACT",
		3: "ANONYMIZE_ACTION_TRUNCATE",
		4: "ANONYMIZE_ACTION_KEEP",
	}
	AnonymizeAction_value = map[string]int32{
		"ANONYMIZE_ACTION_UNSPECIFIED": 0,
		"ANONYMIZE_ACTION_HASH":        1,
		"ANONYMIZE_ACTION_REDACT":      2,
		"ANONYMIZE_ACTION_TRUNCATE":    3,
		"ANONYMIZE_ACTION_KEEP":        4,
	}
)

func (x AnonymizeAction) Enum() *AnonymizeAction {
	p := new(AnonymizeAction)
	*p = x
	return p
}

func (x AnonymizeAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnonymizeAction) Descriptor() protoreflect.EnumDescriptor {
	return file_common_privacy_v1_privacy_proto_enumTypes[0].Descriptor()
}

func (AnonymizeAction) Type() protoreflect.EnumType {
	return &file_common_privacy_v1_privacy_proto_enumTypes[0]
}

func (x AnonymizeAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnonymizeAction.Descriptor instead.
func (AnonymizeAction) EnumDescriptor() ([]byte, []int) {
	return file_common_privacy_v1_privacy_proto_rawDescGZIP(), []int{0}
}

// FieldRule maps a struct field path to an anonymization action.
type FieldRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Struct field name or dot-separated path (e.g. "ProjectID", "Service.Description").
	FieldPath string `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// Action to apply to the field value.
	Action AnonymizeAction `protobuf:"varint,2,opt,name=action,proto3,enum=common.privacy.v1.AnonymizeAction" json:"action,omitempty"`
	// Optional truncation level (1 = coarsest). Only used with TRUNCATE.
	TruncateLevel int32 `protobuf:"varint,3,opt,name=truncate_level,json=truncateLevel,proto3" json:"truncate_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldRule) Reset() {
	*x = FieldRule{}
	mi := &file_common_privacy_v1_privacy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldRule) ProtoMessage() {}

func (x *FieldRule) ProtoReflect() protoreflect.Message {
	mi := &file_common_privacy_v1_privacy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldRule.ProtoReflect.Descriptor instead.
func (*FieldRule) Descriptor() ([]byte, []int) {
	return file_common_privacy_v1_privacy_proto_rawDescGZIP(), []int{0}
}

func (x *FieldRule) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *FieldRule) GetAction() AnonymizeAction {
	if x != nil {
		return x.Action
	}
	return AnonymizeAction_ANONYMIZE_ACTION_UNSPECIFIED
}

func (x *FieldRule) GetTruncateLevel() int32 {
	if x != nil {
		return x.TruncateLevel
	}
	return 0
}

var File_common_privacy_v1_privacy_proto protoreflect.FileDescriptor

const file_common_privacy_v1_privacy_proto_rawDesc = "" +
	"\n" +
	"\x1fcommon/privacy/v1/privacy.proto\x12\x11common.privacy.v1\"\x8d\x01\n" +
	"\tFieldRule\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tR\tfieldPath\x12:\n" +
	"\x06action\x18\x02 \x01(\x0e2\".common.privacy.v1.AnonymizeActionR\x06action\x12%\n" +
	"\x0etruncate_level\x18\x03 \x01(\x05R\rtruncateLevel*\xa5\x01\n" +
	"\x0fAnonymizeAction\x12 \n" +
	"\x1cANONYMIZE_ACTION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ANONYMIZE_ACTION_HASH\x10\x01\x12\x1b\n" +
	"\x17ANONYMIZE_ACTION_REDACT\x10\x02\x12\x1d\n" +
	"\x19ANONYMIZE_ACTION_TRUNCATE\x10\x03\x12\x19\n" +
	"\x15ANONYMIZE_ACTION_KEEP\x10\x04BLZJgithub.com/duizendstra/alexandria/go/contracts/common/privacy/v1;privacyv1b\x06proto3"

var (
	file_common_privacy_v1_privacy_proto_rawDescOnce sync.Once
	file_common_privacy_v1_privacy_proto_rawDescData []byte
)

func file_common_privacy_v1_privacy_proto_rawDescGZIP() []byte {
	file_common_privacy_v1_privacy_proto_rawDescOnce.Do(func() {
		file_common_privacy_v1_privacy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_privacy_v1_privacy_proto_rawDesc), len(file_common_privacy_v1_privacy_proto_rawDesc)))
	})
	return file_common_privacy_v1_privacy_proto_rawDescData
}

var file_common_privacy_v1_privacy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_privacy_v1_privacy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_privacy_v1_privacy_proto_goTypes = []any{
	(AnonymizeAction)(0), // 0: common.privacy.v1.AnonymizeAction
	(*FieldRule)(nil),    // 1: common.privacy.v1.FieldRule
}
var file_common_privacy_v1_privacy_proto_depIdxs = []int32{
	0, // 0: common.privacy.v1.FieldRule.action:type_name -> common.privacy.v1.AnonymizeAction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_privacy_v1_privacy_proto_init() }
func file_common_privacy_v1_privacy_proto_init() {
	if File_common_privacy_v1_privacy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_privacy_v1_privacy_proto_rawDesc), len(file_common_privacy_v1_privacy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_privacy_v1_privacy_proto_goTypes,
		DependencyIndexes: file_common_privacy_v1_privacy_proto_depIdxs,
		EnumInfos:         file_common_privacy_v1_privacy_proto_enumTypes,
		MessageInfos:      file_common_privacy_v1_privacy_proto_msgTypes,
	}.Build()
	File_common_privacy_v1_privacy_proto = out.File
	file_common_privacy_v1_privacy_proto_goTypes = nil
	file_common_privacy_v1_privacy_proto_depIdxs = nil
}
