// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: collaboration/pulls/v1/pulls.proto

// Package pulls defines the collaboration layer's delivery capability.
//
// Hexagonal: inbound port — consumed by MCP tools and services.
// CODE phase: Express — the final step that ships value.
// PARA: Projects — PRs belong to time-bound deliverables.
// Scrumban: Delivery column — create_pr and merge_pr close the loop.
package pullsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/duizendstra/alexandria/go/contracts/collaboration/pulls/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PullsServiceName is the fully-qualified name of the PullsService service.
	PullsServiceName = "collaboration.pulls.v1.PullsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PullsServiceCreatePullRequestProcedure is the fully-qualified name of the PullsService's
	// CreatePullRequest RPC.
	PullsServiceCreatePullRequestProcedure = "/collaboration.pulls.v1.PullsService/CreatePullRequest"
	// PullsServiceMergePullRequestProcedure is the fully-qualified name of the PullsService's
	// MergePullRequest RPC.
	PullsServiceMergePullRequestProcedure = "/collaboration.pulls.v1.PullsService/MergePullRequest"
)

// PullsServiceClient is a client for the collaboration.pulls.v1.PullsService service.
type PullsServiceClient interface {
	// CreatePullRequest opens a new pull request (AIP-133).
	CreatePullRequest(context.Context, *connect.Request[v1.CreatePullRequestRequest]) (*connect.Response[v1.CreatePullRequestResponse], error)
	// MergePullRequest merges an open pull request.
	MergePullRequest(context.Context, *connect.Request[v1.MergePullRequestRequest]) (*connect.Response[v1.MergePullRequestResponse], error)
}

// NewPullsServiceClient constructs a client for the collaboration.pulls.v1.PullsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPullsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PullsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pullsServiceMethods := v1.File_collaboration_pulls_v1_pulls_proto.Services().ByName("PullsService").Methods()
	return &pullsServiceClient{
		createPullRequest: connect.NewClient[v1.CreatePullRequestRequest, v1.CreatePullRequestResponse](
			httpClient,
			baseURL+PullsServiceCreatePullRequestProcedure,
			connect.WithSchema(pullsServiceMethods.ByName("CreatePullRequest")),
			connect.WithClientOptions(opts...),
		),
		mergePullRequest: connect.NewClient[v1.MergePullRequestRequest, v1.MergePullRequestResponse](
			httpClient,
			baseURL+PullsServiceMergePullRequestProcedure,
			connect.WithSchema(pullsServiceMethods.ByName("MergePullRequest")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pullsServiceClient implements PullsServiceClient.
type pullsServiceClient struct {
	createPullRequest *connect.Client[v1.CreatePullRequestRequest, v1.CreatePullRequestResponse]
	mergePullRequest  *connect.Client[v1.MergePullRequestRequest, v1.MergePullRequestResponse]
}

// CreatePullRequest calls collaboration.pulls.v1.PullsService.CreatePullRequest.
func (c *pullsServiceClient) CreatePullRequest(ctx context.Context, req *connect.Request[v1.CreatePullRequestRequest]) (*connect.Response[v1.CreatePullRequestResponse], error) {
	return c.createPullRequest.CallUnary(ctx, req)
}

// MergePullRequest calls collaboration.pulls.v1.PullsService.MergePullRequest.
func (c *pullsServiceClient) MergePullRequest(ctx context.Context, req *connect.Request[v1.MergePullRequestRequest]) (*connect.Response[v1.MergePullRequestResponse], error) {
	return c.mergePullRequest.CallUnary(ctx, req)
}

// PullsServiceHandler is an implementation of the collaboration.pulls.v1.PullsService service.
type PullsServiceHandler interface {
	// CreatePullRequest opens a new pull request (AIP-133).
	CreatePullRequest(context.Context, *connect.Request[v1.CreatePullRequestRequest]) (*connect.Response[v1.CreatePullRequestResponse], error)
	// MergePullRequest merges an open pull request.
	MergePullRequest(context.Context, *connect.Request[v1.MergePullRequestRequest]) (*connect.Response[v1.MergePullRequestResponse], error)
}

// NewPullsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPullsServiceHandler(svc PullsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pullsServiceMethods := v1.File_collaboration_pulls_v1_pulls_proto.Services().ByName("PullsService").Methods()
	pullsServiceCreatePullRequestHandler := connect.NewUnaryHandler(
		PullsServiceCreatePullRequestProcedure,
		svc.CreatePullRequest,
		connect.WithSchema(pullsServiceMethods.ByName("CreatePullRequest")),
		connect.WithHandlerOptions(opts...),
	)
	pullsServiceMergePullRequestHandler := connect.NewUnaryHandler(
		PullsServiceMergePullRequestProcedure,
		svc.MergePullRequest,
		connect.WithSchema(pullsServiceMethods.ByName("MergePullRequest")),
		connect.WithHandlerOptions(opts...),
	)
	return "/collaboration.pulls.v1.PullsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PullsServiceCreatePullRequestProcedure:
			pullsServiceCreatePullRequestHandler.ServeHTTP(w, r)
		case PullsServiceMergePullRequestProcedure:
			pullsServiceMergePullRequestHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPullsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPullsServiceHandler struct{}

func (UnimplementedPullsServiceHandler) CreatePullRequest(context.Context, *connect.Request[v1.CreatePullRequestRequest]) (*connect.Response[v1.CreatePullRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("collaboration.pulls.v1.PullsService.CreatePullRequest is not implemented"))
}

func (UnimplementedPullsServiceHandler) MergePullRequest(context.Context, *connect.Request[v1.MergePullRequestRequest]) (*connect.Response[v1.MergePullRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("collaboration.pulls.v1.PullsService.MergePullRequest is not implemented"))
}
