// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: registry/skills/v1/skills.proto

// Package skills defines the registry of agent capabilities.
//
// Hexagonal: inbound port — consumed by ReasoningService and MCP discovery tools.
// CODE phase: Distill — skills are distilled patterns ready for reuse.
// PARA: Resources — capabilities available to the org.
// Second brain: Skills are the "what can I do?" self-awareness layer.
package skillsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/duizendstra/alexandria/go/contracts/registry/skills/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SkillsServiceName is the fully-qualified name of the SkillsService service.
	SkillsServiceName = "registry.skills.v1.SkillsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SkillsServiceListSkillsProcedure is the fully-qualified name of the SkillsService's ListSkills
	// RPC.
	SkillsServiceListSkillsProcedure = "/registry.skills.v1.SkillsService/ListSkills"
	// SkillsServiceGetSkillProcedure is the fully-qualified name of the SkillsService's GetSkill RPC.
	SkillsServiceGetSkillProcedure = "/registry.skills.v1.SkillsService/GetSkill"
)

// SkillsServiceClient is a client for the registry.skills.v1.SkillsService service.
type SkillsServiceClient interface {
	// ListSkills returns all registered skills (AIP-132).
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	// GetSkill returns details for a specific skill by name (AIP-131).
	GetSkill(context.Context, *connect.Request[v1.GetSkillRequest]) (*connect.Response[v1.GetSkillResponse], error)
}

// NewSkillsServiceClient constructs a client for the registry.skills.v1.SkillsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSkillsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SkillsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	skillsServiceMethods := v1.File_registry_skills_v1_skills_proto.Services().ByName("SkillsService").Methods()
	return &skillsServiceClient{
		listSkills: connect.NewClient[v1.ListSkillsRequest, v1.ListSkillsResponse](
			httpClient,
			baseURL+SkillsServiceListSkillsProcedure,
			connect.WithSchema(skillsServiceMethods.ByName("ListSkills")),
			connect.WithClientOptions(opts...),
		),
		getSkill: connect.NewClient[v1.GetSkillRequest, v1.GetSkillResponse](
			httpClient,
			baseURL+SkillsServiceGetSkillProcedure,
			connect.WithSchema(skillsServiceMethods.ByName("GetSkill")),
			connect.WithClientOptions(opts...),
		),
	}
}

// skillsServiceClient implements SkillsServiceClient.
type skillsServiceClient struct {
	listSkills *connect.Client[v1.ListSkillsRequest, v1.ListSkillsResponse]
	getSkill   *connect.Client[v1.GetSkillRequest, v1.GetSkillResponse]
}

// ListSkills calls registry.skills.v1.SkillsService.ListSkills.
func (c *skillsServiceClient) ListSkills(ctx context.Context, req *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return c.listSkills.CallUnary(ctx, req)
}

// GetSkill calls registry.skills.v1.SkillsService.GetSkill.
func (c *skillsServiceClient) GetSkill(ctx context.Context, req *connect.Request[v1.GetSkillRequest]) (*connect.Response[v1.GetSkillResponse], error) {
	return c.getSkill.CallUnary(ctx, req)
}

// SkillsServiceHandler is an implementation of the registry.skills.v1.SkillsService service.
type SkillsServiceHandler interface {
	// ListSkills returns all registered skills (AIP-132).
	ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error)
	// GetSkill returns details for a specific skill by name (AIP-131).
	GetSkill(context.Context, *connect.Request[v1.GetSkillRequest]) (*connect.Response[v1.GetSkillResponse], error)
}

// NewSkillsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSkillsServiceHandler(svc SkillsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	skillsServiceMethods := v1.File_registry_skills_v1_skills_proto.Services().ByName("SkillsService").Methods()
	skillsServiceListSkillsHandler := connect.NewUnaryHandler(
		SkillsServiceListSkillsProcedure,
		svc.ListSkills,
		connect.WithSchema(skillsServiceMethods.ByName("ListSkills")),
		connect.WithHandlerOptions(opts...),
	)
	skillsServiceGetSkillHandler := connect.NewUnaryHandler(
		SkillsServiceGetSkillProcedure,
		svc.GetSkill,
		connect.WithSchema(skillsServiceMethods.ByName("GetSkill")),
		connect.WithHandlerOptions(opts...),
	)
	return "/registry.skills.v1.SkillsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SkillsServiceListSkillsProcedure:
			skillsServiceListSkillsHandler.ServeHTTP(w, r)
		case SkillsServiceGetSkillProcedure:
			skillsServiceGetSkillHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSkillsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSkillsServiceHandler struct{}

func (UnimplementedSkillsServiceHandler) ListSkills(context.Context, *connect.Request[v1.ListSkillsRequest]) (*connect.Response[v1.ListSkillsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("registry.skills.v1.SkillsService.ListSkills is not implemented"))
}

func (UnimplementedSkillsServiceHandler) GetSkill(context.Context, *connect.Request[v1.GetSkillRequest]) (*connect.Response[v1.GetSkillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("registry.skills.v1.SkillsService.GetSkill is not implemented"))
}
