// Copyright 2026 Duizendstra. All rights reserved.
//
// Development tooling — mechanical code evolution operations
// that change the codebase structure.
//
// Domain:  Development
// Concern: How do we evolve the codebase?

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: development/tools/v1alpha1/tools.proto

package toolsv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobStatus is the lifecycle state of an async job.
type JobStatus int32

const (
	// Default value.
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	// Queued, not yet started.
	JobStatus_JOB_STATUS_PENDING JobStatus = 1
	// Currently executing.
	JobStatus_JOB_STATUS_RUNNING JobStatus = 2
	// Finished successfully — result is set.
	JobStatus_JOB_STATUS_DONE JobStatus = 3
	// Finished with an error — error is set.
	JobStatus_JOB_STATUS_FAILED JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_DONE",
		4: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_DONE":        3,
		"JOB_STATUS_FAILED":      4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_development_tools_v1alpha1_tools_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_development_tools_v1alpha1_tools_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{0}
}

type TagUntaggedRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Optional boundary path (e.g. "customers/example/vault/go").
	// When set, overrides the default goRoot/repoDir/modulePrefix.
	Boundary      string `protobuf:"bytes,3,opt,name=boundary,proto3" json:"boundary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagUntaggedRequest) Reset() {
	*x = TagUntaggedRequest{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagUntaggedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagUntaggedRequest) ProtoMessage() {}

func (x *TagUntaggedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagUntaggedRequest.ProtoReflect.Descriptor instead.
func (*TagUntaggedRequest) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{0}
}

func (x *TagUntaggedRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TagUntaggedRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TagUntaggedRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

type TagResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagResult) Reset() {
	*x = TagResult{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResult) ProtoMessage() {}

func (x *TagResult) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResult.ProtoReflect.Descriptor instead.
func (*TagResult) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{1}
}

func (x *TagResult) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type TagUntaggedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       []*TagResult           `protobuf:"bytes,1,rep,name=created,proto3" json:"created,omitempty"`
	Skipped       int32                  `protobuf:"varint,2,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagUntaggedResponse) Reset() {
	*x = TagUntaggedResponse{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagUntaggedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagUntaggedResponse) ProtoMessage() {}

func (x *TagUntaggedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagUntaggedResponse.ProtoReflect.Descriptor instead.
func (*TagUntaggedResponse) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{2}
}

func (x *TagUntaggedResponse) GetCreated() []*TagResult {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *TagUntaggedResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

// Move describes a package relocation.
type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{3}
}

func (x *Move) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Move) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type MoveResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Rewired       int32                  `protobuf:"varint,3,opt,name=rewired,proto3" json:"rewired,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResult) Reset() {
	*x = MoveResult{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResult) ProtoMessage() {}

func (x *MoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResult.ProtoReflect.Descriptor instead.
func (*MoveResult) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{4}
}

func (x *MoveResult) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MoveResult) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MoveResult) GetRewired() int32 {
	if x != nil {
		return x.Rewired
	}
	return 0
}

func (x *MoveResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MovePackagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Moves []*Move                `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	// Optional boundary path (e.g. "customers/example/vault/go").
	// When set, overrides the default goRoot/repoDir/modulePrefix.
	Boundary      string `protobuf:"bytes,2,opt,name=boundary,proto3" json:"boundary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePackagesRequest) Reset() {
	*x = MovePackagesRequest{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePackagesRequest) ProtoMessage() {}

func (x *MovePackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePackagesRequest.ProtoReflect.Descriptor instead.
func (*MovePackagesRequest) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{5}
}

func (x *MovePackagesRequest) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *MovePackagesRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

type MovePackagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MoveResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePackagesResponse) Reset() {
	*x = MovePackagesResponse{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePackagesResponse) ProtoMessage() {}

func (x *MovePackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePackagesResponse.ProtoReflect.Descriptor instead.
func (*MovePackagesResponse) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{6}
}

func (x *MovePackagesResponse) GetResults() []*MoveResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ExtractDomainRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HandlerPackage string                 `protobuf:"bytes,1,opt,name=handler_package,json=handlerPackage,proto3" json:"handler_package,omitempty"`
	DomainPackage  string                 `protobuf:"bytes,2,opt,name=domain_package,json=domainPackage,proto3" json:"domain_package,omitempty"`
	Files          []string               `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	// Optional boundary path (e.g. "customers/example/vault/go").
	// When set, overrides the default goRoot/repoDir/modulePrefix.
	Boundary      string `protobuf:"bytes,4,opt,name=boundary,proto3" json:"boundary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractDomainRequest) Reset() {
	*x = ExtractDomainRequest{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractDomainRequest) ProtoMessage() {}

func (x *ExtractDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractDomainRequest.ProtoReflect.Descriptor instead.
func (*ExtractDomainRequest) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{7}
}

func (x *ExtractDomainRequest) GetHandlerPackage() string {
	if x != nil {
		return x.HandlerPackage
	}
	return ""
}

func (x *ExtractDomainRequest) GetDomainPackage() string {
	if x != nil {
		return x.DomainPackage
	}
	return ""
}

func (x *ExtractDomainRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ExtractDomainRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

type ExtractDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	FilesMoved    []string               `protobuf:"bytes,2,rep,name=files_moved,json=filesMoved,proto3" json:"files_moved,omitempty"`
	FilesUpdated  []string               `protobuf:"bytes,3,rep,name=files_updated,json=filesUpdated,proto3" json:"files_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractDomainResponse) Reset() {
	*x = ExtractDomainResponse{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractDomainResponse) ProtoMessage() {}

func (x *ExtractDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractDomainResponse.ProtoReflect.Descriptor instead.
func (*ExtractDomainResponse) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{8}
}

func (x *ExtractDomainResponse) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *ExtractDomainResponse) GetFilesMoved() []string {
	if x != nil {
		return x.FilesMoved
	}
	return nil
}

func (x *ExtractDomainResponse) GetFilesUpdated() []string {
	if x != nil {
		return x.FilesUpdated
	}
	return nil
}

// RunQualityRequest configures a quality gate run.
type RunQualityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional boundary path to scope to a subtree (e.g. "alexandria/go/development").
	Boundary string `protobuf:"bytes,1,opt,name=boundary,proto3" json:"boundary,omitempty"`
	// When true, run on all modules — not just changed ones.
	All           bool `protobuf:"varint,2,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunQualityRequest) Reset() {
	*x = RunQualityRequest{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunQualityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunQualityRequest) ProtoMessage() {}

func (x *RunQualityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunQualityRequest.ProtoReflect.Descriptor instead.
func (*RunQualityRequest) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{9}
}

func (x *RunQualityRequest) GetBoundary() string {
	if x != nil {
		return x.Boundary
	}
	return ""
}

func (x *RunQualityRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

// QualityModuleFailure records a single module's failure with captured output.
type QualityModuleFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QualityModuleFailure) Reset() {
	*x = QualityModuleFailure{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QualityModuleFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityModuleFailure) ProtoMessage() {}

func (x *QualityModuleFailure) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityModuleFailure.ProtoReflect.Descriptor instead.
func (*QualityModuleFailure) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{10}
}

func (x *QualityModuleFailure) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *QualityModuleFailure) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// RunQualityResponse is the result of a quality gate run.
type RunQualityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the quality gate passed.
	Passed bool `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	// Human-readable summary (e.g. "quality gate PASSED" or "3 modules failed lint").
	Summary string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// Per-module failure details (empty when passed is true).
	Failures      []*QualityModuleFailure `protobuf:"bytes,3,rep,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunQualityResponse) Reset() {
	*x = RunQualityResponse{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunQualityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunQualityResponse) ProtoMessage() {}

func (x *RunQualityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunQualityResponse.ProtoReflect.Descriptor instead.
func (*RunQualityResponse) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{11}
}

func (x *RunQualityResponse) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *RunQualityResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *RunQualityResponse) GetFailures() []*QualityModuleFailure {
	if x != nil {
		return x.Failures
	}
	return nil
}

// SubmitJobResponse is returned when an async job is submitted.
type SubmitJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID to poll with GetJob.
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// GetJobRequest polls for a job's status.
type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{13}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// GetJobResponse returns the current state of an async job.
type GetJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Current lifecycle state of the job.
	Status JobStatus `protobuf:"varint,2,opt,name=status,proto3,enum=development.tools.v1alpha1.JobStatus" json:"status,omitempty"`
	// Set when status is "done" — the quality gate result.
	Result *RunQualityResponse `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// Set when status is "failed" — the error message.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_development_tools_v1alpha1_tools_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_development_tools_v1alpha1_tools_proto_rawDescGZIP(), []int{14}
}

func (x *GetJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *GetJobResponse) GetResult() *RunQualityResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetJobResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_development_tools_v1alpha1_tools_proto protoreflect.FileDescriptor

const file_development_tools_v1alpha1_tools_proto_rawDesc = "" +
	"\n" +
	"&development/tools/v1alpha1/tools.proto\x12\x1adevelopment.tools.v1alpha1\"d\n" +
	"\x12TagUntaggedRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bboundary\x18\x03 \x01(\tR\bboundary\"\x1d\n" +
	"\tTagResult\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"p\n" +
	"\x13TagUntaggedResponse\x12?\n" +
	"\acreated\x18\x01 \x03(\v2%.development.tools.v1alpha1.TagResultR\acreated\x12\x18\n" +
	"\askipped\x18\x02 \x01(\x05R\askipped\"*\n" +
	"\x04Move\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"`\n" +
	"\n" +
	"MoveResult\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\arewired\x18\x03 \x01(\x05R\arewired\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"i\n" +
	"\x13MovePackagesRequest\x126\n" +
	"\x05moves\x18\x01 \x03(\v2 .development.tools.v1alpha1.MoveR\x05moves\x12\x1a\n" +
	"\bboundary\x18\x02 \x01(\tR\bboundary\"X\n" +
	"\x14MovePackagesResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.development.tools.v1alpha1.MoveResultR\aresults\"\x98\x01\n" +
	"\x14ExtractDomainRequest\x12'\n" +
	"\x0fhandler_package\x18\x01 \x01(\tR\x0ehandlerPackage\x12%\n" +
	"\x0edomain_package\x18\x02 \x01(\tR\rdomainPackage\x12\x14\n" +
	"\x05files\x18\x03 \x03(\tR\x05files\x12\x1a\n" +
	"\bboundary\x18\x04 \x01(\tR\bboundary\"w\n" +
	"\x15ExtractDomainResponse\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1f\n" +
	"\vfiles_moved\x18\x02 \x03(\tR\n" +
	"filesMoved\x12#\n" +
	"\rfiles_updated\x18\x03 \x03(\tR\ffilesUpdated\"A\n" +
	"\x11RunQualityRequest\x12\x1a\n" +
	"\bboundary\x18\x01 \x01(\tR\bboundary\x12\x10\n" +
	"\x03all\x18\x02 \x01(\bR\x03all\"F\n" +
	"\x14QualityModuleFailure\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"\x94\x01\n" +
	"\x12RunQualityResponse\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12L\n" +
	"\bfailures\x18\x03 \x03(\v20.development.tools.v1alpha1.QualityModuleFailureR\bfailures\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xc4\x01\n" +
	"\x0eGetJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.development.tools.v1alpha1.JobStatusR\x06status\x12F\n" +
	"\x06result\x18\x03 \x01(\v2..development.tools.v1alpha1.RunQualityResponseR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*\x83\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x13\n" +
	"\x0fJOB_STATUS_DONE\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x042\xa4\x05\n" +
	"\fToolsService\x12n\n" +
	"\vTagUntagged\x12..development.tools.v1alpha1.TagUntaggedRequest\x1a/.development.tools.v1alpha1.TagUntaggedResponse\x12q\n" +
	"\fMovePackages\x12/.development.tools.v1alpha1.MovePackagesRequest\x1a0.development.tools.v1alpha1.MovePackagesResponse\x12t\n" +
	"\rExtractDomain\x120.development.tools.v1alpha1.ExtractDomainRequest\x1a1.development.tools.v1alpha1.ExtractDomainResponse\x12k\n" +
	"\n" +
	"RunQuality\x12-.development.tools.v1alpha1.RunQualityRequest\x1a..development.tools.v1alpha1.RunQualityResponse\x12m\n" +
	"\rSubmitQuality\x12-.development.tools.v1alpha1.RunQualityRequest\x1a-.development.tools.v1alpha1.SubmitJobResponse\x12_\n" +
	"\x06GetJob\x12).development.tools.v1alpha1.GetJobRequest\x1a*.development.tools.v1alpha1.GetJobResponseBYZWgithub.com/duizendstra/alexandria/go/contracts/development/tools/v1alpha1;toolsv1alpha1b\x06proto3"

var (
	file_development_tools_v1alpha1_tools_proto_rawDescOnce sync.Once
	file_development_tools_v1alpha1_tools_proto_rawDescData []byte
)

func file_development_tools_v1alpha1_tools_proto_rawDescGZIP() []byte {
	file_development_tools_v1alpha1_tools_proto_rawDescOnce.Do(func() {
		file_development_tools_v1alpha1_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_development_tools_v1alpha1_tools_proto_rawDesc), len(file_development_tools_v1alpha1_tools_proto_rawDesc)))
	})
	return file_development_tools_v1alpha1_tools_proto_rawDescData
}

var file_development_tools_v1alpha1_tools_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_development_tools_v1alpha1_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_development_tools_v1alpha1_tools_proto_goTypes = []any{
	(JobStatus)(0),                // 0: development.tools.v1alpha1.JobStatus
	(*TagUntaggedRequest)(nil),    // 1: development.tools.v1alpha1.TagUntaggedRequest
	(*TagResult)(nil),             // 2: development.tools.v1alpha1.TagResult
	(*TagUntaggedResponse)(nil),   // 3: development.tools.v1alpha1.TagUntaggedResponse
	(*Move)(nil),                  // 4: development.tools.v1alpha1.Move
	(*MoveResult)(nil),            // 5: development.tools.v1alpha1.MoveResult
	(*MovePackagesRequest)(nil),   // 6: development.tools.v1alpha1.MovePackagesRequest
	(*MovePackagesResponse)(nil),  // 7: development.tools.v1alpha1.MovePackagesResponse
	(*ExtractDomainRequest)(nil),  // 8: development.tools.v1alpha1.ExtractDomainRequest
	(*ExtractDomainResponse)(nil), // 9: development.tools.v1alpha1.ExtractDomainResponse
	(*RunQualityRequest)(nil),     // 10: development.tools.v1alpha1.RunQualityRequest
	(*QualityModuleFailure)(nil),  // 11: development.tools.v1alpha1.QualityModuleFailure
	(*RunQualityResponse)(nil),    // 12: development.tools.v1alpha1.RunQualityResponse
	(*SubmitJobResponse)(nil),     // 13: development.tools.v1alpha1.SubmitJobResponse
	(*GetJobRequest)(nil),         // 14: development.tools.v1alpha1.GetJobRequest
	(*GetJobResponse)(nil),        // 15: development.tools.v1alpha1.GetJobResponse
}
var file_development_tools_v1alpha1_tools_proto_depIdxs = []int32{
	2,  // 0: development.tools.v1alpha1.TagUntaggedResponse.created:type_name -> development.tools.v1alpha1.TagResult
	4,  // 1: development.tools.v1alpha1.MovePackagesRequest.moves:type_name -> development.tools.v1alpha1.Move
	5,  // 2: development.tools.v1alpha1.MovePackagesResponse.results:type_name -> development.tools.v1alpha1.MoveResult
	11, // 3: development.tools.v1alpha1.RunQualityResponse.failures:type_name -> development.tools.v1alpha1.QualityModuleFailure
	0,  // 4: development.tools.v1alpha1.GetJobResponse.status:type_name -> development.tools.v1alpha1.JobStatus
	12, // 5: development.tools.v1alpha1.GetJobResponse.result:type_name -> development.tools.v1alpha1.RunQualityResponse
	1,  // 6: development.tools.v1alpha1.ToolsService.TagUntagged:input_type -> development.tools.v1alpha1.TagUntaggedRequest
	6,  // 7: development.tools.v1alpha1.ToolsService.MovePackages:input_type -> development.tools.v1alpha1.MovePackagesRequest
	8,  // 8: development.tools.v1alpha1.ToolsService.ExtractDomain:input_type -> development.tools.v1alpha1.ExtractDomainRequest
	10, // 9: development.tools.v1alpha1.ToolsService.RunQuality:input_type -> development.tools.v1alpha1.RunQualityRequest
	10, // 10: development.tools.v1alpha1.ToolsService.SubmitQuality:input_type -> development.tools.v1alpha1.RunQualityRequest
	14, // 11: development.tools.v1alpha1.ToolsService.GetJob:input_type -> development.tools.v1alpha1.GetJobRequest
	3,  // 12: development.tools.v1alpha1.ToolsService.TagUntagged:output_type -> development.tools.v1alpha1.TagUntaggedResponse
	7,  // 13: development.tools.v1alpha1.ToolsService.MovePackages:output_type -> development.tools.v1alpha1.MovePackagesResponse
	9,  // 14: development.tools.v1alpha1.ToolsService.ExtractDomain:output_type -> development.tools.v1alpha1.ExtractDomainResponse
	12, // 15: development.tools.v1alpha1.ToolsService.RunQuality:output_type -> development.tools.v1alpha1.RunQualityResponse
	13, // 16: development.tools.v1alpha1.ToolsService.SubmitQuality:output_type -> development.tools.v1alpha1.SubmitJobResponse
	15, // 17: development.tools.v1alpha1.ToolsService.GetJob:output_type -> development.tools.v1alpha1.GetJobResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_development_tools_v1alpha1_tools_proto_init() }
func file_development_tools_v1alpha1_tools_proto_init() {
	if File_development_tools_v1alpha1_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_development_tools_v1alpha1_tools_proto_rawDesc), len(file_development_tools_v1alpha1_tools_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_development_tools_v1alpha1_tools_proto_goTypes,
		DependencyIndexes: file_development_tools_v1alpha1_tools_proto_depIdxs,
		EnumInfos:         file_development_tools_v1alpha1_tools_proto_enumTypes,
		MessageInfos:      file_development_tools_v1alpha1_tools_proto_msgTypes,
	}.Build()
	File_development_tools_v1alpha1_tools_proto = out.File
	file_development_tools_v1alpha1_tools_proto_goTypes = nil
	file_development_tools_v1alpha1_tools_proto_depIdxs = nil
}
