// Copyright 2026 Duizendstra. All rights reserved.
//
// Spoke identity and registration — every machine (developer laptop,
// CI runner, cloud instance) that participates in the workspace is a
// spoke. Spokes register with the hub and report their capabilities.
//
// Domain:  Workspace
// Concern: How do we identify and track workspace participants?

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workspace/spoke/v1/spoke.proto

package spokev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SpokeType identifies what kind of participant this is.
type SpokeType int32

const (
	SpokeType_SPOKE_TYPE_UNSPECIFIED SpokeType = 0
	// Human developer machine.
	SpokeType_SPOKE_TYPE_DEVELOPER SpokeType = 1
	// AI agent (e.g. Antigravity, Remote).
	SpokeType_SPOKE_TYPE_AGENT SpokeType = 2
	// CI runner (GitHub Actions).
	SpokeType_SPOKE_TYPE_CI SpokeType = 3
	// Cloud service (Cloud Run).
	SpokeType_SPOKE_TYPE_CLOUD SpokeType = 4
)

// Enum value maps for SpokeType.
var (
	SpokeType_name = map[int32]string{
		0: "SPOKE_TYPE_UNSPECIFIED",
		1: "SPOKE_TYPE_DEVELOPER",
		2: "SPOKE_TYPE_AGENT",
		3: "SPOKE_TYPE_CI",
		4: "SPOKE_TYPE_CLOUD",
	}
	SpokeType_value = map[string]int32{
		"SPOKE_TYPE_UNSPECIFIED": 0,
		"SPOKE_TYPE_DEVELOPER":   1,
		"SPOKE_TYPE_AGENT":       2,
		"SPOKE_TYPE_CI":          3,
		"SPOKE_TYPE_CLOUD":       4,
	}
)

func (x SpokeType) Enum() *SpokeType {
	p := new(SpokeType)
	*p = x
	return p
}

func (x SpokeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpokeType) Descriptor() protoreflect.EnumDescriptor {
	return file_workspace_spoke_v1_spoke_proto_enumTypes[0].Descriptor()
}

func (SpokeType) Type() protoreflect.EnumType {
	return &file_workspace_spoke_v1_spoke_proto_enumTypes[0]
}

func (x SpokeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpokeType.Descriptor instead.
func (SpokeType) EnumDescriptor() ([]byte, []int) {
	return file_workspace_spoke_v1_spoke_proto_rawDescGZIP(), []int{0}
}

// SpokeStatus is the current operational state of a spoke.
type SpokeStatus int32

const (
	SpokeStatus_SPOKE_STATUS_UNSPECIFIED SpokeStatus = 0
	// Spoke is online and active.
	SpokeStatus_SPOKE_STATUS_ACTIVE SpokeStatus = 1
	// Spoke is online but idle (no active session).
	SpokeStatus_SPOKE_STATUS_IDLE SpokeStatus = 2
	// Spoke has not heartbeated recently.
	SpokeStatus_SPOKE_STATUS_STALE SpokeStatus = 3
	// Spoke is syncing with the hub.
	SpokeStatus_SPOKE_STATUS_SYNCING SpokeStatus = 4
	// Spoke has unresolved conflicts.
	SpokeStatus_SPOKE_STATUS_CONFLICT SpokeStatus = 5
)

// Enum value maps for SpokeStatus.
var (
	SpokeStatus_name = map[int32]string{
		0: "SPOKE_STATUS_UNSPECIFIED",
		1: "SPOKE_STATUS_ACTIVE",
		2: "SPOKE_STATUS_IDLE",
		3: "SPOKE_STATUS_STALE",
		4: "SPOKE_STATUS_SYNCING",
		5: "SPOKE_STATUS_CONFLICT",
	}
	SpokeStatus_value = map[string]int32{
		"SPOKE_STATUS_UNSPECIFIED": 0,
		"SPOKE_STATUS_ACTIVE":      1,
		"SPOKE_STATUS_IDLE":        2,
		"SPOKE_STATUS_STALE":       3,
		"SPOKE_STATUS_SYNCING":     4,
		"SPOKE_STATUS_CONFLICT":    5,
	}
)

func (x SpokeStatus) Enum() *SpokeStatus {
	p := new(SpokeStatus)
	*p = x
	return p
}

func (x SpokeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpokeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workspace_spoke_v1_spoke_proto_enumTypes[1].Descriptor()
}

func (SpokeStatus) Type() protoreflect.EnumType {
	return &file_workspace_spoke_v1_spoke_proto_enumTypes[1]
}

func (x SpokeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpokeStatus.Descriptor instead.
func (SpokeStatus) EnumDescriptor() ([]byte, []int) {
	return file_workspace_spoke_v1_spoke_proto_rawDescGZIP(), []int{1}
}

// Spoke describes a workspace participant.
type Spoke struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique spoke identifier (stable across sessions).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name (e.g. "jasper-macbook", "antigravity", "ci-runner-1").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// What kind of participant.
	Type SpokeType `protobuf:"varint,3,opt,name=type,proto3,enum=workspace.spoke.v1.SpokeType" json:"type,omitempty"`
	// Machine hostname.
	Hostname string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Available resources (e.g. "workspace", "git", "gcp", "github").
	Resources []string `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	// Last heartbeat timestamp (RFC 3339).
	LastSeen string `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// Current status.
	Status        SpokeStatus `protobuf:"varint,7,opt,name=status,proto3,enum=workspace.spoke.v1.SpokeStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Spoke) Reset() {
	*x = Spoke{}
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Spoke) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Spoke) ProtoMessage() {}

func (x *Spoke) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Spoke.ProtoReflect.Descriptor instead.
func (*Spoke) Descriptor() ([]byte, []int) {
	return file_workspace_spoke_v1_spoke_proto_rawDescGZIP(), []int{0}
}

func (x *Spoke) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Spoke) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Spoke) GetType() SpokeType {
	if x != nil {
		return x.Type
	}
	return SpokeType_SPOKE_TYPE_UNSPECIFIED
}

func (x *Spoke) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Spoke) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Spoke) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *Spoke) GetStatus() SpokeStatus {
	if x != nil {
		return x.Status
	}
	return SpokeStatus_SPOKE_STATUS_UNSPECIFIED
}

// RegisterRequest announces a spoke to the hub.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          SpokeType              `protobuf:"varint,2,opt,name=type,proto3,enum=workspace.spoke.v1.SpokeType" json:"type,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Resources     []string               `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_workspace_spoke_v1_spoke_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetType() SpokeType {
	if x != nil {
		return x.Type
	}
	return SpokeType_SPOKE_TYPE_UNSPECIFIED
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

// RegisterResponse confirms spoke registration.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assigned spoke ID (stable, reused on re-registration).
	SpokeId       string `protobuf:"bytes,1,opt,name=spoke_id,json=spokeId,proto3" json:"spoke_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_workspace_spoke_v1_spoke_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetSpokeId() string {
	if x != nil {
		return x.SpokeId
	}
	return ""
}

// HeartbeatRequest reports ongoing spoke health.
type HeartbeatRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	SpokeId string                 `protobuf:"bytes,1,opt,name=spoke_id,json=spokeId,proto3" json:"spoke_id,omitempty"`
	Status  SpokeStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=workspace.spoke.v1.SpokeStatus" json:"status,omitempty"`
	// Number of local commits not yet synced.
	CommitsPending int32 `protobuf:"varint,3,opt,name=commits_pending,json=commitsPending,proto3" json:"commits_pending,omitempty"`
	// Repos with dirty working trees.
	DirtyRepos    []string `protobuf:"bytes,4,rep,name=dirty_repos,json=dirtyRepos,proto3" json:"dirty_repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_workspace_spoke_v1_spoke_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetSpokeId() string {
	if x != nil {
		return x.SpokeId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() SpokeStatus {
	if x != nil {
		return x.Status
	}
	return SpokeStatus_SPOKE_STATUS_UNSPECIFIED
}

func (x *HeartbeatRequest) GetCommitsPending() int32 {
	if x != nil {
		return x.CommitsPending
	}
	return 0
}

func (x *HeartbeatRequest) GetDirtyRepos() []string {
	if x != nil {
		return x.DirtyRepos
	}
	return nil
}

// HeartbeatResponse acknowledges the heartbeat.
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Actionable events pending for this spoke (from timeline).
	PendingActions int32 `protobuf:"varint,1,opt,name=pending_actions,json=pendingActions,proto3" json:"pending_actions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_workspace_spoke_v1_spoke_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetPendingActions() int32 {
	if x != nil {
		return x.PendingActions
	}
	return 0
}

// ListRequest queries known spokes.
type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by type.
	Type SpokeType `protobuf:"varint,1,opt,name=type,proto3,enum=workspace.spoke.v1.SpokeType" json:"type,omitempty"`
	// Optional filter by status.
	Status        SpokeStatus `protobuf:"varint,2,opt,name=status,proto3,enum=workspace.spoke.v1.SpokeStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_workspace_spoke_v1_spoke_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetType() SpokeType {
	if x != nil {
		return x.Type
	}
	return SpokeType_SPOKE_TYPE_UNSPECIFIED
}

func (x *ListRequest) GetStatus() SpokeStatus {
	if x != nil {
		return x.Status
	}
	return SpokeStatus_SPOKE_STATUS_UNSPECIFIED
}

// ListResponse returns known spokes.
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spokes        []*Spoke               `protobuf:"bytes,1,rep,name=spokes,proto3" json:"spokes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_spoke_v1_spoke_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_workspace_spoke_v1_spoke_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetSpokes() []*Spoke {
	if x != nil {
		return x.Spokes
	}
	return nil
}

var File_workspace_spoke_v1_spoke_proto protoreflect.FileDescriptor

const file_workspace_spoke_v1_spoke_proto_rawDesc = "" +
	"\n" +
	"\x1eworkspace/spoke/v1/spoke.proto\x12\x12workspace.spoke.v1\"\xee\x01\n" +
	"\x05Spoke\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.workspace.spoke.v1.SpokeTypeR\x04type\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x1c\n" +
	"\tresources\x18\x05 \x03(\tR\tresources\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\tR\blastSeen\x127\n" +
	"\x06status\x18\a \x01(\x0e2\x1f.workspace.spoke.v1.SpokeStatusR\x06status\"\x92\x01\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.workspace.spoke.v1.SpokeTypeR\x04type\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1c\n" +
	"\tresources\x18\x04 \x03(\tR\tresources\"-\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bspoke_id\x18\x01 \x01(\tR\aspokeId\"\xb0\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bspoke_id\x18\x01 \x01(\tR\aspokeId\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.workspace.spoke.v1.SpokeStatusR\x06status\x12'\n" +
	"\x0fcommits_pending\x18\x03 \x01(\x05R\x0ecommitsPending\x12\x1f\n" +
	"\vdirty_repos\x18\x04 \x03(\tR\n" +
	"dirtyRepos\"<\n" +
	"\x11HeartbeatResponse\x12'\n" +
	"\x0fpending_actions\x18\x01 \x01(\x05R\x0ependingActions\"y\n" +
	"\vListRequest\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.workspace.spoke.v1.SpokeTypeR\x04type\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.workspace.spoke.v1.SpokeStatusR\x06status\"A\n" +
	"\fListResponse\x121\n" +
	"\x06spokes\x18\x01 \x03(\v2\x19.workspace.spoke.v1.SpokeR\x06spokes*\x80\x01\n" +
	"\tSpokeType\x12\x1a\n" +
	"\x16SPOKE_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SPOKE_TYPE_DEVELOPER\x10\x01\x12\x14\n" +
	"\x10SPOKE_TYPE_AGENT\x10\x02\x12\x11\n" +
	"\rSPOKE_TYPE_CI\x10\x03\x12\x14\n" +
	"\x10SPOKE_TYPE_CLOUD\x10\x04*\xa8\x01\n" +
	"\vSpokeStatus\x12\x1c\n" +
	"\x18SPOKE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SPOKE_STATUS_ACTIVE\x10\x01\x12\x15\n" +
	"\x11SPOKE_STATUS_IDLE\x10\x02\x12\x16\n" +
	"\x12SPOKE_STATUS_STALE\x10\x03\x12\x18\n" +
	"\x14SPOKE_STATUS_SYNCING\x10\x04\x12\x19\n" +
	"\x15SPOKE_STATUS_CONFLICT\x10\x052\x8a\x02\n" +
	"\fSpokeService\x12U\n" +
	"\bRegister\x12#.workspace.spoke.v1.RegisterRequest\x1a$.workspace.spoke.v1.RegisterResponse\x12X\n" +
	"\tHeartbeat\x12$.workspace.spoke.v1.HeartbeatRequest\x1a%.workspace.spoke.v1.HeartbeatResponse\x12I\n" +
	"\x04List\x12\x1f.workspace.spoke.v1.ListRequest\x1a .workspace.spoke.v1.ListResponseBKZIgithub.com/duizendstra/alexandria/go/contracts/workspace/spoke/v1;spokev1b\x06proto3"

var (
	file_workspace_spoke_v1_spoke_proto_rawDescOnce sync.Once
	file_workspace_spoke_v1_spoke_proto_rawDescData []byte
)

func file_workspace_spoke_v1_spoke_proto_rawDescGZIP() []byte {
	file_workspace_spoke_v1_spoke_proto_rawDescOnce.Do(func() {
		file_workspace_spoke_v1_spoke_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_spoke_v1_spoke_proto_rawDesc), len(file_workspace_spoke_v1_spoke_proto_rawDesc)))
	})
	return file_workspace_spoke_v1_spoke_proto_rawDescData
}

var file_workspace_spoke_v1_spoke_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_workspace_spoke_v1_spoke_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_workspace_spoke_v1_spoke_proto_goTypes = []any{
	(SpokeType)(0),            // 0: workspace.spoke.v1.SpokeType
	(SpokeStatus)(0),          // 1: workspace.spoke.v1.SpokeStatus
	(*Spoke)(nil),             // 2: workspace.spoke.v1.Spoke
	(*RegisterRequest)(nil),   // 3: workspace.spoke.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 4: workspace.spoke.v1.RegisterResponse
	(*HeartbeatRequest)(nil),  // 5: workspace.spoke.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 6: workspace.spoke.v1.HeartbeatResponse
	(*ListRequest)(nil),       // 7: workspace.spoke.v1.ListRequest
	(*ListResponse)(nil),      // 8: workspace.spoke.v1.ListResponse
}
var file_workspace_spoke_v1_spoke_proto_depIdxs = []int32{
	0,  // 0: workspace.spoke.v1.Spoke.type:type_name -> workspace.spoke.v1.SpokeType
	1,  // 1: workspace.spoke.v1.Spoke.status:type_name -> workspace.spoke.v1.SpokeStatus
	0,  // 2: workspace.spoke.v1.RegisterRequest.type:type_name -> workspace.spoke.v1.SpokeType
	1,  // 3: workspace.spoke.v1.HeartbeatRequest.status:type_name -> workspace.spoke.v1.SpokeStatus
	0,  // 4: workspace.spoke.v1.ListRequest.type:type_name -> workspace.spoke.v1.SpokeType
	1,  // 5: workspace.spoke.v1.ListRequest.status:type_name -> workspace.spoke.v1.SpokeStatus
	2,  // 6: workspace.spoke.v1.ListResponse.spokes:type_name -> workspace.spoke.v1.Spoke
	3,  // 7: workspace.spoke.v1.SpokeService.Register:input_type -> workspace.spoke.v1.RegisterRequest
	5,  // 8: workspace.spoke.v1.SpokeService.Heartbeat:input_type -> workspace.spoke.v1.HeartbeatRequest
	7,  // 9: workspace.spoke.v1.SpokeService.List:input_type -> workspace.spoke.v1.ListRequest
	4,  // 10: workspace.spoke.v1.SpokeService.Register:output_type -> workspace.spoke.v1.RegisterResponse
	6,  // 11: workspace.spoke.v1.SpokeService.Heartbeat:output_type -> workspace.spoke.v1.HeartbeatResponse
	8,  // 12: workspace.spoke.v1.SpokeService.List:output_type -> workspace.spoke.v1.ListResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_workspace_spoke_v1_spoke_proto_init() }
func file_workspace_spoke_v1_spoke_proto_init() {
	if File_workspace_spoke_v1_spoke_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_spoke_v1_spoke_proto_rawDesc), len(file_workspace_spoke_v1_spoke_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_spoke_v1_spoke_proto_goTypes,
		DependencyIndexes: file_workspace_spoke_v1_spoke_proto_depIdxs,
		EnumInfos:         file_workspace_spoke_v1_spoke_proto_enumTypes,
		MessageInfos:      file_workspace_spoke_v1_spoke_proto_msgTypes,
	}.Build()
	File_workspace_spoke_v1_spoke_proto = out.File
	file_workspace_spoke_v1_spoke_proto_goTypes = nil
	file_workspace_spoke_v1_spoke_proto_depIdxs = nil
}
