// Copyright 2026 Duizendstra. All rights reserved.
//
// Contact types: reusable across any entity that has contact information.
// Designed for Party but importable by Location, Building, Event, etc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/contact/v1/contact.proto

package contactv1

import (
	v1 "github.com/duizendstra/alexandria/go/contracts/domain/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContactPointType classifies the medium of a contact point.
type ContactPointType int32

const (
	ContactPointType_CONTACT_POINT_TYPE_UNSPECIFIED ContactPointType = 0
	ContactPointType_CONTACT_POINT_TYPE_EMAIL       ContactPointType = 1
	ContactPointType_CONTACT_POINT_TYPE_PHONE       ContactPointType = 2
	ContactPointType_CONTACT_POINT_TYPE_URL         ContactPointType = 3
	ContactPointType_CONTACT_POINT_TYPE_FAX         ContactPointType = 4
)

// Enum value maps for ContactPointType.
var (
	ContactPointType_name = map[int32]string{
		0: "CONTACT_POINT_TYPE_UNSPECIFIED",
		1: "CONTACT_POINT_TYPE_EMAIL",
		2: "CONTACT_POINT_TYPE_PHONE",
		3: "CONTACT_POINT_TYPE_URL",
		4: "CONTACT_POINT_TYPE_FAX",
	}
	ContactPointType_value = map[string]int32{
		"CONTACT_POINT_TYPE_UNSPECIFIED": 0,
		"CONTACT_POINT_TYPE_EMAIL":       1,
		"CONTACT_POINT_TYPE_PHONE":       2,
		"CONTACT_POINT_TYPE_URL":         3,
		"CONTACT_POINT_TYPE_FAX":         4,
	}
)

func (x ContactPointType) Enum() *ContactPointType {
	p := new(ContactPointType)
	*p = x
	return p
}

func (x ContactPointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContactPointType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_contact_v1_contact_proto_enumTypes[0].Descriptor()
}

func (ContactPointType) Type() protoreflect.EnumType {
	return &file_domain_contact_v1_contact_proto_enumTypes[0]
}

func (x ContactPointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContactPointType.Descriptor instead.
func (ContactPointType) EnumDescriptor() ([]byte, []int) {
	return file_domain_contact_v1_contact_proto_rawDescGZIP(), []int{0}
}

// ContactPoint represents a single way to reach an entity.
// Carries its own lifecycle, purpose, and temporal validity.
type ContactPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of contact point (email, phone, URL, etc.).
	Type ContactPointType `protobuf:"varint,1,opt,name=type,proto3,enum=domain.contact.v1.ContactPointType" json:"type,omitempty"`
	// The value (e.g. "jasper@example.com", "+31612345678", "https://example.com").
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Usage context (personal, work, billing, etc.).
	Purpose v1.Purpose `protobuf:"varint,3,opt,name=purpose,proto3,enum=domain.common.v1.Purpose" json:"purpose,omitempty"`
	// Current state of this contact point.
	Lifecycle v1.Lifecycle `protobuf:"varint,4,opt,name=lifecycle,proto3,enum=domain.common.v1.Lifecycle" json:"lifecycle,omitempty"`
	// Source system that provided this data point.
	Source *v1.ExternalId `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// When this contact point became valid.
	ValidFrom *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	// When this contact point stopped being valid. Unset = still valid.
	ValidTo *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	// Human-readable label from the source (e.g. "Mobile", "Main").
	Label         string `protobuf:"bytes,8,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactPoint) Reset() {
	*x = ContactPoint{}
	mi := &file_domain_contact_v1_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactPoint) ProtoMessage() {}

func (x *ContactPoint) ProtoReflect() protoreflect.Message {
	mi := &file_domain_contact_v1_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactPoint.ProtoReflect.Descriptor instead.
func (*ContactPoint) Descriptor() ([]byte, []int) {
	return file_domain_contact_v1_contact_proto_rawDescGZIP(), []int{0}
}

func (x *ContactPoint) GetType() ContactPointType {
	if x != nil {
		return x.Type
	}
	return ContactPointType_CONTACT_POINT_TYPE_UNSPECIFIED
}

func (x *ContactPoint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ContactPoint) GetPurpose() v1.Purpose {
	if x != nil {
		return x.Purpose
	}
	return v1.Purpose(0)
}

func (x *ContactPoint) GetLifecycle() v1.Lifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return v1.Lifecycle(0)
}

func (x *ContactPoint) GetSource() *v1.ExternalId {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ContactPoint) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *ContactPoint) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *ContactPoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// PostalAddress represents a structured physical address.
type PostalAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Street name and house number.
	Street string `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	// City or locality.
	City string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	// State, province, or region.
	Region string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	// Postal or ZIP code.
	PostalCode string `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	// ISO 3166-1 alpha-2 country code (e.g. "NL", "US").
	CountryCode string `protobuf:"bytes,5,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	// Usage context (personal, work, billing, shipping).
	Purpose v1.Purpose `protobuf:"varint,6,opt,name=purpose,proto3,enum=domain.common.v1.Purpose" json:"purpose,omitempty"`
	// Current state of this address.
	Lifecycle v1.Lifecycle `protobuf:"varint,7,opt,name=lifecycle,proto3,enum=domain.common.v1.Lifecycle" json:"lifecycle,omitempty"`
	// Source system that provided this data point.
	Source *v1.ExternalId `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	// When this address became valid.
	ValidFrom *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	// When this address stopped being valid. Unset = still valid.
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostalAddress) Reset() {
	*x = PostalAddress{}
	mi := &file_domain_contact_v1_contact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostalAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostalAddress) ProtoMessage() {}

func (x *PostalAddress) ProtoReflect() protoreflect.Message {
	mi := &file_domain_contact_v1_contact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostalAddress.ProtoReflect.Descriptor instead.
func (*PostalAddress) Descriptor() ([]byte, []int) {
	return file_domain_contact_v1_contact_proto_rawDescGZIP(), []int{1}
}

func (x *PostalAddress) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *PostalAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PostalAddress) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PostalAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *PostalAddress) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *PostalAddress) GetPurpose() v1.Purpose {
	if x != nil {
		return x.Purpose
	}
	return v1.Purpose(0)
}

func (x *PostalAddress) GetLifecycle() v1.Lifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return v1.Lifecycle(0)
}

func (x *PostalAddress) GetSource() *v1.ExternalId {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PostalAddress) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *PostalAddress) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

var File_domain_contact_v1_contact_proto protoreflect.FileDescriptor

const file_domain_contact_v1_contact_proto_rawDesc = "" +
	"\n" +
	"\x1fdomain/contact/v1/contact.proto\x12\x11domain.contact.v1\x1a\x1ddomain/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x03\n" +
	"\fContactPoint\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.domain.contact.v1.ContactPointTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x123\n" +
	"\apurpose\x18\x03 \x01(\x0e2\x19.domain.common.v1.PurposeR\apurpose\x129\n" +
	"\tlifecycle\x18\x04 \x01(\x0e2\x1b.domain.common.v1.LifecycleR\tlifecycle\x124\n" +
	"\x06source\x18\x05 \x01(\v2\x1c.domain.common.v1.ExternalIdR\x06source\x129\n" +
	"\n" +
	"valid_from\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x12\x14\n" +
	"\x05label\x18\b \x01(\tR\x05labelJ\x04\b\t\x10\x14\"\xb5\x03\n" +
	"\rPostalAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x1f\n" +
	"\vpostal_code\x18\x04 \x01(\tR\n" +
	"postalCode\x12!\n" +
	"\fcountry_code\x18\x05 \x01(\tR\vcountryCode\x123\n" +
	"\apurpose\x18\x06 \x01(\x0e2\x19.domain.common.v1.PurposeR\apurpose\x129\n" +
	"\tlifecycle\x18\a \x01(\x0e2\x1b.domain.common.v1.LifecycleR\tlifecycle\x124\n" +
	"\x06source\x18\b \x01(\v2\x1c.domain.common.v1.ExternalIdR\x06source\x129\n" +
	"\n" +
	"valid_from\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\avalidToJ\x04\b\v\x10\x14*\xb0\x01\n" +
	"\x10ContactPointType\x12\"\n" +
	"\x1eCONTACT_POINT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONTACT_POINT_TYPE_EMAIL\x10\x01\x12\x1c\n" +
	"\x18CONTACT_POINT_TYPE_PHONE\x10\x02\x12\x1a\n" +
	"\x16CONTACT_POINT_TYPE_URL\x10\x03\x12\x1a\n" +
	"\x16CONTACT_POINT_TYPE_FAX\x10\x04\"\x04\b\x05\x10\tBLZJgithub.com/duizendstra/alexandria/go/contracts/domain/contact/v1;contactv1b\x06proto3"

var (
	file_domain_contact_v1_contact_proto_rawDescOnce sync.Once
	file_domain_contact_v1_contact_proto_rawDescData []byte
)

func file_domain_contact_v1_contact_proto_rawDescGZIP() []byte {
	file_domain_contact_v1_contact_proto_rawDescOnce.Do(func() {
		file_domain_contact_v1_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_contact_v1_contact_proto_rawDesc), len(file_domain_contact_v1_contact_proto_rawDesc)))
	})
	return file_domain_contact_v1_contact_proto_rawDescData
}

var file_domain_contact_v1_contact_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_contact_v1_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domain_contact_v1_contact_proto_goTypes = []any{
	(ContactPointType)(0),         // 0: domain.contact.v1.ContactPointType
	(*ContactPoint)(nil),          // 1: domain.contact.v1.ContactPoint
	(*PostalAddress)(nil),         // 2: domain.contact.v1.PostalAddress
	(v1.Purpose)(0),               // 3: domain.common.v1.Purpose
	(v1.Lifecycle)(0),             // 4: domain.common.v1.Lifecycle
	(*v1.ExternalId)(nil),         // 5: domain.common.v1.ExternalId
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_domain_contact_v1_contact_proto_depIdxs = []int32{
	0,  // 0: domain.contact.v1.ContactPoint.type:type_name -> domain.contact.v1.ContactPointType
	3,  // 1: domain.contact.v1.ContactPoint.purpose:type_name -> domain.common.v1.Purpose
	4,  // 2: domain.contact.v1.ContactPoint.lifecycle:type_name -> domain.common.v1.Lifecycle
	5,  // 3: domain.contact.v1.ContactPoint.source:type_name -> domain.common.v1.ExternalId
	6,  // 4: domain.contact.v1.ContactPoint.valid_from:type_name -> google.protobuf.Timestamp
	6,  // 5: domain.contact.v1.ContactPoint.valid_to:type_name -> google.protobuf.Timestamp
	3,  // 6: domain.contact.v1.PostalAddress.purpose:type_name -> domain.common.v1.Purpose
	4,  // 7: domain.contact.v1.PostalAddress.lifecycle:type_name -> domain.common.v1.Lifecycle
	5,  // 8: domain.contact.v1.PostalAddress.source:type_name -> domain.common.v1.ExternalId
	6,  // 9: domain.contact.v1.PostalAddress.valid_from:type_name -> google.protobuf.Timestamp
	6,  // 10: domain.contact.v1.PostalAddress.valid_to:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_domain_contact_v1_contact_proto_init() }
func file_domain_contact_v1_contact_proto_init() {
	if File_domain_contact_v1_contact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_contact_v1_contact_proto_rawDesc), len(file_domain_contact_v1_contact_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_contact_v1_contact_proto_goTypes,
		DependencyIndexes: file_domain_contact_v1_contact_proto_depIdxs,
		EnumInfos:         file_domain_contact_v1_contact_proto_enumTypes,
		MessageInfos:      file_domain_contact_v1_contact_proto_msgTypes,
	}.Build()
	File_domain_contact_v1_contact_proto = out.File
	file_domain_contact_v1_contact_proto_goTypes = nil
	file_domain_contact_v1_contact_proto_depIdxs = nil
}
