// Copyright 2026 Duizendstra. All rights reserved.
//
// Sentinel error codes for all API interactions.
// Go package apierr maps these to sentinel error values.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: foundation/errors/v1alpha1/errors.proto

package errorsv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode enumerates every failure mode for vendor and internal API calls.
// Consumers use these codes to decide on retry, backoff, or abort.
type ErrorCode int32

const (
	// Default value — no error.
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// The API rejected the token (HTTP 401).
	ErrorCode_ERROR_CODE_UNAUTHORIZED ErrorCode = 1
	// The token lacks required permissions (HTTP 403).
	ErrorCode_ERROR_CODE_FORBIDDEN ErrorCode = 2
	// The requested resource does not exist (HTTP 404).
	ErrorCode_ERROR_CODE_NOT_FOUND ErrorCode = 3
	// The API throttled the request (HTTP 429).
	ErrorCode_ERROR_CODE_RATE_LIMITED ErrorCode = 4
	// The server returned a 5xx response.
	ErrorCode_ERROR_CODE_SERVER_ERROR ErrorCode = 5
	// Any other non-2xx status.
	ErrorCode_ERROR_CODE_UNEXPECTED_STATUS ErrorCode = 6
	// All retry attempts were exhausted.
	ErrorCode_ERROR_CODE_RETRIES_EXCEEDED ErrorCode = 7
	// Authentication failed (token exchange, refresh, etc.).
	ErrorCode_ERROR_CODE_AUTH_FAILED ErrorCode = 8
	// The vendor API indicated a logical failure in its response envelope
	// (e.g. success=false).
	ErrorCode_ERROR_CODE_API_ERROR ErrorCode = 9
	// Client input validation failed (HTTP 400 / INVALID_ARGUMENT).
	ErrorCode_ERROR_CODE_INVALID_INPUT ErrorCode = 10
	// Request timed out (HTTP 408 / DEADLINE_EXCEEDED).
	ErrorCode_ERROR_CODE_TIMEOUT ErrorCode = 11
	// Resource conflict occurred (HTTP 409 / ALREADY_EXISTS).
	ErrorCode_ERROR_CODE_CONFLICT ErrorCode = 12
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_UNAUTHORIZED",
		2:  "ERROR_CODE_FORBIDDEN",
		3:  "ERROR_CODE_NOT_FOUND",
		4:  "ERROR_CODE_RATE_LIMITED",
		5:  "ERROR_CODE_SERVER_ERROR",
		6:  "ERROR_CODE_UNEXPECTED_STATUS",
		7:  "ERROR_CODE_RETRIES_EXCEEDED",
		8:  "ERROR_CODE_AUTH_FAILED",
		9:  "ERROR_CODE_API_ERROR",
		10: "ERROR_CODE_INVALID_INPUT",
		11: "ERROR_CODE_TIMEOUT",
		12: "ERROR_CODE_CONFLICT",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":       0,
		"ERROR_CODE_UNAUTHORIZED":      1,
		"ERROR_CODE_FORBIDDEN":         2,
		"ERROR_CODE_NOT_FOUND":         3,
		"ERROR_CODE_RATE_LIMITED":      4,
		"ERROR_CODE_SERVER_ERROR":      5,
		"ERROR_CODE_UNEXPECTED_STATUS": 6,
		"ERROR_CODE_RETRIES_EXCEEDED":  7,
		"ERROR_CODE_AUTH_FAILED":       8,
		"ERROR_CODE_API_ERROR":         9,
		"ERROR_CODE_INVALID_INPUT":     10,
		"ERROR_CODE_TIMEOUT":           11,
		"ERROR_CODE_CONFLICT":          12,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_foundation_errors_v1alpha1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_foundation_errors_v1alpha1_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_foundation_errors_v1alpha1_errors_proto_rawDescGZIP(), []int{0}
}

var File_foundation_errors_v1alpha1_errors_proto protoreflect.FileDescriptor

const file_foundation_errors_v1alpha1_errors_proto_rawDesc = "" +
	"\n" +
	"'foundation/errors/v1alpha1/errors.proto\x12\x1afoundation.errors.v1alpha1*\xfa\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_FORBIDDEN\x10\x02\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x03\x12\x1b\n" +
	"\x17ERROR_CODE_RATE_LIMITED\x10\x04\x12\x1b\n" +
	"\x17ERROR_CODE_SERVER_ERROR\x10\x05\x12 \n" +
	"\x1cERROR_CODE_UNEXPECTED_STATUS\x10\x06\x12\x1f\n" +
	"\x1bERROR_CODE_RETRIES_EXCEEDED\x10\a\x12\x1a\n" +
	"\x16ERROR_CODE_AUTH_FAILED\x10\b\x12\x18\n" +
	"\x14ERROR_CODE_API_ERROR\x10\t\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_INPUT\x10\n" +
	"\x12\x16\n" +
	"\x12ERROR_CODE_TIMEOUT\x10\v\x12\x17\n" +
	"\x13ERROR_CODE_CONFLICT\x10\fBZZXgithub.com/duizendstra/alexandria/go/contracts/foundation/errors/v1alpha1;errorsv1alpha1b\x06proto3"

var (
	file_foundation_errors_v1alpha1_errors_proto_rawDescOnce sync.Once
	file_foundation_errors_v1alpha1_errors_proto_rawDescData []byte
)

func file_foundation_errors_v1alpha1_errors_proto_rawDescGZIP() []byte {
	file_foundation_errors_v1alpha1_errors_proto_rawDescOnce.Do(func() {
		file_foundation_errors_v1alpha1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foundation_errors_v1alpha1_errors_proto_rawDesc), len(file_foundation_errors_v1alpha1_errors_proto_rawDesc)))
	})
	return file_foundation_errors_v1alpha1_errors_proto_rawDescData
}

var file_foundation_errors_v1alpha1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_foundation_errors_v1alpha1_errors_proto_goTypes = []any{
	(ErrorCode)(0), // 0: foundation.errors.v1alpha1.ErrorCode
}
var file_foundation_errors_v1alpha1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foundation_errors_v1alpha1_errors_proto_init() }
func file_foundation_errors_v1alpha1_errors_proto_init() {
	if File_foundation_errors_v1alpha1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foundation_errors_v1alpha1_errors_proto_rawDesc), len(file_foundation_errors_v1alpha1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foundation_errors_v1alpha1_errors_proto_goTypes,
		DependencyIndexes: file_foundation_errors_v1alpha1_errors_proto_depIdxs,
		EnumInfos:         file_foundation_errors_v1alpha1_errors_proto_enumTypes,
	}.Build()
	File_foundation_errors_v1alpha1_errors_proto = out.File
	file_foundation_errors_v1alpha1_errors_proto_goTypes = nil
	file_foundation_errors_v1alpha1_errors_proto_depIdxs = nil
}
