// Copyright 2026 Duizendstra. All rights reserved.
//
// Message types for email and communication. Designed for Gmail but
// generic enough for any message-based system (email, chat, notifications).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/message/v1/message.proto

package messagev1

import (
	v1 "github.com/duizendstra/alexandria/go/contracts/domain/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType classifies the kind of message.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED  MessageType = 0
	MessageType_MESSAGE_TYPE_EMAIL        MessageType = 1
	MessageType_MESSAGE_TYPE_CHAT         MessageType = 2
	MessageType_MESSAGE_TYPE_NOTIFICATION MessageType = 3 // 4-9 reserved for future types.
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_EMAIL",
		2: "MESSAGE_TYPE_CHAT",
		3: "MESSAGE_TYPE_NOTIFICATION",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":  0,
		"MESSAGE_TYPE_EMAIL":        1,
		"MESSAGE_TYPE_CHAT":         2,
		"MESSAGE_TYPE_NOTIFICATION": 3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_message_v1_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_domain_message_v1_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_domain_message_v1_message_proto_rawDescGZIP(), []int{0}
}

// DraftStatus tracks the lifecycle of a draft message.
type DraftStatus int32

const (
	DraftStatus_DRAFT_STATUS_UNSPECIFIED DraftStatus = 0
	DraftStatus_DRAFT_STATUS_COMPOSING   DraftStatus = 1 // Being written.
	DraftStatus_DRAFT_STATUS_READY       DraftStatus = 2 // Ready to send.
	DraftStatus_DRAFT_STATUS_SENT        DraftStatus = 3 // Has been sent.
	DraftStatus_DRAFT_STATUS_DISCARDED   DraftStatus = 4 // Abandoned.
)

// Enum value maps for DraftStatus.
var (
	DraftStatus_name = map[int32]string{
		0: "DRAFT_STATUS_UNSPECIFIED",
		1: "DRAFT_STATUS_COMPOSING",
		2: "DRAFT_STATUS_READY",
		3: "DRAFT_STATUS_SENT",
		4: "DRAFT_STATUS_DISCARDED",
	}
	DraftStatus_value = map[string]int32{
		"DRAFT_STATUS_UNSPECIFIED": 0,
		"DRAFT_STATUS_COMPOSING":   1,
		"DRAFT_STATUS_READY":       2,
		"DRAFT_STATUS_SENT":        3,
		"DRAFT_STATUS_DISCARDED":   4,
	}
)

func (x DraftStatus) Enum() *DraftStatus {
	p := new(DraftStatus)
	*p = x
	return p
}

func (x DraftStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DraftStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_message_v1_message_proto_enumTypes[1].Descriptor()
}

func (DraftStatus) Type() protoreflect.EnumType {
	return &file_domain_message_v1_message_proto_enumTypes[1]
}

func (x DraftStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DraftStatus.Descriptor instead.
func (DraftStatus) EnumDescriptor() ([]byte, []int) {
	return file_domain_message_v1_message_proto_rawDescGZIP(), []int{1}
}

// Participant represents a sender or recipient.
type Participant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display name (e.g. "Jasper Duizendstra").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Address (e.g. "jasper@example.com").
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_domain_message_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_domain_message_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_domain_message_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Participant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Participant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Message represents an email or communication message.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source system that provided this message.
	ExternalId *v1.ExternalId `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// Thread/conversation identifier for grouping related messages.
	ThreadId string `protobuf:"bytes,2,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	// The message type (email, chat, notification).
	Type MessageType `protobuf:"varint,3,opt,name=type,proto3,enum=domain.message.v1.MessageType" json:"type,omitempty"`
	// Sender of the message.
	From *Participant `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	// Primary recipients.
	To []*Participant `protobuf:"bytes,5,rep,name=to,proto3" json:"to,omitempty"`
	// Carbon-copy recipients.
	Cc []*Participant `protobuf:"bytes,6,rep,name=cc,proto3" json:"cc,omitempty"`
	// Blind carbon-copy recipients.
	Bcc []*Participant `protobuf:"bytes,7,rep,name=bcc,proto3" json:"bcc,omitempty"`
	// Subject line.
	Subject string `protobuf:"bytes,8,opt,name=subject,proto3" json:"subject,omitempty"`
	// Plain text body.
	BodyText string `protobuf:"bytes,9,opt,name=body_text,json=bodyText,proto3" json:"body_text,omitempty"`
	// HTML body (if available).
	BodyHtml string `protobuf:"bytes,10,opt,name=body_html,json=bodyHtml,proto3" json:"body_html,omitempty"`
	// Labels or categories (e.g. "INBOX", "SENT", "IMPORTANT").
	Labels []string `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty"`
	// When the message was received/sent.
	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// Message snippet (short preview of the body).
	Snippet string `protobuf:"bytes,13,opt,name=snippet,proto3" json:"snippet,omitempty"`
	// Whether the message has been read.
	IsRead        bool `protobuf:"varint,14,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_domain_message_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_domain_message_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_domain_message_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetExternalId() *v1.ExternalId {
	if x != nil {
		return x.ExternalId
	}
	return nil
}

func (x *Message) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *Message) GetFrom() *Participant {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Message) GetTo() []*Participant {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Message) GetCc() []*Participant {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *Message) GetBcc() []*Participant {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *Message) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Message) GetBodyText() string {
	if x != nil {
		return x.BodyText
	}
	return ""
}

func (x *Message) GetBodyHtml() string {
	if x != nil {
		return x.BodyHtml
	}
	return ""
}

func (x *Message) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Message) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *Message) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *Message) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

// Draft represents a message being composed.
type Draft struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source system identifier for the draft.
	ExternalId *v1.ExternalId `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// The draft message content.
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Current status of the draft.
	Status DraftStatus `protobuf:"varint,3,opt,name=status,proto3,enum=domain.message.v1.DraftStatus" json:"status,omitempty"`
	// When the draft was last modified.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Draft) Reset() {
	*x = Draft{}
	mi := &file_domain_message_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Draft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Draft) ProtoMessage() {}

func (x *Draft) ProtoReflect() protoreflect.Message {
	mi := &file_domain_message_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Draft.ProtoReflect.Descriptor instead.
func (*Draft) Descriptor() ([]byte, []int) {
	return file_domain_message_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *Draft) GetExternalId() *v1.ExternalId {
	if x != nil {
		return x.ExternalId
	}
	return nil
}

func (x *Draft) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Draft) GetStatus() DraftStatus {
	if x != nil {
		return x.Status
	}
	return DraftStatus_DRAFT_STATUS_UNSPECIFIED
}

func (x *Draft) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_domain_message_v1_message_proto protoreflect.FileDescriptor

const file_domain_message_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1fdomain/message/v1/message.proto\x12\x11domain.message.v1\x1a\x1ddomain/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\vParticipant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xbb\x04\n" +
	"\aMessage\x12=\n" +
	"\vexternal_id\x18\x01 \x01(\v2\x1c.domain.common.v1.ExternalIdR\n" +
	"externalId\x12\x1b\n" +
	"\tthread_id\x18\x02 \x01(\tR\bthreadId\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.domain.message.v1.MessageTypeR\x04type\x122\n" +
	"\x04from\x18\x04 \x01(\v2\x1e.domain.message.v1.ParticipantR\x04from\x12.\n" +
	"\x02to\x18\x05 \x03(\v2\x1e.domain.message.v1.ParticipantR\x02to\x12.\n" +
	"\x02cc\x18\x06 \x03(\v2\x1e.domain.message.v1.ParticipantR\x02cc\x120\n" +
	"\x03bcc\x18\a \x03(\v2\x1e.domain.message.v1.ParticipantR\x03bcc\x12\x18\n" +
	"\asubject\x18\b \x01(\tR\asubject\x12\x1b\n" +
	"\tbody_text\x18\t \x01(\tR\bbodyText\x12\x1b\n" +
	"\tbody_html\x18\n" +
	" \x01(\tR\bbodyHtml\x12\x16\n" +
	"\x06labels\x18\v \x03(\tR\x06labels\x12;\n" +
	"\vreceived_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12\x18\n" +
	"\asnippet\x18\r \x01(\tR\asnippet\x12\x17\n" +
	"\ais_read\x18\x0e \x01(\bR\x06isRead\"\xef\x01\n" +
	"\x05Draft\x12=\n" +
	"\vexternal_id\x18\x01 \x01(\v2\x1c.domain.common.v1.ExternalIdR\n" +
	"externalId\x124\n" +
	"\amessage\x18\x02 \x01(\v2\x1a.domain.message.v1.MessageR\amessage\x126\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1e.domain.message.v1.DraftStatusR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*y\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MESSAGE_TYPE_EMAIL\x10\x01\x12\x15\n" +
	"\x11MESSAGE_TYPE_CHAT\x10\x02\x12\x1d\n" +
	"\x19MESSAGE_TYPE_NOTIFICATION\x10\x03*\x92\x01\n" +
	"\vDraftStatus\x12\x1c\n" +
	"\x18DRAFT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DRAFT_STATUS_COMPOSING\x10\x01\x12\x16\n" +
	"\x12DRAFT_STATUS_READY\x10\x02\x12\x15\n" +
	"\x11DRAFT_STATUS_SENT\x10\x03\x12\x1a\n" +
	"\x16DRAFT_STATUS_DISCARDED\x10\x04BLZJgithub.com/duizendstra/alexandria/go/contracts/domain/message/v1;messagev1b\x06proto3"

var (
	file_domain_message_v1_message_proto_rawDescOnce sync.Once
	file_domain_message_v1_message_proto_rawDescData []byte
)

func file_domain_message_v1_message_proto_rawDescGZIP() []byte {
	file_domain_message_v1_message_proto_rawDescOnce.Do(func() {
		file_domain_message_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_message_v1_message_proto_rawDesc), len(file_domain_message_v1_message_proto_rawDesc)))
	})
	return file_domain_message_v1_message_proto_rawDescData
}

var file_domain_message_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_domain_message_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_domain_message_v1_message_proto_goTypes = []any{
	(MessageType)(0),              // 0: domain.message.v1.MessageType
	(DraftStatus)(0),              // 1: domain.message.v1.DraftStatus
	(*Participant)(nil),           // 2: domain.message.v1.Participant
	(*Message)(nil),               // 3: domain.message.v1.Message
	(*Draft)(nil),                 // 4: domain.message.v1.Draft
	(*v1.ExternalId)(nil),         // 5: domain.common.v1.ExternalId
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_domain_message_v1_message_proto_depIdxs = []int32{
	5,  // 0: domain.message.v1.Message.external_id:type_name -> domain.common.v1.ExternalId
	0,  // 1: domain.message.v1.Message.type:type_name -> domain.message.v1.MessageType
	2,  // 2: domain.message.v1.Message.from:type_name -> domain.message.v1.Participant
	2,  // 3: domain.message.v1.Message.to:type_name -> domain.message.v1.Participant
	2,  // 4: domain.message.v1.Message.cc:type_name -> domain.message.v1.Participant
	2,  // 5: domain.message.v1.Message.bcc:type_name -> domain.message.v1.Participant
	6,  // 6: domain.message.v1.Message.received_at:type_name -> google.protobuf.Timestamp
	5,  // 7: domain.message.v1.Draft.external_id:type_name -> domain.common.v1.ExternalId
	3,  // 8: domain.message.v1.Draft.message:type_name -> domain.message.v1.Message
	1,  // 9: domain.message.v1.Draft.status:type_name -> domain.message.v1.DraftStatus
	6,  // 10: domain.message.v1.Draft.updated_at:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_domain_message_v1_message_proto_init() }
func file_domain_message_v1_message_proto_init() {
	if File_domain_message_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_message_v1_message_proto_rawDesc), len(file_domain_message_v1_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_message_v1_message_proto_goTypes,
		DependencyIndexes: file_domain_message_v1_message_proto_depIdxs,
		EnumInfos:         file_domain_message_v1_message_proto_enumTypes,
		MessageInfos:      file_domain_message_v1_message_proto_msgTypes,
	}.Build()
	File_domain_message_v1_message_proto = out.File
	file_domain_message_v1_message_proto_goTypes = nil
	file_domain_message_v1_message_proto_depIdxs = nil
}
