// Copyright 2026 Duizendstra. All rights reserved.
//
// Service health observability — reports the running state of services
// across all deployment scopes (local, cloud).
//
// Domain:  Deployment
// Concern: What is the health state of services?

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: deployment/status/v1/status.proto

package statusv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/duizendstra/alexandria/go/contracts/deployment/status/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StatusServiceName is the fully-qualified name of the StatusService service.
	StatusServiceName = "deployment.status.v1.StatusService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StatusServiceCheckHealthProcedure is the fully-qualified name of the StatusService's CheckHealth
	// RPC.
	StatusServiceCheckHealthProcedure = "/deployment.status.v1.StatusService/CheckHealth"
)

// StatusServiceClient is a client for the deployment.status.v1.StatusService service.
type StatusServiceClient interface {
	// CheckHealth returns the health of all registered services.
	CheckHealth(context.Context, *connect.Request[v1.CheckHealthRequest]) (*connect.Response[v1.CheckHealthResponse], error)
}

// NewStatusServiceClient constructs a client for the deployment.status.v1.StatusService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStatusServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StatusServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	statusServiceMethods := v1.File_deployment_status_v1_status_proto.Services().ByName("StatusService").Methods()
	return &statusServiceClient{
		checkHealth: connect.NewClient[v1.CheckHealthRequest, v1.CheckHealthResponse](
			httpClient,
			baseURL+StatusServiceCheckHealthProcedure,
			connect.WithSchema(statusServiceMethods.ByName("CheckHealth")),
			connect.WithClientOptions(opts...),
		),
	}
}

// statusServiceClient implements StatusServiceClient.
type statusServiceClient struct {
	checkHealth *connect.Client[v1.CheckHealthRequest, v1.CheckHealthResponse]
}

// CheckHealth calls deployment.status.v1.StatusService.CheckHealth.
func (c *statusServiceClient) CheckHealth(ctx context.Context, req *connect.Request[v1.CheckHealthRequest]) (*connect.Response[v1.CheckHealthResponse], error) {
	return c.checkHealth.CallUnary(ctx, req)
}

// StatusServiceHandler is an implementation of the deployment.status.v1.StatusService service.
type StatusServiceHandler interface {
	// CheckHealth returns the health of all registered services.
	CheckHealth(context.Context, *connect.Request[v1.CheckHealthRequest]) (*connect.Response[v1.CheckHealthResponse], error)
}

// NewStatusServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStatusServiceHandler(svc StatusServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	statusServiceMethods := v1.File_deployment_status_v1_status_proto.Services().ByName("StatusService").Methods()
	statusServiceCheckHealthHandler := connect.NewUnaryHandler(
		StatusServiceCheckHealthProcedure,
		svc.CheckHealth,
		connect.WithSchema(statusServiceMethods.ByName("CheckHealth")),
		connect.WithHandlerOptions(opts...),
	)
	return "/deployment.status.v1.StatusService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StatusServiceCheckHealthProcedure:
			statusServiceCheckHealthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStatusServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStatusServiceHandler struct{}

func (UnimplementedStatusServiceHandler) CheckHealth(context.Context, *connect.Request[v1.CheckHealthRequest]) (*connect.Response[v1.CheckHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("deployment.status.v1.StatusService.CheckHealth is not implemented"))
}
