// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: intelligence/reasoning/v1alpha1/reasoning.proto

// Package reasoning defines the intelligence layer's planning capability.
//
// Hexagonal: inbound port — consumed by MCP tools (Nous) and services (Kratos).
// CODE phase: Distill — transforms intent + context into actionable plans.
// PARA: Resources — a reusable reasoning capability.
//
// The ReasoningService generates multi-step action plans by combining
// user intent with available context (from MemoryService) and capabilities
// (from SkillsService). It is the "thinking" layer of the second brain.

package reasoningv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action represents a single step in a reasoning plan.
type Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The skill to invoke (e.g. "skills/retrieve-memory").
	Skill string `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	// Human-readable description of what this step achieves.
	Rationale string `protobuf:"bytes,2,opt,name=rationale,proto3" json:"rationale,omitempty"`
	// Input parameters as a JSON string.
	InputJson     string `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_intelligence_reasoning_v1alpha1_reasoning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_reasoning_v1alpha1_reasoning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *Action) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *Action) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

// PlanResponseRequest is the request message for
// [ReasoningService.PlanResponse][intelligence.reasoning.v1alpha1.ReasoningService.PlanResponse].
type PlanResponseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. What the user wants to achieve.
	Intent string `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	// Optional. Context retrieved from MemoryService or other sources.
	Context       string `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponseRequest) Reset() {
	*x = PlanResponseRequest{}
	mi := &file_intelligence_reasoning_v1alpha1_reasoning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponseRequest) ProtoMessage() {}

func (x *PlanResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_reasoning_v1alpha1_reasoning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponseRequest.ProtoReflect.Descriptor instead.
func (*PlanResponseRequest) Descriptor() ([]byte, []int) {
	return file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDescGZIP(), []int{1}
}

func (x *PlanResponseRequest) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *PlanResponseRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

// PlanResponseResponse is the response message for
// [ReasoningService.PlanResponse][intelligence.reasoning.v1alpha1.ReasoningService.PlanResponse].
type PlanResponseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Explanation of the reasoning behind the plan.
	ThoughtProcess string `protobuf:"bytes,1,opt,name=thought_process,json=thoughtProcess,proto3" json:"thought_process,omitempty"`
	// Ordered list of actions to execute.
	Actions       []*Action `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanResponseResponse) Reset() {
	*x = PlanResponseResponse{}
	mi := &file_intelligence_reasoning_v1alpha1_reasoning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanResponseResponse) ProtoMessage() {}

func (x *PlanResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_reasoning_v1alpha1_reasoning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanResponseResponse.ProtoReflect.Descriptor instead.
func (*PlanResponseResponse) Descriptor() ([]byte, []int) {
	return file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDescGZIP(), []int{2}
}

func (x *PlanResponseResponse) GetThoughtProcess() string {
	if x != nil {
		return x.ThoughtProcess
	}
	return ""
}

func (x *PlanResponseResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

var File_intelligence_reasoning_v1alpha1_reasoning_proto protoreflect.FileDescriptor

const file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDesc = "" +
	"\n" +
	"/intelligence/reasoning/v1alpha1/reasoning.proto\x12\x1fintelligence.reasoning.v1alpha1\"[\n" +
	"\x06Action\x12\x14\n" +
	"\x05skill\x18\x01 \x01(\tR\x05skill\x12\x1c\n" +
	"\trationale\x18\x02 \x01(\tR\trationale\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\tR\tinputJson\"G\n" +
	"\x13PlanResponseRequest\x12\x16\n" +
	"\x06intent\x18\x01 \x01(\tR\x06intent\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\"\x82\x01\n" +
	"\x14PlanResponseResponse\x12'\n" +
	"\x0fthought_process\x18\x01 \x01(\tR\x0ethoughtProcess\x12A\n" +
	"\aactions\x18\x02 \x03(\v2'.intelligence.reasoning.v1alpha1.ActionR\aactions2\x8f\x01\n" +
	"\x10ReasoningService\x12{\n" +
	"\fPlanResponse\x124.intelligence.reasoning.v1alpha1.PlanResponseRequest\x1a5.intelligence.reasoning.v1alpha1.PlanResponseResponseBbZ`github.com/duizendstra/alexandria/go/contracts/intelligence/reasoning/v1alpha1;reasoningv1alpha1b\x06proto3"

var (
	file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDescOnce sync.Once
	file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDescData []byte
)

func file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDescGZIP() []byte {
	file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDescOnce.Do(func() {
		file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDesc), len(file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDesc)))
	})
	return file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDescData
}

var file_intelligence_reasoning_v1alpha1_reasoning_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_intelligence_reasoning_v1alpha1_reasoning_proto_goTypes = []any{
	(*Action)(nil),               // 0: intelligence.reasoning.v1alpha1.Action
	(*PlanResponseRequest)(nil),  // 1: intelligence.reasoning.v1alpha1.PlanResponseRequest
	(*PlanResponseResponse)(nil), // 2: intelligence.reasoning.v1alpha1.PlanResponseResponse
}
var file_intelligence_reasoning_v1alpha1_reasoning_proto_depIdxs = []int32{
	0, // 0: intelligence.reasoning.v1alpha1.PlanResponseResponse.actions:type_name -> intelligence.reasoning.v1alpha1.Action
	1, // 1: intelligence.reasoning.v1alpha1.ReasoningService.PlanResponse:input_type -> intelligence.reasoning.v1alpha1.PlanResponseRequest
	2, // 2: intelligence.reasoning.v1alpha1.ReasoningService.PlanResponse:output_type -> intelligence.reasoning.v1alpha1.PlanResponseResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_intelligence_reasoning_v1alpha1_reasoning_proto_init() }
func file_intelligence_reasoning_v1alpha1_reasoning_proto_init() {
	if File_intelligence_reasoning_v1alpha1_reasoning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDesc), len(file_intelligence_reasoning_v1alpha1_reasoning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intelligence_reasoning_v1alpha1_reasoning_proto_goTypes,
		DependencyIndexes: file_intelligence_reasoning_v1alpha1_reasoning_proto_depIdxs,
		MessageInfos:      file_intelligence_reasoning_v1alpha1_reasoning_proto_msgTypes,
	}.Build()
	File_intelligence_reasoning_v1alpha1_reasoning_proto = out.File
	file_intelligence_reasoning_v1alpha1_reasoning_proto_goTypes = nil
	file_intelligence_reasoning_v1alpha1_reasoning_proto_depIdxs = nil
}
