// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: collaboration/ideas/v1/ideas.proto

package ideasv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/duizendstra/alexandria/go/contracts/collaboration/ideas/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IdeasServiceName is the fully-qualified name of the IdeasService service.
	IdeasServiceName = "collaboration.ideas.v1.IdeasService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IdeasServiceCreateIdeaProcedure is the fully-qualified name of the IdeasService's CreateIdea RPC.
	IdeasServiceCreateIdeaProcedure = "/collaboration.ideas.v1.IdeasService/CreateIdea"
	// IdeasServiceGetIdeaProcedure is the fully-qualified name of the IdeasService's GetIdea RPC.
	IdeasServiceGetIdeaProcedure = "/collaboration.ideas.v1.IdeasService/GetIdea"
	// IdeasServiceListIdeasProcedure is the fully-qualified name of the IdeasService's ListIdeas RPC.
	IdeasServiceListIdeasProcedure = "/collaboration.ideas.v1.IdeasService/ListIdeas"
	// IdeasServiceUpdateIdeaProcedure is the fully-qualified name of the IdeasService's UpdateIdea RPC.
	IdeasServiceUpdateIdeaProcedure = "/collaboration.ideas.v1.IdeasService/UpdateIdea"
	// IdeasServiceDeleteIdeaProcedure is the fully-qualified name of the IdeasService's DeleteIdea RPC.
	IdeasServiceDeleteIdeaProcedure = "/collaboration.ideas.v1.IdeasService/DeleteIdea"
)

// IdeasServiceClient is a client for the collaboration.ideas.v1.IdeasService service.
type IdeasServiceClient interface {
	// CreateIdea captures a new idea (AIP-133).
	CreateIdea(context.Context, *connect.Request[v1.CreateIdeaRequest]) (*connect.Response[v1.CreateIdeaResponse], error)
	// GetIdea retrieves an idea by resource name (AIP-131).
	GetIdea(context.Context, *connect.Request[v1.GetIdeaRequest]) (*connect.Response[v1.GetIdeaResponse], error)
	// ListIdeas returns ideas with optional filtering and pagination (AIP-132).
	ListIdeas(context.Context, *connect.Request[v1.ListIdeasRequest]) (*connect.Response[v1.ListIdeasResponse], error)
	// UpdateIdea modifies an existing idea's text or status (AIP-134).
	UpdateIdea(context.Context, *connect.Request[v1.UpdateIdeaRequest]) (*connect.Response[v1.UpdateIdeaResponse], error)
	// DeleteIdea permanently removes an idea (AIP-135).
	DeleteIdea(context.Context, *connect.Request[v1.DeleteIdeaRequest]) (*connect.Response[v1.DeleteIdeaResponse], error)
}

// NewIdeasServiceClient constructs a client for the collaboration.ideas.v1.IdeasService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIdeasServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IdeasServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	ideasServiceMethods := v1.File_collaboration_ideas_v1_ideas_proto.Services().ByName("IdeasService").Methods()
	return &ideasServiceClient{
		createIdea: connect.NewClient[v1.CreateIdeaRequest, v1.CreateIdeaResponse](
			httpClient,
			baseURL+IdeasServiceCreateIdeaProcedure,
			connect.WithSchema(ideasServiceMethods.ByName("CreateIdea")),
			connect.WithClientOptions(opts...),
		),
		getIdea: connect.NewClient[v1.GetIdeaRequest, v1.GetIdeaResponse](
			httpClient,
			baseURL+IdeasServiceGetIdeaProcedure,
			connect.WithSchema(ideasServiceMethods.ByName("GetIdea")),
			connect.WithClientOptions(opts...),
		),
		listIdeas: connect.NewClient[v1.ListIdeasRequest, v1.ListIdeasResponse](
			httpClient,
			baseURL+IdeasServiceListIdeasProcedure,
			connect.WithSchema(ideasServiceMethods.ByName("ListIdeas")),
			connect.WithClientOptions(opts...),
		),
		updateIdea: connect.NewClient[v1.UpdateIdeaRequest, v1.UpdateIdeaResponse](
			httpClient,
			baseURL+IdeasServiceUpdateIdeaProcedure,
			connect.WithSchema(ideasServiceMethods.ByName("UpdateIdea")),
			connect.WithClientOptions(opts...),
		),
		deleteIdea: connect.NewClient[v1.DeleteIdeaRequest, v1.DeleteIdeaResponse](
			httpClient,
			baseURL+IdeasServiceDeleteIdeaProcedure,
			connect.WithSchema(ideasServiceMethods.ByName("DeleteIdea")),
			connect.WithClientOptions(opts...),
		),
	}
}

// ideasServiceClient implements IdeasServiceClient.
type ideasServiceClient struct {
	createIdea *connect.Client[v1.CreateIdeaRequest, v1.CreateIdeaResponse]
	getIdea    *connect.Client[v1.GetIdeaRequest, v1.GetIdeaResponse]
	listIdeas  *connect.Client[v1.ListIdeasRequest, v1.ListIdeasResponse]
	updateIdea *connect.Client[v1.UpdateIdeaRequest, v1.UpdateIdeaResponse]
	deleteIdea *connect.Client[v1.DeleteIdeaRequest, v1.DeleteIdeaResponse]
}

// CreateIdea calls collaboration.ideas.v1.IdeasService.CreateIdea.
func (c *ideasServiceClient) CreateIdea(ctx context.Context, req *connect.Request[v1.CreateIdeaRequest]) (*connect.Response[v1.CreateIdeaResponse], error) {
	return c.createIdea.CallUnary(ctx, req)
}

// GetIdea calls collaboration.ideas.v1.IdeasService.GetIdea.
func (c *ideasServiceClient) GetIdea(ctx context.Context, req *connect.Request[v1.GetIdeaRequest]) (*connect.Response[v1.GetIdeaResponse], error) {
	return c.getIdea.CallUnary(ctx, req)
}

// ListIdeas calls collaboration.ideas.v1.IdeasService.ListIdeas.
func (c *ideasServiceClient) ListIdeas(ctx context.Context, req *connect.Request[v1.ListIdeasRequest]) (*connect.Response[v1.ListIdeasResponse], error) {
	return c.listIdeas.CallUnary(ctx, req)
}

// UpdateIdea calls collaboration.ideas.v1.IdeasService.UpdateIdea.
func (c *ideasServiceClient) UpdateIdea(ctx context.Context, req *connect.Request[v1.UpdateIdeaRequest]) (*connect.Response[v1.UpdateIdeaResponse], error) {
	return c.updateIdea.CallUnary(ctx, req)
}

// DeleteIdea calls collaboration.ideas.v1.IdeasService.DeleteIdea.
func (c *ideasServiceClient) DeleteIdea(ctx context.Context, req *connect.Request[v1.DeleteIdeaRequest]) (*connect.Response[v1.DeleteIdeaResponse], error) {
	return c.deleteIdea.CallUnary(ctx, req)
}

// IdeasServiceHandler is an implementation of the collaboration.ideas.v1.IdeasService service.
type IdeasServiceHandler interface {
	// CreateIdea captures a new idea (AIP-133).
	CreateIdea(context.Context, *connect.Request[v1.CreateIdeaRequest]) (*connect.Response[v1.CreateIdeaResponse], error)
	// GetIdea retrieves an idea by resource name (AIP-131).
	GetIdea(context.Context, *connect.Request[v1.GetIdeaRequest]) (*connect.Response[v1.GetIdeaResponse], error)
	// ListIdeas returns ideas with optional filtering and pagination (AIP-132).
	ListIdeas(context.Context, *connect.Request[v1.ListIdeasRequest]) (*connect.Response[v1.ListIdeasResponse], error)
	// UpdateIdea modifies an existing idea's text or status (AIP-134).
	UpdateIdea(context.Context, *connect.Request[v1.UpdateIdeaRequest]) (*connect.Response[v1.UpdateIdeaResponse], error)
	// DeleteIdea permanently removes an idea (AIP-135).
	DeleteIdea(context.Context, *connect.Request[v1.DeleteIdeaRequest]) (*connect.Response[v1.DeleteIdeaResponse], error)
}

// NewIdeasServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIdeasServiceHandler(svc IdeasServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ideasServiceMethods := v1.File_collaboration_ideas_v1_ideas_proto.Services().ByName("IdeasService").Methods()
	ideasServiceCreateIdeaHandler := connect.NewUnaryHandler(
		IdeasServiceCreateIdeaProcedure,
		svc.CreateIdea,
		connect.WithSchema(ideasServiceMethods.ByName("CreateIdea")),
		connect.WithHandlerOptions(opts...),
	)
	ideasServiceGetIdeaHandler := connect.NewUnaryHandler(
		IdeasServiceGetIdeaProcedure,
		svc.GetIdea,
		connect.WithSchema(ideasServiceMethods.ByName("GetIdea")),
		connect.WithHandlerOptions(opts...),
	)
	ideasServiceListIdeasHandler := connect.NewUnaryHandler(
		IdeasServiceListIdeasProcedure,
		svc.ListIdeas,
		connect.WithSchema(ideasServiceMethods.ByName("ListIdeas")),
		connect.WithHandlerOptions(opts...),
	)
	ideasServiceUpdateIdeaHandler := connect.NewUnaryHandler(
		IdeasServiceUpdateIdeaProcedure,
		svc.UpdateIdea,
		connect.WithSchema(ideasServiceMethods.ByName("UpdateIdea")),
		connect.WithHandlerOptions(opts...),
	)
	ideasServiceDeleteIdeaHandler := connect.NewUnaryHandler(
		IdeasServiceDeleteIdeaProcedure,
		svc.DeleteIdea,
		connect.WithSchema(ideasServiceMethods.ByName("DeleteIdea")),
		connect.WithHandlerOptions(opts...),
	)
	return "/collaboration.ideas.v1.IdeasService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IdeasServiceCreateIdeaProcedure:
			ideasServiceCreateIdeaHandler.ServeHTTP(w, r)
		case IdeasServiceGetIdeaProcedure:
			ideasServiceGetIdeaHandler.ServeHTTP(w, r)
		case IdeasServiceListIdeasProcedure:
			ideasServiceListIdeasHandler.ServeHTTP(w, r)
		case IdeasServiceUpdateIdeaProcedure:
			ideasServiceUpdateIdeaHandler.ServeHTTP(w, r)
		case IdeasServiceDeleteIdeaProcedure:
			ideasServiceDeleteIdeaHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIdeasServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIdeasServiceHandler struct{}

func (UnimplementedIdeasServiceHandler) CreateIdea(context.Context, *connect.Request[v1.CreateIdeaRequest]) (*connect.Response[v1.CreateIdeaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("collaboration.ideas.v1.IdeasService.CreateIdea is not implemented"))
}

func (UnimplementedIdeasServiceHandler) GetIdea(context.Context, *connect.Request[v1.GetIdeaRequest]) (*connect.Response[v1.GetIdeaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("collaboration.ideas.v1.IdeasService.GetIdea is not implemented"))
}

func (UnimplementedIdeasServiceHandler) ListIdeas(context.Context, *connect.Request[v1.ListIdeasRequest]) (*connect.Response[v1.ListIdeasResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("collaboration.ideas.v1.IdeasService.ListIdeas is not implemented"))
}

func (UnimplementedIdeasServiceHandler) UpdateIdea(context.Context, *connect.Request[v1.UpdateIdeaRequest]) (*connect.Response[v1.UpdateIdeaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("collaboration.ideas.v1.IdeasService.UpdateIdea is not implemented"))
}

func (UnimplementedIdeasServiceHandler) DeleteIdea(context.Context, *connect.Request[v1.DeleteIdeaRequest]) (*connect.Response[v1.DeleteIdeaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("collaboration.ideas.v1.IdeasService.DeleteIdea is not implemented"))
}
