// Copyright 2026 Duizendstra. All rights reserved.
//
// Role types for Party entities. A Party can play multiple roles
// simultaneously across different contexts.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: domain/role/v1/role.proto

package rolev1

import (
	v1 "github.com/duizendstra/alexandria/go/contracts/domain/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RoleType classifies the function a Party serves in a context.
type RoleType int32

const (
	RoleType_ROLE_TYPE_UNSPECIFIED RoleType = 0
	RoleType_ROLE_TYPE_CONTACT     RoleType = 1 // Personal/business contact.
	RoleType_ROLE_TYPE_EMPLOYEE    RoleType = 2 // Employee of an organization.
	RoleType_ROLE_TYPE_SUPPLIER    RoleType = 3 // Supplies goods or services.
	RoleType_ROLE_TYPE_CUSTOMER    RoleType = 4 // Purchases goods or services.
	RoleType_ROLE_TYPE_DEBTOR      RoleType = 5 // Owes money (accounts receivable).
	RoleType_ROLE_TYPE_CREDITOR    RoleType = 6 // Is owed money (accounts payable).
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "ROLE_TYPE_UNSPECIFIED",
		1: "ROLE_TYPE_CONTACT",
		2: "ROLE_TYPE_EMPLOYEE",
		3: "ROLE_TYPE_SUPPLIER",
		4: "ROLE_TYPE_CUSTOMER",
		5: "ROLE_TYPE_DEBTOR",
		6: "ROLE_TYPE_CREDITOR",
	}
	RoleType_value = map[string]int32{
		"ROLE_TYPE_UNSPECIFIED": 0,
		"ROLE_TYPE_CONTACT":     1,
		"ROLE_TYPE_EMPLOYEE":    2,
		"ROLE_TYPE_SUPPLIER":    3,
		"ROLE_TYPE_CUSTOMER":    4,
		"ROLE_TYPE_DEBTOR":      5,
		"ROLE_TYPE_CREDITOR":    6,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_role_v1_role_proto_enumTypes[0].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_domain_role_v1_role_proto_enumTypes[0]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_domain_role_v1_role_proto_rawDescGZIP(), []int{0}
}

// Role describes what function a Party plays in a given context.
// A single Party can have multiple roles (e.g. both SUPPLIER and CUSTOMER).
type Role struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of role.
	Type RoleType `protobuf:"varint,1,opt,name=type,proto3,enum=domain.role.v1.RoleType" json:"type,omitempty"`
	// Current state of this role assignment.
	Lifecycle v1.Lifecycle `protobuf:"varint,2,opt,name=lifecycle,proto3,enum=domain.common.v1.Lifecycle" json:"lifecycle,omitempty"`
	// Source system that assigned this role.
	Source *v1.ExternalId `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// When this role became active.
	ValidFrom *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	// When this role ended. Unset = still active.
	ValidTo *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	// Job title or role name (e.g. "Software Engineer", "Account Manager").
	Title string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	// Organization the party holds this role at.
	OrganizationName string `protobuf:"bytes,7,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	// Free-text description of responsibilities or context.
	Description   string `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_domain_role_v1_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_domain_role_v1_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_domain_role_v1_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetType() RoleType {
	if x != nil {
		return x.Type
	}
	return RoleType_ROLE_TYPE_UNSPECIFIED
}

func (x *Role) GetLifecycle() v1.Lifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return v1.Lifecycle(0)
}

func (x *Role) GetSource() *v1.ExternalId {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Role) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *Role) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *Role) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Role) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_domain_role_v1_role_proto protoreflect.FileDescriptor

const file_domain_role_v1_role_proto_rawDesc = "" +
	"\n" +
	"\x19domain/role/v1/role.proto\x12\x0edomain.role.v1\x1a\x1ddomain/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x02\n" +
	"\x04Role\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.domain.role.v1.RoleTypeR\x04type\x129\n" +
	"\tlifecycle\x18\x02 \x01(\x0e2\x1b.domain.common.v1.LifecycleR\tlifecycle\x124\n" +
	"\x06source\x18\x03 \x01(\v2\x1c.domain.common.v1.ExternalIdR\x06source\x129\n" +
	"\n" +
	"valid_from\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12+\n" +
	"\x11organization_name\x18\a \x01(\tR\x10organizationName\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription*\xb2\x01\n" +
	"\bRoleType\x12\x19\n" +
	"\x15ROLE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ROLE_TYPE_CONTACT\x10\x01\x12\x16\n" +
	"\x12ROLE_TYPE_EMPLOYEE\x10\x02\x12\x16\n" +
	"\x12ROLE_TYPE_SUPPLIER\x10\x03\x12\x16\n" +
	"\x12ROLE_TYPE_CUSTOMER\x10\x04\x12\x14\n" +
	"\x10ROLE_TYPE_DEBTOR\x10\x05\x12\x16\n" +
	"\x12ROLE_TYPE_CREDITOR\x10\x06BFZDgithub.com/duizendstra/alexandria/go/contracts/domain/role/v1;rolev1b\x06proto3"

var (
	file_domain_role_v1_role_proto_rawDescOnce sync.Once
	file_domain_role_v1_role_proto_rawDescData []byte
)

func file_domain_role_v1_role_proto_rawDescGZIP() []byte {
	file_domain_role_v1_role_proto_rawDescOnce.Do(func() {
		file_domain_role_v1_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_role_v1_role_proto_rawDesc), len(file_domain_role_v1_role_proto_rawDesc)))
	})
	return file_domain_role_v1_role_proto_rawDescData
}

var file_domain_role_v1_role_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_role_v1_role_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_domain_role_v1_role_proto_goTypes = []any{
	(RoleType)(0),                 // 0: domain.role.v1.RoleType
	(*Role)(nil),                  // 1: domain.role.v1.Role
	(v1.Lifecycle)(0),             // 2: domain.common.v1.Lifecycle
	(*v1.ExternalId)(nil),         // 3: domain.common.v1.ExternalId
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_domain_role_v1_role_proto_depIdxs = []int32{
	0, // 0: domain.role.v1.Role.type:type_name -> domain.role.v1.RoleType
	2, // 1: domain.role.v1.Role.lifecycle:type_name -> domain.common.v1.Lifecycle
	3, // 2: domain.role.v1.Role.source:type_name -> domain.common.v1.ExternalId
	4, // 3: domain.role.v1.Role.valid_from:type_name -> google.protobuf.Timestamp
	4, // 4: domain.role.v1.Role.valid_to:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_domain_role_v1_role_proto_init() }
func file_domain_role_v1_role_proto_init() {
	if File_domain_role_v1_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_role_v1_role_proto_rawDesc), len(file_domain_role_v1_role_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_role_v1_role_proto_goTypes,
		DependencyIndexes: file_domain_role_v1_role_proto_depIdxs,
		EnumInfos:         file_domain_role_v1_role_proto_enumTypes,
		MessageInfos:      file_domain_role_v1_role_proto_msgTypes,
	}.Build()
	File_domain_role_v1_role_proto = out.File
	file_domain_role_v1_role_proto_goTypes = nil
	file_domain_role_v1_role_proto_depIdxs = nil
}
