// Copyright 2026 Duizendstra. All rights reserved.
//
// Spoke sync — async replication between spoke (local) and hub (GitHub).
// Handles pull (reconcile), push (branch), PR (create), merge (rebase),
// and inside-out submodule ordering.
//
// Domain:  Development
// Concern: How do we sync code between spokes and the hub?

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: development/sync/v1/sync.proto

package syncv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncStatus is the overall outcome of a sync.
type SyncStatus int32

const (
	SyncStatus_SYNC_STATUS_UNSPECIFIED SyncStatus = 0
	// All repos synced and merged successfully.
	SyncStatus_SYNC_STATUS_COMPLETE SyncStatus = 1
	// Sync in progress (async — PR created, CI running).
	SyncStatus_SYNC_STATUS_PENDING SyncStatus = 2
	// Pull --rebase hit a conflict that needs manual resolution.
	SyncStatus_SYNC_STATUS_CONFLICT SyncStatus = 3
	// CI failed on the sync branch.
	SyncStatus_SYNC_STATUS_CI_FAILED SyncStatus = 4
	// Push or PR creation failed.
	SyncStatus_SYNC_STATUS_ERROR SyncStatus = 5
)

// Enum value maps for SyncStatus.
var (
	SyncStatus_name = map[int32]string{
		0: "SYNC_STATUS_UNSPECIFIED",
		1: "SYNC_STATUS_COMPLETE",
		2: "SYNC_STATUS_PENDING",
		3: "SYNC_STATUS_CONFLICT",
		4: "SYNC_STATUS_CI_FAILED",
		5: "SYNC_STATUS_ERROR",
	}
	SyncStatus_value = map[string]int32{
		"SYNC_STATUS_UNSPECIFIED": 0,
		"SYNC_STATUS_COMPLETE":    1,
		"SYNC_STATUS_PENDING":     2,
		"SYNC_STATUS_CONFLICT":    3,
		"SYNC_STATUS_CI_FAILED":   4,
		"SYNC_STATUS_ERROR":       5,
	}
)

func (x SyncStatus) Enum() *SyncStatus {
	p := new(SyncStatus)
	*p = x
	return p
}

func (x SyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_development_sync_v1_sync_proto_enumTypes[0].Descriptor()
}

func (SyncStatus) Type() protoreflect.EnumType {
	return &file_development_sync_v1_sync_proto_enumTypes[0]
}

func (x SyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncStatus.Descriptor instead.
func (SyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_development_sync_v1_sync_proto_rawDescGZIP(), []int{0}
}

// SyncRequest initiates a spoke→hub sync.
type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path to the repository root.
	RepoPath string `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	// Spoke identifier (e.g. hostname, agent ID).
	SpokeId string `protobuf:"bytes,2,opt,name=spoke_id,json=spokeId,proto3" json:"spoke_id,omitempty"`
	// When true, also sync submodules inside-out before the parent.
	IncludeSubmodules bool `protobuf:"varint,3,opt,name=include_submodules,json=includeSubmodules,proto3" json:"include_submodules,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_development_sync_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_development_sync_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_development_sync_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *SyncRequest) GetSpokeId() string {
	if x != nil {
		return x.SpokeId
	}
	return ""
}

func (x *SyncRequest) GetIncludeSubmodules() bool {
	if x != nil {
		return x.IncludeSubmodules
	}
	return false
}

// SyncResponse reports the outcome of a sync operation.
type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall sync status.
	Status SyncStatus `protobuf:"varint,1,opt,name=status,proto3,enum=development.sync.v1.SyncStatus" json:"status,omitempty"`
	// Human-readable summary.
	Summary string `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	// Per-repo sync results (root + submodules).
	Repos         []*RepoSyncResult `protobuf:"bytes,3,rep,name=repos,proto3" json:"repos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_development_sync_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_development_sync_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_development_sync_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetStatus() SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *SyncResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SyncResponse) GetRepos() []*RepoSyncResult {
	if x != nil {
		return x.Repos
	}
	return nil
}

// RepoSyncResult is the sync outcome for a single repository.
type RepoSyncResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Repo path (relative, e.g. "alexandria" or "." for root).
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Sync status for this repo.
	Status SyncStatus `protobuf:"varint,2,opt,name=status,proto3,enum=development.sync.v1.SyncStatus" json:"status,omitempty"`
	// Number of local commits being synced.
	CommitsAhead int32 `protobuf:"varint,3,opt,name=commits_ahead,json=commitsAhead,proto3" json:"commits_ahead,omitempty"`
	// Number of hub commits pulled (rebased onto).
	CommitsBehind int32 `protobuf:"varint,4,opt,name=commits_behind,json=commitsBehind,proto3" json:"commits_behind,omitempty"`
	// Sync branch name (e.g. "sync/antigravity-1711360000").
	Branch string `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`
	// PR URL if created.
	PrUrl string `protobuf:"bytes,6,opt,name=pr_url,json=prUrl,proto3" json:"pr_url,omitempty"`
	// Conflict details if status is CONFLICT.
	Conflicts []*ConflictDetail `protobuf:"bytes,7,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	// Error message if status is ERROR.
	Error         string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepoSyncResult) Reset() {
	*x = RepoSyncResult{}
	mi := &file_development_sync_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepoSyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepoSyncResult) ProtoMessage() {}

func (x *RepoSyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_development_sync_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepoSyncResult.ProtoReflect.Descriptor instead.
func (*RepoSyncResult) Descriptor() ([]byte, []int) {
	return file_development_sync_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *RepoSyncResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RepoSyncResult) GetStatus() SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *RepoSyncResult) GetCommitsAhead() int32 {
	if x != nil {
		return x.CommitsAhead
	}
	return 0
}

func (x *RepoSyncResult) GetCommitsBehind() int32 {
	if x != nil {
		return x.CommitsBehind
	}
	return 0
}

func (x *RepoSyncResult) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *RepoSyncResult) GetPrUrl() string {
	if x != nil {
		return x.PrUrl
	}
	return ""
}

func (x *RepoSyncResult) GetConflicts() []*ConflictDetail {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *RepoSyncResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ConflictDetail describes a single file conflict during rebase.
type ConflictDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File path (relative to repo root).
	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// Conflict type (e.g. "both_modified", "deleted_by_them").
	ConflictType  string `protobuf:"bytes,2,opt,name=conflict_type,json=conflictType,proto3" json:"conflict_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictDetail) Reset() {
	*x = ConflictDetail{}
	mi := &file_development_sync_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictDetail) ProtoMessage() {}

func (x *ConflictDetail) ProtoReflect() protoreflect.Message {
	mi := &file_development_sync_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictDetail.ProtoReflect.Descriptor instead.
func (*ConflictDetail) Descriptor() ([]byte, []int) {
	return file_development_sync_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *ConflictDetail) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *ConflictDetail) GetConflictType() string {
	if x != nil {
		return x.ConflictType
	}
	return ""
}

// StatusRequest queries a spoke's current sync state.
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute path to the repository root.
	RepoPath string `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	// Spoke identifier.
	SpokeId       string `protobuf:"bytes,2,opt,name=spoke_id,json=spokeId,proto3" json:"spoke_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_development_sync_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_development_sync_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_development_sync_v1_sync_proto_rawDescGZIP(), []int{4}
}

func (x *StatusRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *StatusRequest) GetSpokeId() string {
	if x != nil {
		return x.SpokeId
	}
	return ""
}

// StatusResponse reports the current sync state.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Commits ahead of remote (not yet synced).
	CommitsAhead int32 `protobuf:"varint,1,opt,name=commits_ahead,json=commitsAhead,proto3" json:"commits_ahead,omitempty"`
	// Commits behind remote (need pull).
	CommitsBehind int32 `protobuf:"varint,2,opt,name=commits_behind,json=commitsBehind,proto3" json:"commits_behind,omitempty"`
	// Pending PRs from this spoke.
	PendingPrs []*PendingPR `protobuf:"bytes,3,rep,name=pending_prs,json=pendingPrs,proto3" json:"pending_prs,omitempty"`
	// Last successful sync timestamp (RFC 3339).
	LastSync      string `protobuf:"bytes,4,opt,name=last_sync,json=lastSync,proto3" json:"last_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_development_sync_v1_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_development_sync_v1_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_development_sync_v1_sync_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetCommitsAhead() int32 {
	if x != nil {
		return x.CommitsAhead
	}
	return 0
}

func (x *StatusResponse) GetCommitsBehind() int32 {
	if x != nil {
		return x.CommitsBehind
	}
	return 0
}

func (x *StatusResponse) GetPendingPrs() []*PendingPR {
	if x != nil {
		return x.PendingPrs
	}
	return nil
}

func (x *StatusResponse) GetLastSync() string {
	if x != nil {
		return x.LastSync
	}
	return ""
}

// PendingPR is a sync PR that hasn't merged yet.
type PendingPR struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Url    string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Branch string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	// One of: open, ci_running, ci_passed, ci_failed, merged.
	State         string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingPR) Reset() {
	*x = PendingPR{}
	mi := &file_development_sync_v1_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingPR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingPR) ProtoMessage() {}

func (x *PendingPR) ProtoReflect() protoreflect.Message {
	mi := &file_development_sync_v1_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingPR.ProtoReflect.Descriptor instead.
func (*PendingPR) Descriptor() ([]byte, []int) {
	return file_development_sync_v1_sync_proto_rawDescGZIP(), []int{6}
}

func (x *PendingPR) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PendingPR) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *PendingPR) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// ResolveRequest resolves a sync conflict or retries a failed sync.
type ResolveRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RepoPath string                 `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	SpokeId  string                 `protobuf:"bytes,2,opt,name=spoke_id,json=spokeId,proto3" json:"spoke_id,omitempty"`
	// One of: "retry" (re-push), "abort" (abandon sync branch).
	Action        string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_development_sync_v1_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_development_sync_v1_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_development_sync_v1_sync_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *ResolveRequest) GetSpokeId() string {
	if x != nil {
		return x.SpokeId
	}
	return ""
}

func (x *ResolveRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// ResolveResponse confirms the resolution.
type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SyncStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=development.sync.v1.SyncStatus" json:"status,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_development_sync_v1_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_development_sync_v1_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_development_sync_v1_sync_proto_rawDescGZIP(), []int{8}
}

func (x *ResolveResponse) GetStatus() SyncStatus {
	if x != nil {
		return x.Status
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *ResolveResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_development_sync_v1_sync_proto protoreflect.FileDescriptor

const file_development_sync_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x1edevelopment/sync/v1/sync.proto\x12\x13development.sync.v1\"t\n" +
	"\vSyncRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x19\n" +
	"\bspoke_id\x18\x02 \x01(\tR\aspokeId\x12-\n" +
	"\x12include_submodules\x18\x03 \x01(\bR\x11includeSubmodules\"\x9c\x01\n" +
	"\fSyncResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.development.sync.v1.SyncStatusR\x06status\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x129\n" +
	"\x05repos\x18\x03 \x03(\v2#.development.sync.v1.RepoSyncResultR\x05repos\"\xb1\x02\n" +
	"\x0eRepoSyncResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.development.sync.v1.SyncStatusR\x06status\x12#\n" +
	"\rcommits_ahead\x18\x03 \x01(\x05R\fcommitsAhead\x12%\n" +
	"\x0ecommits_behind\x18\x04 \x01(\x05R\rcommitsBehind\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branch\x12\x15\n" +
	"\x06pr_url\x18\x06 \x01(\tR\x05prUrl\x12A\n" +
	"\tconflicts\x18\a \x03(\v2#.development.sync.v1.ConflictDetailR\tconflicts\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"I\n" +
	"\x0eConflictDetail\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12#\n" +
	"\rconflict_type\x18\x02 \x01(\tR\fconflictType\"G\n" +
	"\rStatusRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x19\n" +
	"\bspoke_id\x18\x02 \x01(\tR\aspokeId\"\xba\x01\n" +
	"\x0eStatusResponse\x12#\n" +
	"\rcommits_ahead\x18\x01 \x01(\x05R\fcommitsAhead\x12%\n" +
	"\x0ecommits_behind\x18\x02 \x01(\x05R\rcommitsBehind\x12?\n" +
	"\vpending_prs\x18\x03 \x03(\v2\x1e.development.sync.v1.PendingPRR\n" +
	"pendingPrs\x12\x1b\n" +
	"\tlast_sync\x18\x04 \x01(\tR\blastSync\"K\n" +
	"\tPendingPR\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"`\n" +
	"\x0eResolveRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x19\n" +
	"\bspoke_id\x18\x02 \x01(\tR\aspokeId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"d\n" +
	"\x0fResolveResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1f.development.sync.v1.SyncStatusR\x06status\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary*\xa8\x01\n" +
	"\n" +
	"SyncStatus\x12\x1b\n" +
	"\x17SYNC_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SYNC_STATUS_COMPLETE\x10\x01\x12\x17\n" +
	"\x13SYNC_STATUS_PENDING\x10\x02\x12\x18\n" +
	"\x14SYNC_STATUS_CONFLICT\x10\x03\x12\x19\n" +
	"\x15SYNC_STATUS_CI_FAILED\x10\x04\x12\x15\n" +
	"\x11SYNC_STATUS_ERROR\x10\x052\x83\x02\n" +
	"\vSyncService\x12K\n" +
	"\x04Sync\x12 .development.sync.v1.SyncRequest\x1a!.development.sync.v1.SyncResponse\x12Q\n" +
	"\x06Status\x12\".development.sync.v1.StatusRequest\x1a#.development.sync.v1.StatusResponse\x12T\n" +
	"\aResolve\x12#.development.sync.v1.ResolveRequest\x1a$.development.sync.v1.ResolveResponseBKZIgithub.com/duizendstra/alexandria/go/contracts/development/sync/v1;syncv1b\x06proto3"

var (
	file_development_sync_v1_sync_proto_rawDescOnce sync.Once
	file_development_sync_v1_sync_proto_rawDescData []byte
)

func file_development_sync_v1_sync_proto_rawDescGZIP() []byte {
	file_development_sync_v1_sync_proto_rawDescOnce.Do(func() {
		file_development_sync_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_development_sync_v1_sync_proto_rawDesc), len(file_development_sync_v1_sync_proto_rawDesc)))
	})
	return file_development_sync_v1_sync_proto_rawDescData
}

var file_development_sync_v1_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_development_sync_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_development_sync_v1_sync_proto_goTypes = []any{
	(SyncStatus)(0),         // 0: development.sync.v1.SyncStatus
	(*SyncRequest)(nil),     // 1: development.sync.v1.SyncRequest
	(*SyncResponse)(nil),    // 2: development.sync.v1.SyncResponse
	(*RepoSyncResult)(nil),  // 3: development.sync.v1.RepoSyncResult
	(*ConflictDetail)(nil),  // 4: development.sync.v1.ConflictDetail
	(*StatusRequest)(nil),   // 5: development.sync.v1.StatusRequest
	(*StatusResponse)(nil),  // 6: development.sync.v1.StatusResponse
	(*PendingPR)(nil),       // 7: development.sync.v1.PendingPR
	(*ResolveRequest)(nil),  // 8: development.sync.v1.ResolveRequest
	(*ResolveResponse)(nil), // 9: development.sync.v1.ResolveResponse
}
var file_development_sync_v1_sync_proto_depIdxs = []int32{
	0, // 0: development.sync.v1.SyncResponse.status:type_name -> development.sync.v1.SyncStatus
	3, // 1: development.sync.v1.SyncResponse.repos:type_name -> development.sync.v1.RepoSyncResult
	0, // 2: development.sync.v1.RepoSyncResult.status:type_name -> development.sync.v1.SyncStatus
	4, // 3: development.sync.v1.RepoSyncResult.conflicts:type_name -> development.sync.v1.ConflictDetail
	7, // 4: development.sync.v1.StatusResponse.pending_prs:type_name -> development.sync.v1.PendingPR
	0, // 5: development.sync.v1.ResolveResponse.status:type_name -> development.sync.v1.SyncStatus
	1, // 6: development.sync.v1.SyncService.Sync:input_type -> development.sync.v1.SyncRequest
	5, // 7: development.sync.v1.SyncService.Status:input_type -> development.sync.v1.StatusRequest
	8, // 8: development.sync.v1.SyncService.Resolve:input_type -> development.sync.v1.ResolveRequest
	2, // 9: development.sync.v1.SyncService.Sync:output_type -> development.sync.v1.SyncResponse
	6, // 10: development.sync.v1.SyncService.Status:output_type -> development.sync.v1.StatusResponse
	9, // 11: development.sync.v1.SyncService.Resolve:output_type -> development.sync.v1.ResolveResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_development_sync_v1_sync_proto_init() }
func file_development_sync_v1_sync_proto_init() {
	if File_development_sync_v1_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_development_sync_v1_sync_proto_rawDesc), len(file_development_sync_v1_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_development_sync_v1_sync_proto_goTypes,
		DependencyIndexes: file_development_sync_v1_sync_proto_depIdxs,
		EnumInfos:         file_development_sync_v1_sync_proto_enumTypes,
		MessageInfos:      file_development_sync_v1_sync_proto_msgTypes,
	}.Build()
	File_development_sync_v1_sync_proto = out.File
	file_development_sync_v1_sync_proto_goTypes = nil
	file_development_sync_v1_sync_proto_depIdxs = nil
}
